/* REQ-PLAT-31: ledger-corrections.json — regenerated by --regen with computed
   missingFrom; the verifier must record-once pre-cut and fail post-cut. */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const ROOT = process.cwd();
const EVAL = (body: string) =>
  execFileSync('node', ['--input-type=module', '-e',
    `const m = await import('${ROOT}/scripts/release/verify-release-ledger.mjs'); ${body}`],
  { cwd: ROOT, encoding: 'utf8' });

describe('ledger corrections (REQ-PLAT-31)', () => {
  const corrections = JSON.parse(readFileSync('docs/release/ledger-corrections.json', 'utf8'))
    .corrections as { version: string; missingFrom: string[] }[];
  it('every correction has a computed missingFrom list', () => {
    for (const c of corrections) expect(Array.isArray(c.missingFrom)).toBe(true);
    expect(corrections.length).toBeGreaterThan(0);
  });
  it('computeCorrections only emits pre-cut rows', () => {
    const out = EVAL(`console.log(JSON.stringify(m.computeCorrections({
      changelog: ['4.1.1','3.5.0'], tags: ['4.1.1'], gitlab: ['4.1.1','3.5.0'], npm: ['4.1.1','3.5.0'] })))`);
    expect(JSON.parse(out)).toEqual([{ version: '3.5.0', missingFrom: ['tag'], note: 'computed 4.1.1-cut regen' }]);
  });
  it('a post-cut missing row fails the check instead of correcting', () => {
    const out = EVAL(`const r = m.ledgerCheck({ changelog: ['4.1.1'], tags: [], gitlab: ['4.1.1'], npm: ['4.1.1'] });
      console.log(JSON.stringify(r.errors))`);
    expect(JSON.parse(out).join()).toContain('4.1.1');
  });
  it('--regen refuses to write on fetch failure', async () => {
    const out = EVAL(`try {
        await m.main(['--regen'], { root: '/nonexistent' });
      } catch (e) { console.log('ERR'); process.exit(0); }
      console.log('OK')`);
    expect(out.trim()).toContain('ERR');
  });
});
