/* REQ-PLAT-31: verify-release-ledger.mjs — for every version >= 4.1.1 the CHANGELOG heading, git
   tag, GitLab Release and npm version agree; pre-4.1.1 mismatches are recorded once each in
   docs/release/ledger-corrections.json with a computed missingFrom (regenerated by --regen);
   any source that cannot be read is an error, never an empty set. */
import { describe, expect, it } from '@jest/globals';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const ROOT = process.cwd();
/** Runs `body` in a child node with the module bound to `m`; prints are returned. */
const EVAL = (body: string, env: Record<string, string | undefined> = {}) =>
  execFileSync('node', ['--input-type=module', '-e',
    `const m = await import('${ROOT}/scripts/release/verify-release-ledger.mjs'); ${body}`],
  { cwd: ROOT, encoding: 'utf8', env: { ...process.env, CI_JOB_TOKEN: '', ...env } });
const json = (body: string, env?: Record<string, string | undefined>) => JSON.parse(EVAL(body, env));

// Stub sources for collectLive/main: git + npm + glab via execImpl, GitLab API via fetchImpl.
const STUBS = `
  const execOk = (cmd, args) => {
    if (cmd === 'git') return 'v4.0.0\\nv3.4.8\\n';
    if (cmd === 'npm') return JSON.stringify([['4.0.0', '3.4.8', '3.4.7']]);
    if (cmd === 'glab') return JSON.stringify([{ tag_name: 'v4.0.0' }]);
    throw new Error('unexpected ' + cmd);
  };
  const execFail = (bad) => (cmd, args, o) => { if (cmd === bad) throw new Error(bad + ' unreachable'); return execOk(cmd, args, o); };
`;

describe('release ledger (REQ-PLAT-31)', () => {
  it('parses CHANGELOG headings', () => {
    expect(json(`console.log(JSON.stringify(m.changelogVersions('# Changelog\\n## [4.2.0] — x\\n## 4.1.1\\n### sub')))`))
      .toEqual(['4.2.0', '4.1.1']);
  });

  it('passes when all ledgers agree', () => {
    expect(json(`const v = ['4.2.0', '4.1.1'];
      console.log(JSON.stringify(m.ledgerCheck({ changelog: v, tags: v, gitlab: v, npm: v }).errors))`)).toEqual([]);
  });

  it('fails on a >= cut version missing from any ledger', () => {
    const errors = json(`console.log(JSON.stringify(m.ledgerCheck({
      changelog: ['4.2.0'], tags: ['4.2.0'], gitlab: [], npm: ['4.2.0'] }).errors))`);
    expect(errors.join()).toMatch(/4\.2\.0: missing from gitlab-release/);
  });

  it('a pre-cut mismatch needs a record; a matching record passes; a stale record fails', () => {
    const r = json(`const live = { changelog: [], tags: ['3.4.8'], gitlab: ['3.4.8'], npm: ['3.4.8'] };
      console.log(JSON.stringify({
        none: m.ledgerCheck(live).errors,
        ok: m.ledgerCheck(live, { corrections: [{ version: '3.4.8', missingFrom: ['changelog'], note: 'n' }] }),
        stale: m.ledgerCheck(live, { corrections: [{ version: '3.4.8', missingFrom: ['npm'], note: 'n' }] }).errors,
      }))`);
    expect(r.none.join()).toMatch(/3\.4\.8: pre-4\.1\.1 mismatch missing from ledger-corrections\.json/);
    expect(r.ok.errors).toEqual([]);
    expect(r.ok.records.join()).toMatch(/3\.4\.8: recorded/);
    expect(r.stale.join()).toMatch(/3\.4\.8: ledger-corrections\.json is stale .*rerun --regen/);
  });

  it('--github mode includes GitHub Releases in the agreement set', () => {
    const errors = json(`console.log(JSON.stringify(m.ledgerCheck({
      changelog: ['4.2.0'], tags: ['4.2.0'], gitlab: ['4.2.0'], npm: ['4.2.0'], github: [] }).errors))`);
    expect(errors.join()).toMatch(/github-release/);
  });

  it('computeCorrections emits only pre-cut rows, each with its computed missingFrom', () => {
    expect(json(`console.log(JSON.stringify(m.computeCorrections({
      changelog: ['4.1.1', '3.5.0'], tags: ['4.1.1'], gitlab: ['4.1.1', '3.5.0'], npm: ['4.1.1', '3.5.0'] })))`))
      .toEqual([{ version: '3.5.0', missingFrom: ['tag'], note: 'computed 4.1.1-cut regen' }]);
  });

  describe('sources fail closed', () => {
    it.each([['git'], ['npm'], ['glab']])('%s failure is an error, not an empty set', (bad) => {
      const out = EVAL(`${STUBS}
        try { await m.collectLive({ execImpl: execFail('${bad}') }); console.log('RESOLVED'); }
        catch (e) { console.log('ERR ' + e.message); }`);
      expect(out).toMatch(/^ERR verify-release-ledger: .* fetch failed/);
    });

    it('a non-200 GitLab API answer (CI job token path) is an error', () => {
      const out = EVAL(`${STUBS}
        const fetchImpl = async () => ({ ok: false, status: 404, json: async () => ({}) });
        try { await m.collectLive({ execImpl: execOk, fetchImpl }); console.log('RESOLVED'); }
        catch (e) { console.log('ERR ' + e.message); }`, { CI_JOB_TOKEN: 'stub-job-token' });
      expect(out).toMatch(/^ERR .*GitLab releases .*HTTP 404/);
    });

    it('sends the job token and pages through the GitLab releases API', () => {
      const r = json(`${STUBS}
        const seen = [];
        const fetchImpl = async (url, init) => {
          seen.push([url.replace(/^.*releases/, 'releases'), init.headers['JOB-TOKEN']]);
          const page = Number(new URL(url).searchParams.get('page'));
          const rows = page === 1 ? Array.from({ length: 100 }, (_, i) => ({ tag_name: 'v0.0.' + i })) : [{ tag_name: 'v4.0.0' }];
          return { ok: true, status: 200, json: async () => rows };
        };
        const live = await m.collectLive({ execImpl: execOk, fetchImpl });
        console.log(JSON.stringify({ seen, n: live.gitlab.length, last: live.gitlab.at(-1) }))`, { CI_JOB_TOKEN: 'stub-job-token' });
      expect(r.seen).toEqual([['releases?per_page=100&page=1', 'stub-job-token'], ['releases?per_page=100&page=2', 'stub-job-token']]);
      expect(r.n).toBe(101);
      expect(r.last).toBe('4.0.0');
    });

    it('an answered empty release list is data, and the npm array wrapper is unwrapped', () => {
      const live = json(`${STUBS}
        const exec = (cmd, a, o) => cmd === 'glab' ? '[]' : execOk(cmd, a, o);
        console.log(JSON.stringify(await m.collectLive({ execImpl: exec })))`);
      expect(live.gitlab).toEqual([]);
      expect(live.npm).toEqual(['4.0.0', '3.4.8', '3.4.7']);
      expect(live.tags).toEqual(['4.0.0', '3.4.8']);
    });
  });

  describe('--regen', () => {
    const withRoot = (fn: (root: string) => void) => {
      const root = mkdtempSync(join(tmpdir(), 'ledger-'));
      try {
        writeFileSync(join(root, 'CHANGELOG.md'), '# Changelog\n## [4.0.0] - x\n## [3.4.7] - y\n');
        fn(root);
      } finally { rmSync(root, { recursive: true, force: true }); }
    };

    it('writes nothing when a source fails', () => withRoot((root) => {
      const out = EVAL(`${STUBS}
        try { await m.main(['--regen'], { root: '${root}', execImpl: execFail('npm') }); console.log('WROTE'); }
        catch (e) { console.log('ERR ' + e.message); }`);
      expect(out).toMatch(/^ERR .*npm view aura-glass versions fetch failed/);
      expect(existsSync(join(root, 'docs/release/ledger-corrections.json'))).toBe(false);
    }));

    it('computes every row from the sources and records the source sizes', () => withRoot((root) => {
      EVAL(`${STUBS}
        const { mkdirSync } = await import('node:fs');
        mkdirSync('${root}/docs/release', { recursive: true });
        process.exitCode = await m.main(['--regen'], { root: '${root}', execImpl: execOk });`);
      const file = JSON.parse(readFileSync(join(root, 'docs/release/ledger-corrections.json'), 'utf8'));
      expect(file.sources).toEqual({ changelog: 2, tags: 2, gitlabReleases: 1, npm: 3 });
      expect(file.corrections).toEqual([
        { version: '3.4.7', missingFrom: ['tag', 'gitlab-release'], note: 'computed 4.1.1-cut regen' },
        { version: '3.4.8', missingFrom: ['changelog', 'gitlab-release'], note: 'computed 4.1.1-cut regen' },
      ]);
    }));
  });

  describe('committed docs/release/ledger-corrections.json', () => {
    const file = JSON.parse(readFileSync('docs/release/ledger-corrections.json', 'utf8')) as {
      generatedAt: string; cut: string; sources: Record<string, number>;
      corrections: { version: string; missingFrom: string[]; note: string }[];
    };
    it('is a --regen output (timestamp, cut, source sizes)', () => {
      expect(Number.isNaN(Date.parse(file.generatedAt))).toBe(false);
      expect(file.cut).toBe('4.1.1');
      for (const k of ['changelog', 'tags', 'gitlabReleases', 'npm']) expect(typeof file.sources[k]).toBe('number');
    });
    it('every row is pre-cut, computed, and names only known sources', () => {
      const known = new Set(['changelog', 'tag', 'gitlab-release', 'npm', 'github-release']);
      expect(file.corrections.length).toBeGreaterThan(0);
      for (const c of file.corrections) {
        const [maj = 0, min = 0, pat = 0] = c.version.split('-')[0]!.split('.').map(Number);
        expect(maj * 1e6 + min * 1e3 + pat).toBeLessThan(4 * 1e6 + 1 * 1e3 + 1);
        expect(c.missingFrom.length).toBeGreaterThan(0);
        for (const s of c.missingFrom) expect(known.has(s)).toBe(true);
        expect(c.note).toBe('computed 4.1.1-cut regen');
      }
      expect(new Set(file.corrections.map((c) => c.version)).size).toBe(file.corrections.length);
    });
    it('records each pre-4.1.1 mismatch the PRD names', () => {
      const vers = file.corrections.map((c) => c.version);
      for (const v of ['3.4.8', '3.5.0', '3.0.7', '2.17.0', '2.16.4', '2.0.7', '2.0.8']) expect(vers).toContain(v);
      // v1 releases have no git tags.
      for (const c of file.corrections.filter((x) => x.version.startsWith('1.'))) expect(c.missingFrom).toContain('tag');
    });
    it('CHANGELOG.md carries the Ledger corrections note', () => {
      expect(readFileSync('CHANGELOG.md', 'utf8')).toMatch(/^## Ledger corrections\n[\s\S]*docs\/release\/ledger-corrections\.json/m);
    });
  });
});
