import { defineMeta } from '../../foundation';

export default defineMeta({
  name: 'Button',
  owner: 'CMP',
  entry: '.',
  tier: 'T1',
  flagship: 1,
  rsc: 'client',
  parts: ['root', 'icon', 'label', 'spinner', 'hit-area'],
  states: ['hover', 'active', 'focus-visible', 'pressed', 'disabled', 'loading'],
  variants: {
    variant: ['regular', 'clear', 'identity'],
    prominent: ['true', 'false'],
    intent: ['neutral', 'danger'],
    size: ['sm', 'md', 'lg'],
  },
  material: { layer: 'chrome', refractionEligible: true },
  apg: 'button',
  budgetKb: 10,
  migration: [
    {
      from: 'GlassButton',
      props: {
        variant: { to: 'prominent', values: { primary: 'true' } },
        'variant:secondary': 'variant:regular',
        'variant:default': 'variant:regular',
        'variant:outline': { to: 'variant', values: { outline: 'regular' } },
        'variant:ghost': { to: 'variant', values: { ghost: 'identity' } },
        'variant:tertiary': { to: 'variant', values: { tertiary: 'identity' } },
        'variant:link': { to: 'variant', values: { link: 'identity' } },
        'variant:gradient': null,
        'variant:aurora': null,
        'variant:success': null,
        'variant:warning': null,
        'variant:danger': 'intent',
        'variant:destructive': 'intent',
        'variant:error': 'intent',
        'size:xs': { to: 'size', values: { xs: 'sm' } },
        'size:xl': { to: 'size', values: { xl: 'lg' } },
        asChild: 'render',
        leftIcon: 'startIcon',
        rightIcon: 'endIcon',
        material: null,
        glassVariant: { to: 'variant', values: { clear: 'clear' } },
        onChange: 'onPressedChange',
      },
      selectors: { '.glass-button': '.ag-button' },
      automation: 'mostly',
      compat: true,
    },
    {
      from: 'EnhancedGlassButton',
      props: { variant: 'prominent', leftIcon: 'startIcon', rightIcon: 'endIcon' },
      selectors: { '.glass-enhanced-glass-button': '.ag-button' }, automation: 'partial',
      compat: true,
    },
    {
      from: 'GlassMagneticButton',
      props: { magnetic: null, variant: 'prominent' },
      selectors: { '.glass-magnetic-button': '.ag-button' }, automation: 'partial',
      compat: true,
    },
  ],
});
