/* fragments/size-budgets/cmp.ts — CMP owns this file on both branches (§3.4).
   CMP-044/053: provisional rows (min+gz, peers external) at/below PERF default
   ceilings; recorded in docs/size-budgets.changelog.md. */
import type { SizeBudgetRow } from '../../src/contracts/fragments';
export default [
  { id: 'Card', import: "{ Card } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Badge', import: "{ Badge } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Separator', import: "{ Separator } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Kbd', import: "{ Kbd } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Text', import: "{ Text } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Heading', import: "{ Heading } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Stack', import: "{ Stack } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Grid', import: "{ Grid } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Container', import: "{ Container } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'DescriptionList', import: "{ DescriptionList } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'EmptyState', import: "{ EmptyState } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'ErrorState', import: "{ ErrorState } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'LoadingState', import: "{ LoadingState } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Steps', import: "{ Steps } from 'aura-glass'", limitBytes: 1500, kind: 'js' },
  { id: 'Button', import: "{ Button } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'IconButton', import: "{ IconButton } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'ButtonGroup', import: "{ ButtonGroup } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'Toolbar', import: "{ Toolbar } from 'aura-glass'", limitBytes: 13000, kind: 'js' },
  { id: 'ToggleGroup', import: "{ ToggleGroup } from 'aura-glass'", limitBytes: 11000, kind: 'js' },
  { id: 'SegmentedControl', import: "{ SegmentedControl } from 'aura-glass'", limitBytes: 13000, kind: 'js' },
  { id: 'AvatarGroup', import: "{ AvatarGroup } from 'aura-glass'", limitBytes: 3000, kind: 'js' },
  { id: 'Alert', import: "{ Alert } from 'aura-glass'", limitBytes: 3000, kind: 'js' },
  { id: 'Skeleton', import: "{ Skeleton } from 'aura-glass'", limitBytes: 3000, kind: 'js' },
  { id: 'Link', import: "{ Link } from 'aura-glass'", limitBytes: 3000, kind: 'js' },
  { id: 'Avatar', import: "{ Avatar } from 'aura-glass'", limitBytes: 3000, kind: 'js' },
  { id: 'Chip', import: "{ Chip } from 'aura-glass/data'", limitBytes: 3000, kind: 'js' },
  { id: 'Progress', import: "{ Progress } from 'aura-glass'", limitBytes: 5000, kind: 'js' },
  { id: 'Meter', import: "{ Meter } from 'aura-glass'", limitBytes: 5000, kind: 'js' },
  { id: 'Collapsible', import: "{ Collapsible } from 'aura-glass'", limitBytes: 5000, kind: 'js' },
  { id: 'Accordion', import: "{ Accordion } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'ScrollArea', import: "{ ScrollArea } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'Rating', import: "{ Rating } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'InlineEdit', import: "{ InlineEdit } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'Form', import: "{ Form } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'Tour', import: "{ Tour } from 'aura-glass'", limitBytes: 15000, kind: 'js' },
  { id: 'FileUpload', import: "{ FileUpload } from 'aura-glass'", limitBytes: 15000, kind: 'js' },
  { id: 'KeyValueEditor', import: "{ KeyValueEditor } from 'aura-glass/data'", limitBytes: 15000, kind: 'js' },
  { id: 'ColorPicker', import: "{ ColorPicker } from 'aura-glass'", limitBytes: 20000, kind: 'js' },
  { id: 'icon-glyph-each', import: "{ CheckIcon } from 'aura-glass/icons'", limitBytes: 1000, kind: 'js' },
  { id: 'aura-glass/primitives', import: "'aura-glass/primitives'", limitBytes: 4000, kind: 'js' },
  // ≤1.2 KB CSS each; T2 CSS total ≤12 KB
  { id: 'VisuallyHidden.css', import: "src/primitives/VisuallyHidden.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'StateView.css', import: "src/components/state-view/StateView.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Steps.css', import: "src/components/steps/Steps.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'AvatarGroup.css', import: "src/components/avatar/AvatarGroup.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Chip.css', import: "src/components/chip/Chip.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'KeyValueEditor.css', import: "src/components/key-value-editor/KeyValueEditor.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Form.css', import: "src/components/field/Form.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 't2-css-total', import: "aura-glass/styles.css | cmp-t2", limitBytes: 12000, kind: 'css' },
  { id: 'Button.css', import: "src/components/button/Button.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'IconButton.css', import: "src/components/icon-button/IconButton.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Toolbar.css', import: "src/components/toolbar/Toolbar.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'ButtonGroup.css', import: "src/components/button-group/ButtonGroup.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'ToggleGroup.css', import: "src/components/toggle-group/ToggleGroup.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'SegmentedControl.css', import: "src/components/segmented-control/SegmentedControl.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  // CMP-165 — §16 inputs rows (provisional until calibration, D-26)
  { id: 'Switch', import: "{ Switch } from 'aura-glass'", limitBytes: 8000, kind: 'js' },
  { id: 'Slider', import: "{ Slider } from 'aura-glass'", limitBytes: 14000, kind: 'js' },
  { id: 'Checkbox+CheckboxGroup', import: "{ Checkbox, CheckboxGroup } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'RadioGroup', import: "{ RadioGroup } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'TextField', import: "{ TextField } from 'aura-glass'", limitBytes: 12000, kind: 'js' },
  { id: 'SearchField', import: "{ SearchField } from 'aura-glass'", limitBytes: 13000, kind: 'js' },
  { id: 'Select', import: "{ Select } from 'aura-glass'", limitBytes: 25000, kind: 'js' },
  { id: 'Combobox', import: "{ Combobox } from 'aura-glass'", limitBytes: 30000, kind: 'js' },
  { id: 'NumberField', import: "{ NumberField } from 'aura-glass'", limitBytes: 14000, kind: 'js' },
  { id: 'controls-all-families', import: "{ Button, IconButton, ButtonGroup, Toolbar, ToggleGroup, SegmentedControl, Switch, Slider, Checkbox, CheckboxGroup, RadioGroup, TextField, SearchField, Select, Combobox, NumberField, Field, Fieldset } from 'aura-glass'", limitBytes: 60000, kind: 'js' },
  { id: 'aura-glass/forms', import: "'aura-glass/forms'", limitBytes: 4000, kind: 'js' },
  // CMP-165 — controls CSS (§16 controls ≤7 KB total)
  { id: 'controls.css', import: "src/components/control-shared/controls.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Field.css', import: "src/components/field/Field.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'TextField.css', import: "src/components/text-field/TextField.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'SearchField.css', import: "src/components/search-field/SearchField.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'NumberField.css', import: "src/components/number-field/NumberField.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Checkbox.css', import: "src/components/checkbox/Checkbox.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'RadioGroup.css', import: "src/components/radio-group/RadioGroup.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Switch.css', import: "src/components/switch/Switch.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'Slider.css', import: "src/components/slider/Slider.css | aura-glass/styles.css", limitBytes: 1200, kind: 'css' },
  { id: 'controls-css-total', import: "aura-glass/styles.css | cmp-controls", limitBytes: 7000, kind: 'css' },
  // CMP-218/227/238 — §16 overlay rows (provisional until alpha calibration, D-26; ratchet down only)
  { id: 'Dialog', import: "{ Dialog } from 'aura-glass'", limitBytes: 20000, kind: 'js' },
  { id: 'AlertDialog', import: "{ AlertDialog } from 'aura-glass'", limitBytes: 20000, kind: 'js' },
  { id: 'Sheet', import: "{ Sheet } from 'aura-glass'", limitBytes: 24000, kind: 'js' },
  { id: 'Popover', import: "{ Popover } from 'aura-glass'", limitBytes: 14000, kind: 'js' },
  { id: 'Tooltip', import: "{ Tooltip } from 'aura-glass'", limitBytes: 10000, kind: 'js' },
  { id: 'Menu', import: "{ Menu, ContextMenu, Menubar } from 'aura-glass'", limitBytes: 22000, kind: 'js' },
  { id: 'Toast', import: "{ Toast, useToast } from 'aura-glass'", limitBytes: 14000, kind: 'js' },
  { id: 'Dialog.css', import: "src/components/dialog/Dialog.css | aura-glass/styles.css", limitBytes: 4000, kind: 'css' },
  { id: 'AlertDialog.css', import: "src/components/alert-dialog/AlertDialog.css | aura-glass/styles.css", limitBytes: 4000, kind: 'css' },
  { id: 'Sheet.css', import: "src/components/sheet/Sheet.css | aura-glass/styles.css", limitBytes: 5000, kind: 'css' },
  { id: 'overlays.css', import: "src/components/overlays/_shared/overlays.css | aura-glass/styles.css", limitBytes: 3000, kind: 'css' },
] satisfies SizeBudgetRow[];
