/** aura-glass root double: real cmp doubles where they exist, factory
 * stubs elsewhere. S-24/S-30 seeds. */
export { Dialog } from '../cmp/dialog';
export { Menu } from '../cmp/menu';
export { Popover } from '../cmp/popover';
export { Toolbar } from '../cmp/toolbar';
export { Tooltip } from '../cmp/tooltip';
export { Collapsible } from '../cmp/collapsible';
export { ScrollArea } from '../cmp/scroll-area';
import { comp, compound } from './_factory';
export const Select = compound('Select'); // overrides: registry uses Select.Root/Trigger/Content/Item
export const Combobox = compound('Combobox');
export const Slider = compound('Slider');
export const Text = comp('Text');
export const Badge = comp('Badge');
export const Button = comp('Button');
export const IconButton = comp('IconButton');
export const Link = comp('Link');
export const Separator = comp('Separator');
export const TextField = comp('TextField');
export const Switch = comp('Switch');
export const Checkbox = comp('Checkbox');
export const CheckboxGroup = comp('CheckboxGroup');
export const StatCard = comp('StatCard');
export const ChartFrame = comp('ChartFrame');
export const Sparkline = comp('Sparkline');
export const AvatarGroup = comp('AvatarGroup');
export const Toast = comp('Toast');
export const Alert = comp('Alert');
export const Progress = comp('Progress');
export const Avatar = compound('Avatar');
export const Card = compound('Card');
export const Field = compound('Field');
export const Pagination = compound('Pagination');
export const SegmentedControl = compound('SegmentedControl');
export const TabBar = compound('TabBar');
export const Tabs = compound('Tabs');
export const FilterBar = comp('FilterBar');
export const Table = comp('Table');
export const TreeView = comp('TreeView');
export const MobileShell = comp('MobileShell');
export const Backdrop = comp('Backdrop');
export const DateRangePicker = comp('DateRangePicker');
export const AgentSteps = comp('AgentSteps');
export const Thread = comp('Thread');
export const UsageMeter = comp('UsageMeter');
export const AppShell = compound('AppShell');
export const Sidebar = compound('Sidebar');
export const TopBar = compound('TopBar');
export const StatusBar = compound('StatusBar');
export const Inspector = compound('Inspector');
export const ResizablePanels = compound('ResizablePanels');
export const ImageViewer = compound('ImageViewer');
export const MediaControls = compound('MediaControls');
export const NowPlayingBar = compound('NowPlayingBar');
export const Composer = compound('Composer');
export const GlassPreferencesPanel = comp('GlassPreferencesPanel');
