#!/usr/bin/env node
/* @ag-contract-seed: S-10, S-11, S-52. Owner MAT replaces internals with the real Style Dictionary
   compiler; the CLI contract (npm run tokens:build, output paths) is frozen.
   Seed: writes TOKEN_OUTPUTS from PUBLIC_CSS_VARS and MOTION_CSS_VARS with placeholder values
   ('initial' for colours, '0' for dimensions); every CSS file is layered per S-04. Idempotent. */
import { build } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

async function loadContract(specifier) {
  const res = await build({
    stdin: { contents: `export * from '${specifier}';`, resolveDir: root, loader: 'ts' },
    bundle: true, write: false, format: 'esm', platform: 'node', logLevel: 'silent',
  });
  const url = 'data:text/javascript;base64,' + Buffer.from(res.outputFiles[0].text).toString('base64');
  return import(url);
}

const { PUBLIC_CSS_VARS, LAYER_ORDER_STATEMENT, TOKEN_OUTPUTS } = await loadContract('./src/contracts/tokens.ts');
const { MOTION_CSS_VARS, DURATIONS_MS, AMBIENT_DURATION_MS, EASES, SPRINGS } = await loadContract('./src/contracts/motion.ts');

const allVars = Object.values(PUBLIC_CSS_VARS).flat().concat([...MOTION_CSS_VARS]);
const isColor = (name) => name.startsWith('--ag-color') || name.startsWith('--ag-surface') ||
  ['--background', '--foreground', '--primary', '--primary-foreground', '--muted', '--border', '--ring'].includes(name);
const value = (name) => (isColor(name) ? 'initial' : name === '--ag-density' ? '1' : '0');

const write = (rel, content) => {
  const p = join(root, rel);
  mkdirSync(dirname(p), { recursive: true });
  const prev = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (prev !== content) writeFileSync(p, content);
  console.log(`${prev === content ? 'ok' : 'wrote'} ${rel}`);
};

// dist/tokens.css — every public var at its placeholder value, under @layer ag.tokens (S-04)
write(TOKEN_OUTPUTS.css.replace(/^dist\//, 'dist/'), [
  LAYER_ORDER_STATEMENT, '', '@layer ag.tokens {', '  :root {',
  ...allVars.map((v) => `    ${v}: ${value(v)};`), '  }', '}', '',
].join('\n'));

// dist/tokens/manifest.json — TokenManifest (S-11)
write(TOKEN_OUTPUTS.manifest, JSON.stringify({
  version: 1, generatedFrom: 'tokens/**/*.tokens.json',
  tokens: allVars.map((v) => ({
    name: v.replace(/^--(ag-)?/, '').replaceAll('-', '.'),
    cssVar: v,
    type: isColor(v) ? 'color' : 'dimension',
    tier: 'sys', modes: {}, value: value(v),
  })),
}, null, 1) + '\n');

// src/tokens/index.ts — committed generated module (S-10)
write(TOKEN_OUTPUTS.ts, [
  '/* @generated by scripts/tokens/build.mjs (seed). Do not edit by hand; MAT regenerates in its own PRs. */',
  'export const tokens = {',
  ...allVars.map((v) => `  ${JSON.stringify(v)}: 'var(${v})',`),
  '} as const;',
  'export type TokenName = keyof typeof tokens;', '',
].join('\n'));

// src/motion/tokens.generated.ts — committed generated module
write(TOKEN_OUTPUTS.motionTs, [
  '/* @generated by scripts/tokens/build.mjs (seed). Do not edit by hand; MAT regenerates in its own PRs. */',
  'export const motionTokens = {',
  ...Object.entries(DURATIONS_MS).flatMap(([d, v]) =>
    [`  'duration-${d}': ${v.enter},`, `  'duration-${d}-exit': ${v.exit},`]),
  `  'duration-ambient': ${AMBIENT_DURATION_MS},`,
  ...Object.entries(EASES).map(([e, v]) => `  'ease-${e}': 'cubic-bezier(${v.join(', ')})',`),
  ...Object.entries(SPRINGS).flatMap(([s, v]) =>
    [`  'spring-${s}': ${v.zeta},`, `  'spring-${s}-duration': ${v.responseMs},`]),
  '} as const;', '',
].join('\n'));

// src/material/css/generated/{ladders,floors}.css — committed generated sheets
for (const f of [TOKEN_OUTPUTS.ladders, TOKEN_OUTPUTS.floors]) {
  write(f, [LAYER_ORDER_STATEMENT, '', '@layer ag.material {', '  /* seed: MAT replaces with the compiled ladders/floors */',
    '  [data-ag-surface] {', '    --ag-surface-fill: var(--ag-glass-opacity, initial);', '  }', '}', ''].join('\n'));
}

// dist/compat/tokens.css — from tokens/compat-alias-map.json (H03 on 4.x); absent -> empty layer at C0
const aliasPath = join(root, 'tokens', 'compat-alias-map.json');
const aliases = existsSync(aliasPath) ? JSON.parse(readFileSync(aliasPath, 'utf8')) : {};
write(TOKEN_OUTPUTS.compat, [
  LAYER_ORDER_STATEMENT, '', '@layer ag.compat {', '  :root {',
  ...Object.entries(aliases).map(([from, to]) => `    ${from}: var(${to});`), '  }', '}', '',
].join('\n'));
