#!/usr/bin/env node
/* Token build — release/4.x platform bridge-4x (bridge H cells, contract §2.4).

   Reads tokens/compat-alias-map.json + tokens/legacy/4x-rendered.tokens.json and
   emits the committed bridge files:
     src/material/compat/tokens.css  — @layer ag.compat alias sheet
     src/styles/v5.css               — @layer ag.tokens subset: every --ag-* var
                                      the alias map succeeds to, at its 5.0 value
     src/styles/preview-v5.css       — opt-in preview composition (tokens + compat)
   plus the dist mirror dist/tokens/4x/. The job mat:build:bridge replays this and
   diffs src/material src/styles/v5.css src/styles/preview-v5.css. */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const platform = args[args.indexOf('--platform') + 1];
if (platform !== 'bridge-4x') {
  console.error(`build.mjs: only --platform bridge-4x is supported on this line (got "${platform}")`);
  process.exit(1);
}

const map = JSON.parse(readFileSync('tokens/compat-alias-map.json', 'utf8'));

/* 5.0 contract values for every --ag-* name a successor may point at (subset
   emitted by the bridge — the full table is tokens/generated/tokens.css on
   the next line). Keep in sync with the contract token table. */
const AG_VALUES = {
  '--ag-space-0': '0', '--ag-space-1': '4px', '--ag-space-2': '8px', '--ag-space-3': '12px',
  '--ag-space-4': '16px', '--ag-space-5': '20px', '--ag-space-6': '24px', '--ag-space-8': '32px',
  '--ag-space-10': '40px', '--ag-space-12': '48px', '--ag-space-16': '64px',
  '--ag-radius-xs': '6px', '--ag-radius-sm': '10px', '--ag-radius-md': '14px',
  '--ag-radius-lg': '20px', '--ag-radius-xl': '28px', '--ag-radius-full': '9999px',
  '--ag-duration-small': '160ms', '--ag-duration-medium': '240ms', '--ag-duration-large': '320ms',
};

const light = [], dark = [];
for (const [name, e] of Object.entries(map.entries)) {
  if (e.successor) { light.push(`${name}: var(${e.successor});`); continue; }
  const fv = e.frozenValue;
  if (fv === null) { light.push(`/* ${name}: ${e.note} */`); continue; }
  if (typeof fv === 'object') {
    light.push(`${name}: ${fv.light};`);
    if (fv.dark !== undefined && fv.dark !== fv.light) dark.push(`${name}: ${fv.dark};`);
  } else light.push(`${name}: ${fv};`);
}

const usedSuccessors = [...new Set(Object.values(map.entries).map(e => e.successor).filter(Boolean))].sort();
const missing = usedSuccessors.filter(s => AG_VALUES[s] === undefined);
if (missing.length) {
  console.error(`build.mjs: alias map references successors with no known 5.0 value: ${missing.join(', ')}`);
  process.exit(1);
}
const tokenLines = usedSuccessors.map(s => `${s}: ${AG_VALUES[s]};`);

const BANNER = '/* generated by scripts/tokens/build.mjs --platform bridge-4x — do not edit */';
const compatBlock = [
  '@layer ag.compat {',
  ':where(:root) {',
  ...light,
  '}',
  ...(dark.length ? [':where(:root[data-ag-scheme="dark"]) {', ...dark, '}'] : []),
  '}',
].join('\n');
const tokensBlock = [
  '@layer ag.tokens {',
  ':where(:root) {',
  '/* bridge subset: --ag-* successors referenced by the compat alias map.',
  '   The complete 5.0 token table is tokens/generated/tokens.css on the next line. */',
  ...tokenLines,
  '}',
  '}',
].join('\n');

const files = {
  'src/material/compat/tokens.css': `${BANNER}\n${compatBlock}\n`,
  'src/styles/v5.css': `${BANNER}\n${tokensBlock}\n`,
  'src/styles/preview-v5.css': `${BANNER}\n/* opt-in 4.x preview: 5.0 successor values + --glass-* aliases. */\n${tokensBlock}\n\n${compatBlock}\n`,
};
for (const [p, c] of Object.entries(files)) {
  mkdirSync(p.slice(0, p.lastIndexOf('/')), { recursive: true });
  writeFileSync(p, c);
}

const distDir = 'dist/tokens/4x';
mkdirSync(distDir, { recursive: true });
writeFileSync(`${distDir}/tokens.css`, `${BANNER}\n${tokensBlock}\n`);
writeFileSync(`${distDir}/compat-tokens.css`, `${BANNER}\n${compatBlock}\n`);
writeFileSync(`${distDir}/preview-v5.css`, `${BANNER}\n${tokensBlock}\n\n${compatBlock}\n`);
writeFileSync(`${distDir}/manifest.json`, JSON.stringify({
  platform: 'bridge-4x',
  source: 'tokens/compat-alias-map.json + tokens/legacy/4x-rendered.tokens.json',
  outputs: ['tokens.css', 'compat-tokens.css', 'preview-v5.css'],
  successors: usedSuccessors.length,
  entries: map.counts.total,
}, null, 1) + '\n');

console.log(`bridge-4x: ${map.counts.total} aliases (${map.counts.mapped} successors), ${usedSuccessors.length} --ag-* emitted; dist/tokens/4x/ written`);
