/* Material ladder emitters (MAT-038/040/048): MaterialSpec -> ladders.css + floors.css +
   properties.css. Keying is [data-ag-variant="<v>"][data-ag-thickness="<t>"] (data-ag-material
   is a banned attribute — material.ts S-01). backdrop-filter literals are emitted per
   [variant][thickness][tier] for the 2 blurred variants x 3 thicknesses x 3 DOM tiers = 18. */
import { colorToCss } from './color.mjs';

const VARIANTS = ['regular', 'clear', 'identity'];
const BLURRED = ['regular', 'clear'];                     // identity has no backdrop filter
const THICKNESS = ['thin', 'regular', 'thick'];
const DOM_TIERS = ['lightweight', 'standard', 'enhanced']; // data-ag-tier (material.ts)
const TIER_BLUR_SCALE = { lightweight: 0.5, standard: 1, enhanced: 1 };
const LADDER_STEPS = 9;

const dim = (v) => `${v.value}${v.unit}`;
const shadowCss = (s) => `${dim(s.offsetX)} ${dim(s.offsetY)} ${dim(s.blur)} ${dim(s.spread ?? { value: 0, unit: 'px' })} ${colorToCss(s.color)}`;

function get(records, resolved, name) {
  const rec = records.get(name);
  if (!rec) throw new Error(`ladders: missing token ${name}`);
  return resolved.get(name);
}

/** The sole MaterialSpec (MAT-021): material.material is a single glass-material token
 *  shaped per tokens/$schema.json $defs.materialValue (variants x thickness cells,
 *  content, tint, scrim, fallbackFill, refraction). */
function materialSpec(records, resolved) {
  const spec = get(records, resolved, 'material.material');
  if (!spec?.variants?.regular || !spec?.refraction?.bezel || !spec?.scrim)
    throw new Error('ladders: material.material is not a MaterialSpec (needs variants, refraction.bezel, scrim)');
  return spec;
}

/** ladders.css — per-cell recipe vars + backdrop-filter literals (MAT-038/041). */
export function buildLadders(records, resolved) {
  const spec = materialSpec(records, resolved);
  const cell = (v, t) => spec.variants[v][t];
  const bezel = (t) => dim(spec.refraction.bezel[t]);
  const shadow = (t) => `var(--ag-shadow-${t})`;
  // elevation ladder steps: 9 linear increments of 0.03 above the cell's tint alpha
  const LADDER_STEP = 0.03;

  const out = [
    '/* @generated by scripts/tokens/build.mjs (ladders). Do not edit. */',
    '@layer ag.compat, ag.reset, ag.tokens, ag.material, ag.components, ag.a11y;',
    '',
    '@layer ag.material {',
  ];
  for (const variant of VARIANTS) {
    for (const th of THICKNESS) {
      const c = cell(variant, th);
      const b = c.blur;
      if (b.unit === 'px' && b.value > 32) throw new Error(`blur > 32px at material.material.variants.${variant}.${th}`);
      out.push(`  [data-ag-variant="${variant}"][data-ag-thickness="${th}"] {`);
      out.push(`    --_ag-mat-blur: ${dim(b)};`);
      out.push(`    --_ag-mat-saturation: ${c.saturation};`);
      out.push(`    --_ag-mat-grain: ${c.grain};`);
      out.push(`    --_ag-mat-rim: ${dim(c.rim)};`);
      out.push(`    --_ag-mat-bezel: ${bezel(th)};`);
      out.push(`    --_ag-mat-tint-alpha: ${c.alpha};`);
      out.push(`    --_ag-mat-shadow: ${shadow(th)};`);
      out.push(`    --_ag-surface-alpha: ${c.alpha};`); // disabled state scales this (MAT-018)
      out.push(`    --ag-surface-fill: oklch(from var(--ag-color-canvas) l c h / var(--_ag-alpha, ${c.alpha}));`);
      for (let i = 1; i <= LADDER_STEPS; i++)
        out.push(`    --_ag-ladder-${i}: ${Math.round((c.alpha + i * LADDER_STEP) * 10000) / 10000};`);
      out.push('  }');
    }
  }
  // backdrop-filter literals: blurred variants x thickness x DOM tier (18 rules, MAT-041)
  for (const variant of BLURRED) {
    for (const th of THICKNESS) {
      for (const tier of DOM_TIERS) {
        const b = cell(variant, th).blur;
        const scaled = Math.round(b.value * TIER_BLUR_SCALE[tier] * 100) / 100;
        out.push(`  [data-ag-variant="${variant}"][data-ag-thickness="${th}"][data-ag-tier="${tier}"],`);
        out.push(`  [data-ag-tier="${tier}"] [data-ag-variant="${variant}"][data-ag-thickness="${th}"] {`);
        out.push(`    -webkit-backdrop-filter: blur(${scaled}px) saturate(${cell(variant, th).saturation});`);
        out.push(`    backdrop-filter: blur(${scaled}px) saturate(${cell(variant, th).saturation});`);
        out.push('  }');
      }
    }
  }
  out.push('  /* identity has no backdrop filter (MAT-038) */');
  out.push('');
  // content materials: [data-ag-content] on layer=content surfaces (AG_ATTRIBUTES)
  for (const content of Object.keys(spec.content ?? {})) {
    const cells = spec.content[content];
    if (!cells) continue;
    for (const th of THICKNESS) {
      const c = cells[th];
      out.push(`  [data-ag-content="content-${content}"][data-ag-thickness="${th}"] {`);
      out.push(`    --_ag-mat-tint-alpha: ${c.alpha};`);
      out.push(`    --_ag-surface-alpha: ${c.alpha};`);
      out.push('  }');
    }
  }
  out.push('');
  out.push('  /* disabled: fill alpha scaled by --ag-state-disabled-alpha via --_ag-surface-alpha; no host opacity: (MAT-033) */');
  for (const variant of VARIANTS) {
    for (const th of THICKNESS) {
      out.push(`  [data-ag-variant="${variant}"][data-ag-thickness="${th}"][data-ag-state~="disabled"] {`);
      out.push('    --_ag-alpha: calc(var(--_ag-surface-alpha) * var(--ag-state-disabled-alpha));');
      out.push('  }');
    }
  }
  out.push('}', '');
  return out.join('\n');
}

/** floors.css — OS floors + --_ag-tint-floor per [transparency][thickness][backdrop] (MAT-048). */
export function buildFloors(records, resolved, matrix = null) {
  const spec = materialSpec(records, resolved);
  const floor = (t) => get(records, resolved, `contrast.matrix.floors.${t}`);
  const scrim = spec.scrim.clear;
  const fallback = spec.fallbackFill?.alpha ?? 0.98;
  const out = [
    '/* @generated by scripts/tokens/build.mjs (floors). Do not edit. */',
    '@layer ag.compat, ag.reset, ag.tokens, ag.material, ag.components, ag.a11y;',
    '',
    '@layer ag.material {',
    '  /* --_ag-tint-floor: max solved floor across presets, schemes and variants (REQ-MAT-33 key). */',
  ];
  // matrix may be passed in by build.mjs after solving; otherwise emit authored floors
  const solved = matrix?.tintFloors ?? null;
  for (const tr of ['glass', 'tinted', 'solid']) {
    for (const th of THICKNESS) {
      for (const bd of ['light', 'dark', 'media']) {
        const v = solved?.[tr]?.[th]?.[bd] ?? floor(th);
        out.push(`  [data-ag-transparency="${tr}"] [data-ag-thickness="${th}"][data-ag-backdrop="${bd}"],`);
        out.push(`  [data-ag-transparency="${tr}"][data-ag-thickness="${th}"][data-ag-backdrop="${bd}"] {`);
        out.push(`    --_ag-tint-floor: ${Math.round(v * 1000) / 1000};`);
        out.push('  }');
      }
    }
  }
  for (const th of THICKNESS) {
    for (const bd of ['light', 'dark', 'media']) {
      // contrast=more must never go below the tinted floor row (MAT-035 contract).
      const v = Math.max(solved?.more?.[th]?.[bd] ?? floor(th), solved?.tinted?.[th]?.[bd] ?? 0);
      out.push(`  [data-ag-contrast="more"][data-ag-thickness="${th}"][data-ag-backdrop="${bd}"],`);
      out.push(`  [data-ag-contrast="more"] [data-ag-thickness="${th}"][data-ag-backdrop="${bd}"] {`);
      out.push(`    --_ag-tint-floor: ${Math.round(v * 1000) / 1000};`);
      out.push('  }');
    }
  }
  out.push('}', '', '@layer ag.a11y {');
  for (const th of THICKNESS) {
    for (const variant of VARIANTS) {
      out.push(`  [data-ag-variant="${variant}"][data-ag-thickness="${th}"] {`);
      out.push(`    --_ag-floor-alpha: ${floor(th)};`);
      out.push('  }');
    }
  }
  out.push(
    '',
    '  /* Opaque fallback: forced-colors flattens the glass (blur contributes nothing);',
    '     transparency=solid raises fills to the authored floors via --_ag-tint-floor above. */',
    '  @media (forced-colors: active) {',
    '    [data-ag-variant] {',
    '      --ag-glass-opacity: 1;',
    '      --_ag-mat-blur: 0px;',
    `      --_ag-scrim-clear: ${scrim};`,
    '    }',
    '  }',
    '',
    `  /* No backdrop-filter support: opaque fill at fallbackFill.alpha ${fallback}. */`,
    '  @supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {',
    '    [data-ag-variant] {',
    `      --_ag-alpha: ${fallback};`,
    '    }',
    '  }',
    '}',
    '',
  );
  return out.join('\n');
}

/** properties.css — @property registrations (MAT-027). Unlayered, <= 16 entries. */
export function buildProperties() {
  const props = [
    ['--ag-light-angle', '<angle>', 'true', '300deg'],
    ['--ag-specular', '<number>', 'false', '0.5'],
    ['--ag-glass-opacity', '<number>', 'true', '0'],
    ['--_ag-optics', '<number>', 'false', '1'],
    ['--_ag-press', '<number>', 'false', '0'],
    ['--_ag-refraction-scale', '<number>', 'false', '1'],
    ['--_ag-mat-blur', '<length>', 'false', '0px'],
    ['--_ag-mat-saturation', '<number>', 'false', '1'],
    ['--_ag-mat-tint-alpha', '<number>', 'false', '0'],
    ['--_ag-floor-alpha', '<number>', 'false', '0'],
    ['--_ag-tint-floor', '<number>', 'false', '0'],
    ['--_ag-scrim-clear', '<number>', 'false', '0.35'],
    ['--_ag-surface-alpha', '<number>', 'false', '1'],
    ['--_ag-alpha', '<number>', 'false', '1'],
    ['--_ag-density', '<number>', 'false', '1'],
  ];
  if (props.length > 16) throw new Error('properties.css would exceed 16 @property rules');
  const out = ['/* @generated by scripts/tokens/build.mjs (@property). Do not edit. Unlayered by contract. */'];
  for (const [name, syntax, inherits, initial] of props) {
    out.push(`@property ${name} {`, `  syntax: '${syntax}';`, `  inherits: ${inherits};`, `  initial-value: ${initial};`, '}');
  }
  return out.join('\n') + '\n';
}
