/* fragments/codemods/cmp.ts — CMP owns this file on both branches (§3.4).
   CMP-322/332/343: mapping data + fixture dir list for DX's engine (DX-041/042).
   packages/cli is absent on this branch — fixtures live here, never under packages/cli. */
import type { CodemodMappingFragment } from '../../src/contracts/fragments';

export default {
  renames: [
    { from: 'GlassButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'EnhancedGlassButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'RippleButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassMagneticButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'MagneticButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassLinkButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'ToggleButton', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassFab', fromEntry: '.', to: 'IconButton', toEntry: '.' },
    { from: 'GlassIconButton', fromEntry: '.', to: 'IconButton', toEntry: '.' },
    { from: 'LiquidGlassControlGroup', fromEntry: '.', to: 'ButtonGroup', toEntry: '.' },
    { from: 'GlassToolbar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'LiquidGlassToolbar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'GlassCommandBar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'GlassActionBar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'LiquidGlassMapControls', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'ToggleButtonGroup', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassToggle', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassSegmentedControl', fromEntry: '.', to: 'SegmentedControl', toEntry: '.' },
    { from: 'LiquidGlassSegmentedControl', fromEntry: '.', to: 'SegmentedControl', toEntry: '.' },
    { from: 'GlassSwitch', fromEntry: '.', to: 'Switch', toEntry: '.' },
    { from: 'GlassSlider', fromEntry: '.', to: 'Slider', toEntry: '.' },
    { from: 'GlassCheckbox', fromEntry: '.', to: 'Checkbox', toEntry: '.' },
    { from: 'GlassCheckboxGroup', fromEntry: '.', to: 'CheckboxGroup', toEntry: '.' },
    { from: 'GlassRadioGroup', fromEntry: '.', to: 'RadioGroup', toEntry: '.' },
    { from: 'GlassInput', fromEntry: '.', to: 'TextField', toEntry: '.' },
    { from: 'GlassTextarea', fromEntry: '.', to: 'TextField', toEntry: '.' },
    { from: 'GlassFieldGroup', fromEntry: '.', to: 'Fieldset', toEntry: '.' },
    { from: 'GlassValidationMessage', fromEntry: '.', to: 'Field.Error', toEntry: '.' },
    { from: 'GlassFormField', fromEntry: '.', to: 'Field', toEntry: '.' },
    { from: 'LiquidGlassSearchField', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSearchField', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSearchInterface', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassIntelligentSearch', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSelect', fromEntry: '.', to: 'Select', toEntry: '.' },
    { from: 'GlassSelectCompound', fromEntry: '.', to: 'Select', toEntry: '.' },
    { from: 'GlassCombobox', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassMultiSelect', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassTagInput', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassMentionList', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'LiquidGlassButtonStyle', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassModal', fromEntry: '.', to: 'Dialog', toEntry: '.' },
    { from: 'GlassDialog', fromEntry: '.', to: 'Dialog', toEntry: '.' },
    { from: 'GlassDrawer', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassBottomSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassActionSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'LiquidGlassAdaptiveSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassPopover', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassHoverCard', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassTooltip', fromEntry: '.', to: 'Tooltip', toEntry: '.' },
    { from: 'Positioner', fromEntry: '.', to: 'Popover.Positioner', toEntry: '.' },
    { from: 'GlassPositioner', fromEntry: '.', to: 'Popover.Positioner', toEntry: '.' },
    { from: 'GlassDropdownMenu', fromEntry: '.', to: 'Menu', toEntry: '.' },
    { from: 'GlassContextMenu', fromEntry: '.', to: 'ContextMenu', toEntry: '.' },
    { from: 'GlassMenubar', fromEntry: '.', to: 'Menubar', toEntry: '.' },
    { from: 'LiquidGlassPopoverMenu', fromEntry: '.', to: 'Menu', toEntry: '.' },
    { from: 'GlassToast', fromEntry: '.', to: 'useToast', toEntry: '.' },
    { from: 'GlassToastProvider', fromEntry: '.', to: 'Toast.Provider', toEntry: '.' },
    { from: 'GlassToastViewport', fromEntry: '.', to: 'Toast.Viewport', toEntry: '.' },
    { from: 'GlassNotificationCenter', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassNotificationProvider', fromEntry: '.', to: 'Toast.Provider', toEntry: '.' },
    { from: 'useNotifications', fromEntry: '.', to: 'useToast', toEntry: '.' },
  ],
  props: [
    { component: 'GlassButton', from: 'variant', to: 'variant', values: { primary: 'prominent', secondary: 'default', ghost: 'subtle', danger: 'intent:danger', destructive: 'intent:danger', error: 'intent:danger' } },
    { component: 'GlassButton', from: 'size', to: 'size', values: { xs: 'sm', xl: 'lg' } },
    { component: 'GlassButton', from: 'leftIcon', to: 'startIcon' },
    { component: 'GlassButton', from: 'rightIcon', to: 'endIcon' },
    { component: 'GlassButton', from: 'material', to: null, todo: 'material=\'liquid\' -> variant=\'prominent\'; other values drop' },
    { component: 'GlassIconButton', from: 'label', to: 'aria-label' },
    { component: 'ToggleButton', from: 'selected', to: 'pressed' },
    { component: 'ToggleButton', from: 'onChange', to: 'onPressedChange' },
    { component: 'GlassToggle', from: 'checked', to: 'value', todo: 'wrap in ToggleGroup value=[\'on\']' },
    { component: 'GlassSwitch', from: 'onChange', to: 'onCheckedChange', todo: 'e.target.checked -> checked argument' },
    { component: 'GlassCheckbox', from: 'onChange', to: 'onCheckedChange', todo: 'e.target.checked -> checked argument' },
    { component: 'GlassSlider', from: 'onAfterChange', to: 'onValueCommitted' },
    { component: 'GlassInput', from: 'helperText', to: 'description' },
    { component: 'GlassInput', from: 'errorText', to: 'error' },
    { component: 'GlassInput', from: 'errorMessage', to: 'error' },
    { component: 'GlassInput', from: 'leftIcon', to: 'startAdornment' },
    { component: 'GlassInput', from: 'rightIcon', to: 'endAdornment' },
    { component: 'GlassTextarea', from: 'rows', to: 'rows' },
    { component: 'GlassSelect', from: 'options', to: 'items' },
    { component: 'GlassSelect', from: 'searchable', to: null, todo: 'use Combobox for searchable pickers' },
    { component: 'GlassCombobox', from: 'onInputChange', to: 'onInputValueChange' },
    { component: 'GlassCombobox', from: 'options', to: 'items' },
    { component: 'GlassRadioGroup', from: 'direction', to: 'orientation', values: { horizontal: 'horizontal', vertical: 'vertical' } },
    { component: 'GlassModal', from: 'onClose', to: 'onOpenChange', todo: 'onClose() -> (open)=>{ if(!open) onClose() }' },
    { component: 'GlassModal', from: 'closeOnBackdropClick', to: 'dismissible' },
    { component: 'GlassModal', from: 'closeOnOverlayClick', to: 'dismissible' },
    { component: 'GlassModal', from: 'closeOnEscape', to: null, todo: 'false -> filter reason \'escape-key\' in onOpenChange' },
    { component: 'GlassModal', from: 'size', to: 'size', values: { small: 'sm', medium: 'md', large: 'lg', fullscreen: 'full' } },
    { component: 'GlassModal', from: 'variant', to: null, values: { drawer: 'sheet-side:bottom', sheet: 'sheet-side:bottom', bottom: 'sheet-side:bottom', fullscreen: 'size:full' } },
    { component: 'GlassModal', from: 'role', to: null, values: { alertdialog: 'component:AlertDialog' } },
    { component: 'GlassModal', from: 'isContained', to: null, todo: 'compose with Surface; set data-ag-transparency' },
    { component: 'GlassModal', from: 'title', to: null, todo: 'move into Dialog.Title' },
    { component: 'GlassModal', from: 'description', to: null, todo: 'move into Dialog.Description' },
    { component: 'GlassModal', from: 'footer', to: null, todo: 'move into Dialog.Actions/Close parts' },
    { component: 'GlassDialog', from: 'confirmText', to: null, todo: 'AlertDialog.Close with data-ag-intent="danger"' },
    { component: 'GlassDialog', from: 'cancelText', to: null, todo: 'AlertDialog.Close' },
    { component: 'GlassDrawer', from: 'position', to: 'side', values: { left: 'end', right: 'start' } },
    { component: 'GlassDrawer', from: 'placement', to: 'side', values: { left: 'end', right: 'start' } },
    { component: 'GlassDrawer', from: 'snap', to: 'detents' },
    { component: 'GlassBottomSheet', from: 'height', to: 'detents', todo: 'numeric height -> single detent px value' },
    { component: 'GlassActionSheet', from: 'actions', to: null, todo: 'actions[] -> <Sheet.Action> children; preset="action"' },
    { component: 'GlassActionSheet', from: 'cancelText', to: null, todo: '<Sheet.Close> child' },
    { component: 'GlassPopover', from: 'placement', to: null, values: { top: 'side:top', bottom: 'side:bottom', left: 'side:left', right: 'side:right', 'top-start': 'side:top align:start', 'bottom-start': 'side:bottom align:start' } },
    { component: 'GlassPopover', from: 'trigger', to: null, values: { hover: 'openOnHover:true', click: 'default' } },
    { component: 'GlassHoverCard', from: 'openDelay', to: 'delay' },
    { component: 'GlassTooltip', from: 'content', to: null, todo: 'move into Tooltip.Popup children' },
    { component: 'GlassTooltip', from: 'position', to: null, values: { top: 'side:top', bottom: 'side:bottom', left: 'side:left', right: 'side:right' } },
    { component: 'GlassDropdownMenu.Content', from: 'sideOffset', to: 'sideOffset' },
    { component: 'GlassDropdownMenu.Item', from: 'onSelect', to: 'onSelect' },
    { component: 'GlassContextMenu.Item', from: 'onClick', to: 'onSelect' },
    { component: 'GlassMenubar', from: 'menus', to: null, todo: 'menus[] -> <Menubar><Menu.Root> children' },
    { component: 'GlassToast', from: 'type', to: 'intent', values: { error: 'danger', danger: 'danger', success: 'success', info: 'info', warning: 'warning' } },
    { component: 'GlassToast', from: 'duration', to: 'timeout' },
    { component: 'GlassToast', from: 'onClose', to: null, todo: 'component mount -> useToast().add(); close via id' },
    { component: 'GlassToast', from: 'onDismiss', to: null, todo: '-> useToast().close(id)' },
    { component: 'GlassToastProvider', from: 'position', to: 'position', values: { top: 'top-center', bottom: 'bottom-center' } },
    { component: 'GlassToastProvider', from: 'duration', to: 'timeout' },
    { component: 'GlassNotificationCenter', from: 'notifications', to: null, todo: 'list content -> useToast history or local state inside Popover' },
  ],
  removed: [
    { symbol: 'GlassAchievementNotifications', entry: '.', reason: 'achievement stream removed; feed through useToast().add', doc: '#dep-c0130' },
    { symbol: 'GlassTransitions.GlassModal', entry: '.', reason: 'transitions built into Dialog', doc: '#dep-c0131' },
    { symbol: 'MobileGlassBottomSheet', entry: '.', reason: 'use Sheet side=\'bottom\'', doc: '#dep-c0132' },
  ],
  fixtures: [
    'canonical-names/fnd-enhanced-glass-button',
    'canonical-names/fnd-glass-action-bar',
    'canonical-names/fnd-glass-action-sheet',
    'canonical-names/fnd-glass-bottom-sheet',
    'canonical-names/fnd-glass-button',
    'canonical-names/fnd-glass-checkbox',
    'canonical-names/fnd-glass-checkbox-group',
    'canonical-names/fnd-glass-combobox',
    'canonical-names/fnd-glass-command-bar',
    'canonical-names/fnd-glass-context-menu',
    'canonical-names/fnd-glass-dialog',
    'canonical-names/fnd-glass-drawer',
    'canonical-names/fnd-glass-dropdown-menu',
    'canonical-names/fnd-glass-fab',
    'canonical-names/fnd-glass-field-group',
    'canonical-names/fnd-glass-form-field',
    'canonical-names/fnd-glass-hover-card',
    'canonical-names/fnd-glass-icon-button',
    'canonical-names/fnd-glass-input',
    'canonical-names/fnd-glass-intelligent-search',
    'canonical-names/fnd-glass-link-button',
    'canonical-names/fnd-glass-magnetic-button',
    'canonical-names/fnd-glass-mention-list',
    'canonical-names/fnd-glass-menubar',
    'canonical-names/fnd-glass-modal',
    'canonical-names/fnd-glass-multi-select',
    'canonical-names/fnd-glass-notification-center',
    'canonical-names/fnd-glass-notification-provider',
    'canonical-names/fnd-glass-popover',
    'canonical-names/fnd-glass-positioner',
    'canonical-names/fnd-glass-radio-group',
    'canonical-names/fnd-glass-search-field',
    'canonical-names/fnd-glass-search-interface',
    'canonical-names/fnd-glass-segmented-control',
    'canonical-names/fnd-glass-select',
    'canonical-names/fnd-glass-select-compound',
    'canonical-names/fnd-glass-slider',
    'canonical-names/fnd-glass-stepper-ambiguous',
    'canonical-names/fnd-glass-switch',
    'canonical-names/fnd-glass-tag-input',
    'canonical-names/fnd-glass-textarea',
    'canonical-names/fnd-glass-toast',
    'canonical-names/fnd-glass-toast-provider',
    'canonical-names/fnd-glass-toast-viewport',
    'canonical-names/fnd-glass-toggle',
    'canonical-names/fnd-glass-toolbar',
    'canonical-names/fnd-glass-tooltip',
    'canonical-names/fnd-glass-validation-message',
    'canonical-names/fnd-glassstepper-negative',
    'canonical-names/fnd-liquid-glass-adaptive-sheet',
    'canonical-names/fnd-liquid-glass-button-style',
    'canonical-names/fnd-liquid-glass-control-group',
    'canonical-names/fnd-liquid-glass-map-controls',
    'canonical-names/fnd-liquid-glass-popover-menu',
    'canonical-names/fnd-liquid-glass-search-field',
    'canonical-names/fnd-liquid-glass-segmented-control',
    'canonical-names/fnd-liquid-glass-toolbar',
    'canonical-names/fnd-magnetic-button',
    'canonical-names/fnd-positioner',
    'canonical-names/fnd-ripple-button',
    'canonical-names/fnd-toggle-button',
    'canonical-names/fnd-toggle-button-group',
    'canonical-names/fnd-use-notifications',
    'canonical-names/fnd-use-toast',
    'imports-subpaths/fnd-button-deep-import',
    'imports-subpaths/overlays-subpath',
    'prop-grammar/fnd-accordion-role',
    'prop-grammar/fnd-button-checked-event',
    'prop-grammar/fnd-glassbutton-variant-gradient',
    'prop-grammar/fnd-glassmodal-props',
    'prop-grammar/overlays-backdrop-click',
    'prop-grammar/overlays-escape-all',
    'prop-grammar/overlays-on-close-semantics',
    'prop-grammar/overlays-placement',
    'providers/overlays-toast-provider',
    'removed/fnd-glass-achievement-notifications',
    'removed/fnd-glass-transitions-modal',
    'removed/fnd-mobile-glass-bottom-sheet',
  ],
} satisfies CodemodMappingFragment;
