/* fragments/codemods/cmp.ts — CMP owns this file on both branches (§3.4).
   CMP-322/332/343: mapping data + fixture dir list for DX's engine (DX-041/042).
   packages/cli is absent on this branch — fixtures live here, never under packages/cli. */
import type { CodemodMappingFragment } from '../../src/contracts/fragments';

export default {
  renames: [
    { from: 'GlassButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'EnhancedGlassButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'RippleButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassMagneticButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'MagneticButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassLinkButton', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'ToggleButton', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassFab', fromEntry: '.', to: 'IconButton', toEntry: '.' },
    { from: 'GlassIconButton', fromEntry: '.', to: 'IconButton', toEntry: '.' },
    { from: 'LiquidGlassControlGroup', fromEntry: '.', to: 'ButtonGroup', toEntry: '.' },
    { from: 'GlassToolbar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'LiquidGlassToolbar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'GlassCommandBar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'GlassActionBar', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'LiquidGlassMapControls', fromEntry: '.', to: 'Toolbar', toEntry: '.' },
    { from: 'ToggleButtonGroup', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassToggle', fromEntry: '.', to: 'ToggleGroup', toEntry: '.' },
    { from: 'GlassSegmentedControl', fromEntry: '.', to: 'SegmentedControl', toEntry: '.' },
    { from: 'LiquidGlassSegmentedControl', fromEntry: '.', to: 'SegmentedControl', toEntry: '.' },
    { from: 'GlassSwitch', fromEntry: '.', to: 'Switch', toEntry: '.' },
    { from: 'GlassSlider', fromEntry: '.', to: 'Slider', toEntry: '.' },
    { from: 'GlassCheckbox', fromEntry: '.', to: 'Checkbox', toEntry: '.' },
    { from: 'GlassCheckboxGroup', fromEntry: '.', to: 'CheckboxGroup', toEntry: '.' },
    { from: 'GlassRadioGroup', fromEntry: '.', to: 'RadioGroup', toEntry: '.' },
    { from: 'GlassInput', fromEntry: '.', to: 'TextField', toEntry: '.' },
    { from: 'GlassTextarea', fromEntry: '.', to: 'TextField', toEntry: '.' },
    { from: 'GlassFieldGroup', fromEntry: '.', to: 'Fieldset', toEntry: '.' },
    { from: 'GlassValidationMessage', fromEntry: '.', to: 'Field.Error', toEntry: '.' },
    { from: 'GlassFormField', fromEntry: '.', to: 'Field', toEntry: '.' },
    { from: 'LiquidGlassSearchField', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSearchField', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSearchInterface', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassIntelligentSearch', fromEntry: '.', to: 'SearchField', toEntry: '.' },
    { from: 'GlassSelect', fromEntry: '.', to: 'Select', toEntry: '.' },
    { from: 'GlassSelectCompound', fromEntry: '.', to: 'Select', toEntry: '.' },
    { from: 'GlassCombobox', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassMultiSelect', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassTagInput', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'GlassMentionList', fromEntry: '.', to: 'Combobox', toEntry: '.' },
    { from: 'LiquidGlassButtonStyle', fromEntry: '.', to: 'Button', toEntry: '.' },
    { from: 'GlassModal', fromEntry: '.', to: 'Dialog', toEntry: '.' },
    { from: 'GlassDialog', fromEntry: '.', to: 'Dialog', toEntry: '.' },
    { from: 'GlassDrawer', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassBottomSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassActionSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'LiquidGlassAdaptiveSheet', fromEntry: '.', to: 'Sheet', toEntry: '.' },
    { from: 'GlassPopover', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassHoverCard', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassTooltip', fromEntry: '.', to: 'Tooltip', toEntry: '.' },
    { from: 'Positioner', fromEntry: '.', to: 'Popover.Positioner', toEntry: '.' },
    { from: 'GlassPositioner', fromEntry: '.', to: 'Popover.Positioner', toEntry: '.' },
    { from: 'GlassDropdownMenu', fromEntry: '.', to: 'Menu', toEntry: '.' },
    { from: 'GlassContextMenu', fromEntry: '.', to: 'ContextMenu', toEntry: '.' },
    { from: 'GlassMenubar', fromEntry: '.', to: 'Menubar', toEntry: '.' },
    { from: 'LiquidGlassPopoverMenu', fromEntry: '.', to: 'Menu', toEntry: '.' },
    { from: 'GlassToast', fromEntry: '.', to: 'useToast', toEntry: '.' },
    { from: 'GlassToastProvider', fromEntry: '.', to: 'Toast.Provider', toEntry: '.' },
    { from: 'GlassToastViewport', fromEntry: '.', to: 'Toast.Viewport', toEntry: '.' },
    { from: 'GlassNotificationCenter', fromEntry: '.', to: 'Popover', toEntry: '.' },
    { from: 'GlassNotificationProvider', fromEntry: '.', to: 'Toast.Provider', toEntry: '.' },
    { from: 'useNotifications', fromEntry: '.', to: 'useToast', toEntry: '.' },
    // Path-scoped rows (REQ-CMP-133): the same 4.x name exports from more than
    // one entry point, so the engine must match on (fromEntry, from).
    { from: 'GlassStepper', fromEntry: '.', to: 'Steps', toEntry: '.' },
    { from: 'GlassToast', fromEntry: 'aura-glass/feedback', to: 'Toast', toEntry: '.' },
    { from: 'GlassToast', fromEntry: 'aura-glass/root', to: 'useToast', toEntry: '.' },
    // Root `Button` in 4.x is re-exported as-is in 5.0 (name is stable).
    { from: 'Button', fromEntry: '.', to: 'Button', toEntry: '.', compatOnly: true },
    // 4.x `useToast` keeps its name in 5.0; the compat hook maps the 4.x return shape.
    { from: 'useToast', fromEntry: '.', to: 'useToast', toEntry: '.', compatOnly: true },
    // <generated renames — do not hand-edit>
    { from: 'ChartTooltip',fromEntry: '.',to: 'Tooltip',toEntry: '.' },
    { from: 'CircularProgress',fromEntry: '.',to: 'Progress',toEntry: '.' },
    { from: 'DisplayText',fromEntry: '.',to: 'Heading',toEntry: '.' },
    { from: 'FocusTrap',fromEntry: '.',to: 'FocusScope',toEntry: '.' },
    { from: 'GlassAccordion',fromEntry: '.',to: 'Accordion',toEntry: '.' },
    { from: 'GlassAlert',fromEntry: '.',to: 'Alert',toEntry: '.' },
    { from: 'GlassAvatar',fromEntry: '.',to: 'Avatar',toEntry: '.' },
    { from: 'GlassAvatarGroup',fromEntry: '.',to: 'AvatarGroup',toEntry: '.' },
    { from: 'GlassBadge',fromEntry: '.',to: 'Badge',toEntry: '.' },
    { from: 'GlassButtonGroup',fromEntry: '.',to: 'ButtonGroup',toEntry: '.' },
    { from: 'GlassCard',fromEntry: '.',to: 'Card',toEntry: '.' },
    { from: 'GlassChip',fromEntry: '.',to: 'Chip',toEntry: '.' },
    { from: 'GlassCoachmarks',fromEntry: '.',to: 'Tour',toEntry: '.' },
    { from: 'GlassColorPicker',fromEntry: '.',to: 'ColorPicker',toEntry: '.' },
    { from: 'GlassColorWheel',fromEntry: '.',to: 'ColorPicker',toEntry: '.' },
    { from: 'GlassContainer',fromEntry: '.',to: 'Container',toEntry: '.' },
    { from: 'GlassDescriptionList',fromEntry: '.',to: 'DescriptionList',toEntry: '.' },
    { from: 'GlassDismissableLayer',fromEntry: '.',to: 'DismissableLayer',toEntry: '.' },
    { from: 'GlassDivider',fromEntry: '.',to: 'Separator',toEntry: '.' },
    { from: 'GlassDropdown',fromEntry: '.',to: 'Menu',toEntry: '.' },
    { from: 'GlassEmptyState',fromEntry: '.',to: 'EmptyState',toEntry: '.' },
    { from: 'GlassErrorState',fromEntry: '.',to: 'ErrorState',toEntry: '.' },
    { from: 'GlassField',fromEntry: '.',to: 'Field',toEntry: '.' },
    { from: 'GlassFileUpload',fromEntry: '.',to: 'FileUpload',toEntry: '.' },
    { from: 'GlassFocusScope',fromEntry: '.',to: 'FocusScope',toEntry: '.' },
    { from: 'GlassForm',fromEntry: '.',to: 'Form',toEntry: '.' },
    { from: 'GlassGradientPicker',fromEntry: '.',to: 'ColorPicker',toEntry: '.' },
    { from: 'GlassGrid',fromEntry: '.',to: 'Grid',toEntry: '.' },
    { from: 'GlassHeading',fromEntry: '.',to: 'Heading',toEntry: '.' },
    { from: 'GlassIcon',fromEntry: '.',to: 'Icon',toEntry: '.' },
    { from: 'GlassImageList',fromEntry: '.',to: 'ImageList',toEntry: '.' },
    { from: 'GlassInlineEdit',fromEntry: '.',to: 'InlineEdit',toEntry: '.' },
    { from: 'GlassKeyValueEditor',fromEntry: '.',to: 'KeyValueEditor',toEntry: '.' },
    { from: 'GlassLabel',fromEntry: '.',to: 'Label',toEntry: '.' },
    { from: 'GlassLabelPrimitive',fromEntry: '.',to: 'Label',toEntry: '.' },
    { from: 'GlassLink',fromEntry: '.',to: 'Link',toEntry: '.' },
    { from: 'GlassLoadingSkeleton',fromEntry: '.',to: 'Skeleton',toEntry: '.' },
    { from: 'GlassLoadingState',fromEntry: '.',to: 'LoadingState',toEntry: '.' },
    { from: 'GlassMasonry',fromEntry: '.',to: 'Grid',toEntry: '.' },
    { from: 'GlassMenu',fromEntry: '.',to: 'Menu',toEntry: '.' },
    { from: 'GlassMobileNav',fromEntry: '.',to: 'Sheet',toEntry: '.' },
    { from: 'GlassNotificationItem',fromEntry: '.',to: 'Toast',toEntry: '.' },
    { from: 'GlassNumberInput',fromEntry: '.',to: 'NumberField',toEntry: '.' },
    { from: 'GlassPortal',fromEntry: '.',to: 'Portal',toEntry: '.' },
    { from: 'GlassProgress',fromEntry: '.',to: 'Progress',toEntry: '.' },
    { from: 'GlassRating',fromEntry: '.',to: 'Rating',toEntry: '.' },
    { from: 'GlassScrollArea',fromEntry: '.',to: 'ScrollArea',toEntry: '.' },
    { from: 'GlassSearchInput',fromEntry: '.',to: 'SearchField',toEntry: '.' },
    { from: 'GlassSeparator',fromEntry: '.',to: 'Separator',toEntry: '.' },
    { from: 'GlassSkeleton',fromEntry: '.',to: 'Skeleton',toEntry: '.' },
    { from: 'GlassSlot',fromEntry: '.',to: 'Slot',toEntry: '.' },
    { from: 'GlassSnackbar',fromEntry: '.',to: 'Toast',toEntry: '.' },
    { from: 'GlassSpotlight',fromEntry: '.',to: 'Tour',toEntry: '.' },
    { from: 'GlassStack',fromEntry: '.',to: 'Stack',toEntry: '.' },
    { from: 'GlassText',fromEntry: '.',to: 'Text',toEntry: '.' },
    { from: 'GlassToggleGroup',fromEntry: '.',to: 'ToggleGroup',toEntry: '.' },
    { from: 'GlassWorkspacePanel',fromEntry: '.',to: 'Card',toEntry: '.' },
    { from: 'GlowingCard',fromEntry: '.',to: 'Card',toEntry: '.' },
    { from: 'LabelRoot',fromEntry: '.',to: 'Label',toEntry: '.' },
    { from: 'LiquidGlassBadgeCluster',fromEntry: '.',to: 'Badge',toEntry: '.' },
    { from: 'MobileGlassBottomSheet',fromEntry: '.',to: 'Sheet',toEntry: '.' },
    { from: 'RovingFocusGroup',fromEntry: '.',to: 'FocusScope',toEntry: '.' },
    { from: 'ScreenReader',fromEntry: '.',to: 'VisuallyHidden',toEntry: '.' },
    { from: 'ScreenReaderText',fromEntry: '.',to: 'VisuallyHidden',toEntry: '.' },
    { from: 'toast',fromEntry: '.',to: 'Toast',toEntry: '.' },
    { from: 'Typography',fromEntry: '.',to: 'Text',toEntry: '.' },
    { from: 'WidgetGlass',fromEntry: '.',to: 'Card',toEntry: '.' },
    // </generated>
  ],
  props: [
    // <generated by scripts/cmp/gen-fragments.mjs — do not hand-edit>
    { component: 'GlassModal',from: 'role',to: 'component',values: { alertdialog: 'AlertDialog' } },
    { component: 'GlassModal',from: 'open',to: 'open' },
    { component: 'GlassModal',from: 'onClose',to: 'onOpenChange' },
    { component: 'GlassModal',from: 'confirmText',to: 'AlertDialog.Action' },
    { component: 'GlassModal',from: 'cancelText',to: 'AlertDialog.Cancel' },
    { component: 'GlassModal',from: 'destructive',to: 'intent',values: { true: 'danger' } },
    { component: 'GlassDialog',from: 'role',to: 'component',values: { alertdialog: 'AlertDialog' } },
    { component: 'GlassDialog',from: 'confirmText',to: 'AlertDialog.Action' },
    { component: 'GlassDialog',from: 'cancelText',to: 'AlertDialog.Cancel' },
    { component: 'GlassDialog',from: 'destructive',to: 'intent',values: { true: 'danger' } },
    { component: 'GlassButtonGroup',from: 'orientation',to: 'orientation' },
    { component: 'GlassButtonGroup',from: 'attached',to: 'attached' },
    { component: 'GlassButton',from: 'variant',to: 'prominent',values: { primary: 'true' } },
    { component: 'GlassButton',from: 'variant:secondary',to: 'variant:regular' },
    { component: 'GlassButton',from: 'variant:default',to: 'variant:regular' },
    { component: 'GlassButton',from: 'variant:outline',to: 'variant',values: { outline: 'regular' } },
    { component: 'GlassButton',from: 'variant:ghost',to: 'variant',values: { ghost: 'identity' } },
    { component: 'GlassButton',from: 'variant:tertiary',to: 'variant',values: { tertiary: 'identity' } },
    { component: 'GlassButton',from: 'variant:link',to: 'variant',values: { link: 'identity' } },
    { component: 'GlassButton',from: 'variant:gradient',to: null },
    { component: 'GlassButton',from: 'variant:aurora',to: null },
    { component: 'GlassButton',from: 'variant:success',to: null },
    { component: 'GlassButton',from: 'variant:warning',to: null },
    { component: 'GlassButton',from: 'variant:danger',to: 'intent' },
    { component: 'GlassButton',from: 'variant:destructive',to: 'intent' },
    { component: 'GlassButton',from: 'variant:error',to: 'intent' },
    { component: 'GlassButton',from: 'size:xs',to: 'size',values: { xs: 'sm' } },
    { component: 'GlassButton',from: 'size:xl',to: 'size',values: { xl: 'lg' } },
    { component: 'GlassButton',from: 'asChild',to: 'render' },
    { component: 'GlassButton',from: 'leftIcon',to: 'startIcon' },
    { component: 'GlassButton',from: 'rightIcon',to: 'endIcon' },
    { component: 'GlassButton',from: 'material',to: null },
    { component: 'GlassButton',from: 'glassVariant',to: 'variant',values: { clear: 'clear' } },
    { component: 'GlassButton',from: 'onChange',to: 'onPressedChange' },
    { component: 'EnhancedGlassButton',from: 'variant',to: 'prominent' },
    { component: 'EnhancedGlassButton',from: 'leftIcon',to: 'startIcon' },
    { component: 'EnhancedGlassButton',from: 'rightIcon',to: 'endIcon' },
    { component: 'GlassMagneticButton',from: 'magnetic',to: null },
    { component: 'GlassMagneticButton',from: 'variant',to: 'prominent' },
    { component: 'GlassCheckbox',from: 'onChange',to: 'onCheckedChange' },
    { component: 'GlassCheckbox',from: 'label',to: 'children' },
    { component: 'GlassCheckbox',from: 'glassVariant',to: null },
    { component: 'GlassCheckbox',from: 'size:xl',to: 'size',values: { xl: 'lg' } },
    { component: 'GlassCheckboxGroup',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassCheckboxGroup',from: 'options',to: 'children' },
    { component: 'GlassCombobox',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassCombobox',from: 'onInputChange',to: 'onInputValueChange' },
    { component: 'GlassCombobox',from: 'options',to: 'items' },
    { component: 'GlassCombobox',from: 'glassVariant',to: null },
    { component: 'GlassMultiSelect',from: 'selected',to: 'value' },
    { component: 'GlassMultiSelect',from: 'onSelectionChange',to: 'onValueChange' },
    { component: 'GlassMultiSelect',from: 'options',to: 'items' },
    { component: 'GlassMultiSelect',from: 'searchable',to: 'multiple' },
    { component: 'GlassModal',from: 'title',to: 'Dialog.Title' },
    { component: 'GlassModal',from: 'description',to: 'Dialog.Description' },
    { component: 'GlassModal',from: 'footer',to: 'Dialog.Footer' },
    { component: 'GlassModal',from: 'size',to: 'size',values: { small: 'sm',medium: 'md',large: 'lg',fullscreen: 'full' } },
    { component: 'GlassModal',from: 'variant',to: 'component',values: { drawer: 'Sheet',fullscreen: 'Dialog size=full' } },
    { component: 'GlassModal',from: 'closeOnBackdropClick',to: 'dismissible' },
    { component: 'GlassModal',from: 'closeOnOverlayClick',to: 'dismissible' },
    { component: 'GlassModal',from: 'closeOnEscape',to: null },
    { component: 'GlassModal',from: 'backdropBlur',to: null },
    { component: 'GlassModal',from: 'material',to: null },
    { component: 'GlassModal',from: 'materialProps',to: null },
    { component: 'GlassModal',from: 'consciousness',to: null },
    { component: 'GlassModal',from: 'predictive',to: null },
    { component: 'GlassModal',from: 'adaptive',to: null },
    { component: 'GlassModal',from: 'eyeTracking',to: null },
    { component: 'GlassModal',from: 'trackAchievements',to: null },
    { component: 'GlassModal',from: 'animation',to: null },
    { component: 'GlassModal',from: 'compact',to: null },
    { component: 'GlassModal',from: 'isContained',to: null },
    { component: 'GlassDialog',from: 'open',to: 'open' },
    { component: 'GlassDialog',from: 'onClose',to: 'onOpenChange' },
    { component: 'GlassDialog',from: 'title',to: 'Dialog.Title' },
    { component: 'GlassDialog',from: 'description',to: 'Dialog.Description' },
    { component: 'GlassDialog',from: 'footer',to: 'Dialog.Footer' },
    { component: 'GlassDialog',from: 'size',to: 'size' },
    { component: 'GlassDialog',from: 'closeOnBackdropClick',to: 'dismissible' },
    { component: 'GlassDialog',from: 'backdropBlur',to: null },
    { component: 'GlassDialog',from: 'material',to: null },
    { component: 'GlassDialog',from: 'materialProps',to: null },
    { component: 'GlassDialog',from: 'animation',to: null },
    { component: 'GlassDialog',from: 'compact',to: null },
    { component: 'GlassField',from: 'label',to: 'children' },
    { component: 'GlassField',from: 'description',to: 'children' },
    { component: 'GlassField',from: 'error',to: 'invalid + <Field.Error>' },
    { component: 'GlassField',from: 'hint',to: 'children' },
    { component: 'GlassField',from: 'required',to: 'aria-required on the inner control' },
    { component: 'GlassFieldGroup',from: 'legend',to: 'legend' },
    { component: 'GlassFieldGroup',from: 'title',to: 'legend' },
    { component: 'GlassFieldGroup',from: 'description',to: 'children' },
    { component: 'GlassForm',from: 'onSubmit',to: 'onSubmit(values, eventDetails)' },
    { component: 'GlassForm',from: 'errors',to: 'errors' },
    { component: 'GlassIconButton',from: 'aria-label',to: 'label' },
    { component: 'GlassIconButton',from: 'children',to: 'icon' },
    { component: 'GlassIconButton',from: 'variant',to: 'prominent' },
    { component: 'GlassIconButton',from: 'size',to: 'size' },
    { component: 'GlassKeyValueEditor',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassKeyValueEditor',from: 'data-testid',to: 'data-ag-part hooks' },
    { component: 'GlassMenu',from: 'open',to: 'open' },
    { component: 'GlassMenu',from: 'onClose',to: 'onOpenChange' },
    { component: 'GlassMenu',from: 'items',to: 'Menu.Item children' },
    { component: 'GlassMenu',from: 'side',to: 'Positioner side' },
    { component: 'GlassDropdown',from: 'items',to: 'Menu.Item children' },
    { component: 'GlassDropdown',from: 'open',to: 'open' },
    { component: 'GlassContextMenu',from: 'items',to: 'ContextMenu.Item children' },
    { component: 'GlassMenubar',from: 'menus',to: 'Menubar>Menu.Root children' },
    { component: 'GlassNumberInput',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassNumberInput',from: 'formatter',to: 'format' },
    { component: 'GlassNumberInput',from: 'parser',to: 'locale/format' },
    { component: 'GlassPopover',from: 'open',to: 'open' },
    { component: 'GlassPopover',from: 'onClose',to: 'onOpenChange' },
    { component: 'GlassPopover',from: 'title',to: 'Popover.Title' },
    { component: 'GlassPopover',from: 'content',to: 'Popover.Popup children' },
    { component: 'GlassPopover',from: 'side',to: 'Positioner side' },
    { component: 'GlassPopover',from: 'align',to: 'Positioner align' },
    { component: 'GlassHoverCard',from: 'open',to: 'open' },
    { component: 'GlassHoverCard',from: 'trigger',to: 'Popover.Trigger openOnHover' },
    { component: 'GlassHoverCard',from: 'content',to: 'Popover.Popup children' },
    { component: 'GlassTooltip',from: 'content',to: 'Popover.Popup children' },
    { component: 'GlassRadioGroup',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassRadioGroup',from: 'options',to: 'children' },
    { component: 'GlassRadioGroup',from: 'direction',to: 'orientation' },
    { component: 'GlassRadioGroup',from: 'glassVariant',to: null },
    { component: 'GlassSearchInput',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassSearchInput',from: 'onSearch',to: 'onValueChange + Enter submit' },
    { component: 'GlassSearchInput',from: 'clearable',to: null },
    { component: 'GlassSegmentedControl',from: 'value',to: 'value' },
    { component: 'GlassSegmentedControl',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassSegmentedControl',from: 'options',to: null },
    { component: 'GlassSelect',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassSelect',from: 'options',to: 'items' },
    { component: 'GlassSelect',from: 'glassVariant',to: null },
    { component: 'GlassSelect',from: 'size:xl',to: 'size',values: { xl: 'lg' } },
    { component: 'GlassDropdown',from: 'onSelect',to: 'onValueChange' },
    { component: 'GlassDropdown',from: 'menu',to: 'children' },
    { component: 'GlassDrawer',from: 'position',to: 'side' },
    { component: 'GlassDrawer',from: 'placement',to: 'side' },
    { component: 'GlassDrawer',from: 'snap',to: 'detents' },
    { component: 'GlassDrawer',from: 'open',to: 'open' },
    { component: 'GlassDrawer',from: 'onClose',to: 'onOpenChange' },
    { component: 'GlassBottomSheet',from: 'snap',to: 'detents' },
    { component: 'GlassBottomSheet',from: 'height',to: 'detents' },
    { component: 'GlassActionSheet',from: 'actions',to: 'preset' },
    { component: 'GlassActionSheet',from: 'cancelText',to: 'Sheet.Close' },
    { component: 'LiquidGlassAdaptiveSheet',from: 'snap',to: 'detents' },
    { component: 'MobileGlassBottomSheet',from: 'snap',to: 'detents' },
    { component: 'GlassMobileNav',from: 'position',to: 'side' },
    { component: 'GlassSlider',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassSlider',from: 'onAfterChange',to: 'onValueCommitted' },
    { component: 'GlassSlider',from: 'glassVariant',to: null },
    { component: 'GlassSwitch',from: 'onChange',to: 'onCheckedChange' },
    { component: 'GlassSwitch',from: 'label',to: 'children' },
    { component: 'GlassSwitch',from: 'glassVariant',to: null },
    { component: 'GlassSwitch',from: 'size:xl',to: 'size',values: { xl: 'lg' } },
    { component: 'GlassInput',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassInput',from: 'leftIcon',to: 'startAdornment' },
    { component: 'GlassInput',from: 'rightIcon',to: 'endAdornment' },
    { component: 'GlassInput',from: 'icon',to: 'startAdornment' },
    { component: 'GlassInput',from: 'helperText',to: 'description' },
    { component: 'GlassInput',from: 'errorMessage',to: 'error' },
    { component: 'GlassInput',from: 'isInvalid',to: 'error (node) or invalid via Field.Root' },
    { component: 'GlassInput',from: 'fullWidth',to: null },
    { component: 'GlassInput',from: 'glassVariant',to: null },
    { component: 'GlassTextarea',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassTextarea',from: 'helperText',to: 'description' },
    { component: 'GlassTextarea',from: 'errorMessage',to: 'error' },
    { component: 'GlassToast',from: 'message',to: 'Toast.Description' },
    { component: 'GlassToast',from: 'type',to: 'intent' },
    { component: 'GlassToast',from: 'duration',to: 'timeout' },
    { component: 'GlassToast',from: 'onClose',to: 'useToast close' },
    { component: 'GlassSnackbar',from: 'message',to: 'Toast.Title' },
    { component: 'GlassSnackbar',from: 'action',to: 'Toast.Action' },
    { component: 'toast',from: 'toast()',to: 'useToast().add/success/error' },
    { component: 'toast',from: 'toast.promise',to: 'useToast().promise' },
    { component: 'GlassToggleGroup',from: 'value',to: 'value' },
    { component: 'GlassToggleGroup',from: 'onChange',to: 'onValueChange' },
    { component: 'GlassToggleGroup',from: 'multiple',to: 'multiple' },
    { component: 'GlassToolbar',from: 'orientation',to: 'orientation' },
    { component: 'GlassToolbar',from: 'items',to: null },
    { component: 'GlassTooltip',from: 'placement',to: 'Positioner side/align' },
    { component: 'GlassTooltip',from: 'delay',to: 'Provider delay' },
    { component: 'GlassIcon',from: 'name',to: 'name' },
    // </generated>
  ],
  removed: [
    { symbol: 'GlassAchievementNotifications', entry: '.', reason: 'achievement stream removed; feed through useToast().add', doc: '#dep-c0130' },
    { symbol: 'GlassTransitions.GlassModal', entry: '.', reason: 'transitions built into Dialog', doc: '#dep-c0131' },
    { symbol: 'MobileGlassBottomSheet', entry: '.', reason: 'use Sheet side=\'bottom\'', doc: '#dep-c0132' },
  ],
  fixtures: [
    'canonical-names/fnd-enhanced-glass-button',
    'canonical-names/fnd-glass-action-bar',
    'canonical-names/fnd-glass-action-sheet',
    'canonical-names/fnd-glass-bottom-sheet',
    'canonical-names/fnd-glass-button',
    'canonical-names/fnd-glass-checkbox',
    'canonical-names/fnd-glass-checkbox-group',
    'canonical-names/fnd-glass-combobox',
    'canonical-names/fnd-glass-command-bar',
    'canonical-names/fnd-glass-context-menu',
    'canonical-names/fnd-glass-dialog',
    'canonical-names/fnd-glass-drawer',
    'canonical-names/fnd-glass-dropdown-menu',
    'canonical-names/fnd-glass-fab',
    'canonical-names/fnd-glass-field-group',
    'canonical-names/fnd-glass-form-field',
    'canonical-names/fnd-glass-hover-card',
    'canonical-names/fnd-glass-icon-button',
    'canonical-names/fnd-glass-input',
    'canonical-names/fnd-glass-intelligent-search',
    'canonical-names/fnd-glass-link-button',
    'canonical-names/fnd-glass-magnetic-button',
    'canonical-names/fnd-glass-mention-list',
    'canonical-names/fnd-glass-menubar',
    'canonical-names/fnd-glass-modal',
    'canonical-names/fnd-glass-multi-select',
    'canonical-names/fnd-glass-notification-center',
    'canonical-names/fnd-glass-notification-provider',
    'canonical-names/fnd-glass-popover',
    'canonical-names/fnd-glass-positioner',
    'canonical-names/fnd-glass-radio-group',
    'canonical-names/fnd-glass-search-field',
    'canonical-names/fnd-glass-search-interface',
    'canonical-names/fnd-glass-segmented-control',
    'canonical-names/fnd-glass-select',
    'canonical-names/fnd-glass-select-compound',
    'canonical-names/fnd-glass-slider',
    'canonical-names/fnd-glass-stepper-ambiguous',
    'canonical-names/fnd-glass-switch',
    'canonical-names/fnd-glass-tag-input',
    'canonical-names/fnd-glass-textarea',
    'canonical-names/fnd-glass-toast',
    'canonical-names/fnd-glass-toast-provider',
    'canonical-names/fnd-glass-toast-viewport',
    'canonical-names/fnd-glass-toggle',
    'canonical-names/fnd-glass-toolbar',
    'canonical-names/fnd-glass-tooltip',
    'canonical-names/fnd-glass-validation-message',
    'canonical-names/fnd-glassstepper-negative',
    'canonical-names/fnd-liquid-glass-adaptive-sheet',
    'canonical-names/fnd-liquid-glass-button-style',
    'canonical-names/fnd-liquid-glass-control-group',
    'canonical-names/fnd-liquid-glass-map-controls',
    'canonical-names/fnd-liquid-glass-popover-menu',
    'canonical-names/fnd-liquid-glass-search-field',
    'canonical-names/fnd-liquid-glass-segmented-control',
    'canonical-names/fnd-liquid-glass-toolbar',
    'canonical-names/fnd-magnetic-button',
    'canonical-names/fnd-positioner',
    'canonical-names/fnd-ripple-button',
    'canonical-names/fnd-toggle-button',
    'canonical-names/fnd-toggle-button-group',
    'canonical-names/fnd-use-notifications',
    'canonical-names/fnd-use-toast',
    'imports-subpaths/fnd-button-deep-import',
    'imports-subpaths/overlays-subpath',
    'prop-grammar/fnd-accordion-role',
    'prop-grammar/fnd-button-checked-event',
    'prop-grammar/fnd-glassbutton-variant-gradient',
    'prop-grammar/fnd-glassmodal-props',
    'prop-grammar/overlays-backdrop-click',
    'prop-grammar/overlays-escape-all',
    'prop-grammar/overlays-on-close-semantics',
    'prop-grammar/overlays-placement',
    'providers/overlays-toast-provider',
    'removed/fnd-glass-achievement-notifications',
    'removed/fnd-glass-transitions-modal',
    'removed/fnd-mobile-glass-bottom-sheet',
  ],
} satisfies CodemodMappingFragment;
