// codemods fragment for SURF (contract S-38..S-45). Lane blocks are owned by SURF lanes W1..W5; edit only your own block.
import type { CodemodMappingFragment } from '../../src/contracts/fragments';

// --- lane W1 begin ---
const w1: CodemodMappingFragment = {
  props: [
    { component: 'AppShell', from: 'header', to: null, todo: 'slot children: render TopBar/PageHeader inside AppShell.Root' },
    { component: 'AppShell', from: 'sidebar', to: null, todo: 'slot children: render Sidebar inside AppShell.Root' },
    { component: 'AppShell', from: 'footer', to: null, todo: 'slot children: render StatusBar inside AppShell.Root' },
    { component: 'AppShell', from: 'sidebarWidth', to: 'sidebarWidth' },
    { component: 'AppShell', from: 'collapsible', to: null, todo: 'sidebar always collapsible via AppShell.SidebarToggle' },
    { component: 'AppShell', from: 'mobileOverlay', to: null, todo: 'mobile overlay is SidebarDrawer, shown by container query' },
    { component: 'AppShell', from: 'padding', to: null, todo: 'padding is css, --ag-space-* tokens' },
    { component: 'AppShell', from: 'maxWidth', to: null, todo: 'main column sizing is css' },
    { component: 'Sidebar', from: 'items', to: null, todo: 'item arrays become Sidebar.Item children (app-shell-slots)' },
    { component: 'Sidebar', from: 'activeId', to: 'currentValue' },
    { component: 'Sidebar', from: 'onClick', to: 'onSelect' },
    { component: 'Sidebar', from: 'badge', to: 'badge' },
    { component: 'Tabs', from: 'selectedTab', to: 'value' },
    { component: 'Tabs', from: 'onTabChange', to: 'onValueChange' },
    { component: 'TabBar', from: 'items', to: null, todo: 'item arrays become TabBar.Item children' },
    { component: 'TabBar', from: 'activeTab', to: 'value' },
    { component: 'Breadcrumbs', from: 'items', to: null, todo: 'item arrays become Breadcrumbs.Item children' },
    { component: 'Breadcrumbs', from: 'separator', to: 'separator' },
    { component: 'Pagination', from: 'totalPages', to: 'pageCount' },
    { component: 'Pagination', from: 'currentPage', to: 'page' },
    { component: 'Pagination', from: 'onChange', to: 'onPageChange' },
    { component: 'CommandPalette', from: 'open', to: 'open' },
    { component: 'CommandPalette', from: 'hotkey', to: 'hotkey' },
  ],
  renames: [
    { from: 'GlassAppShell', fromEntry: 'aura-glass', to: 'AppShell', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassHeader', fromEntry: 'aura-glass', to: 'TopBar', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassTopBar', fromEntry: 'aura-glass', to: 'TopBar', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassNavigation', fromEntry: 'aura-glass', to: 'Sidebar', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassSidebar', fromEntry: 'aura-glass', to: 'Sidebar', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassMain', fromEntry: 'aura-glass', to: 'AppShell', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassPageHeader', fromEntry: 'aura-glass', to: 'AppShell', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassStatusBar', fromEntry: 'aura-glass', to: 'StatusBar', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassInspector', fromEntry: 'aura-glass', to: 'Inspector', toEntry: 'aura-glass/app-shell' },
    { from: 'GlassMobileShell', fromEntry: 'aura-glass', to: 'MobileShell', toEntry: 'aura-glass/app-shell' },
    { from: 'ZSpaceAppLayout', fromEntry: 'aura-glass', to: 'ZSpaceAppLayout', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassTabs', fromEntry: 'aura-glass', to: 'Tabs', toEntry: 'aura-glass' },
    { from: 'GlassPageTabs', fromEntry: 'aura-glass', to: 'GlassPageTabs', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassTabBar', fromEntry: 'aura-glass', to: 'TabBar', toEntry: 'aura-glass' },
    { from: 'GlassWorkspaceTabs', fromEntry: 'aura-glass', to: 'Tabs', toEntry: 'aura-glass' },
    { from: 'LiquidGlassTabBar', fromEntry: 'aura-glass', to: 'LiquidGlassTabBar', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassBottomNav', fromEntry: 'aura-glass', to: 'TabBar', toEntry: 'aura-glass' },
    { from: 'LiquidGlassBottomAccessory', fromEntry: 'aura-glass', to: 'LiquidGlassBottomAccessory', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassMobileNav', fromEntry: 'aura-glass', to: 'GlassMobileNav', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassBreadcrumb', fromEntry: 'aura-glass', to: 'Breadcrumbs', toEntry: 'aura-glass' },
    { from: 'GlassPagination', fromEntry: 'aura-glass', to: 'Pagination', toEntry: 'aura-glass' },
    { from: 'GlassCommandPalette', fromEntry: 'aura-glass', to: 'CommandPalette', toEntry: 'aura-glass' },
    { from: 'GlassCommand', fromEntry: 'aura-glass', to: 'Command', toEntry: 'aura-glass' },
    { from: 'LiquidGlassCommandSurface', fromEntry: 'aura-glass', to: 'LiquidGlassCommandSurface', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'LiquidGlassTransitionProvider', fromEntry: 'aura-glass', to: 'SourceTransition', toEntry: 'aura-glass' },
    { from: 'LiquidGlassSource', fromEntry: 'aura-glass', to: 'SourceTransition', toEntry: 'aura-glass' },
    { from: 'LiquidGlassDestination', fromEntry: 'aura-glass', to: 'SourceTransition', toEntry: 'aura-glass' },
  ],
  areaTransforms: [
    {
      id: 'app-shell-slots',
      module: 'packages/cli/src/migrate/4to5/transforms/app-shell-slots.ts',
      spec: 'GlassAppShell header/sidebar/footer props -> slot children; GlassSidebar/GlassSidebarRail item arrays -> Sidebar.Item/Rail.Item children; handler-only items (onClick/onSelect, no href) stay actions',
    },
  ],
  fixtures: ['fragments/codemods/surf/fixtures/app-shell-slots'],
};
// --- lane W1 end ---

// --- lane W2 begin ---
const w2: CodemodMappingFragment = {
  props: [
    // GlassDataGrid ColumnDefinition (REQ-SURF-14)
    { component: 'Table.Column', from: 'key', to: 'accessorKey' },
    { component: 'Table.Column', from: 'label', to: 'header' },
    { component: 'Table.Column', from: 'sortable', to: 'enableSorting' },
    { component: 'Table.Column', from: 'width', to: 'size', todo: 'string widths need a css var or px number' },
    { component: 'Table.Column', from: 'render', to: 'cell', todo: 'wrap as ({ getValue, row }) => render(getValue(), row.original)' },
    { component: 'Table.Column', from: 'cellRenderer', to: 'cell', todo: 'wrap as ({ getValue, row }) => cellRenderer(getValue(), row.original)' },
    { component: 'Table.Column', from: 'align', to: 'meta.align', values: { left: 'start', right: 'end', center: 'center' } },
    // GlassDataTable (REQ-SURF-14)
    { component: 'Table', from: 'rows', to: 'data' },
    { component: 'Table', from: 'filterable', to: 'enableColumnFilter' },
    { component: 'Table', from: 'compact', to: 'size', values: { true: 'sm' } },
    { component: 'Table', from: 'selectedRows', to: 'rowSelection', todo: 'array -> Record<id, true>' },
    { component: 'Table', from: 'onSelectionChange', to: 'onRowSelectionChange', todo: 'array -> Record<id, true>' },
    { component: 'Table', from: 'onRowClick', to: 'onRowAction' },
    { component: 'Table', from: 'emptyMessage', to: 'emptyState' },
    { component: 'Table', from: 'consciousness', to: null, todo: 'dropped 4.x simulated prop' },
    // GlassDatePicker (REQ-SURF-14)
    { component: 'DatePicker', from: 'onChange', to: 'onValueChange' },
    { component: 'DatePicker', from: 'minDate', to: 'minValue', todo: 'Date -> CalendarDate via fromDate(getLocalTimeZone()) client-side' },
    { component: 'DatePicker', from: 'maxDate', to: 'maxValue', todo: 'Date -> CalendarDate via fromDate(getLocalTimeZone()) client-side' },
    { component: 'DatePicker', from: 'disabledDates', to: 'isDateUnavailable', todo: 'Date param -> DateValue' },
    { component: 'DatePicker', from: 'disabled', to: 'isDisabled' },
    { component: 'DatePicker', from: 'required', to: 'isRequired' },
    { component: 'DatePicker', from: 'error', to: 'isInvalid' },
    { component: 'DatePicker', from: 'helperText', to: 'description' },
    { component: 'DatePicker', from: 'format', to: null, todo: 'display format is locale-driven at 5.0' },
    { component: 'DatePicker', from: 'mode', to: null, todo: 'mode="range" -> DateRangePicker' },
    // GlassDateField / GlassTimeField
    { component: 'DateField', from: 'onChange', to: 'onValueChange' },
    { component: 'DateField', from: 'minDate', to: 'minValue' },
    { component: 'DateField', from: 'maxDate', to: 'maxValue' },
    { component: 'TimeField', from: 'onChange', to: 'onValueChange' },
    // GlassStatCard / GlassSparkline / GlassTimeline
    { component: 'StatCard', from: 'title', to: 'label' },
    { component: 'StatCard', from: 'trend', to: 'trendDirection', values: { up: 'up-is-good', down: 'up-is-good', flat: 'neutral' } },
    { component: 'Sparkline', from: 'values', to: 'data' },
    { component: 'Sparkline', from: 'color', to: 'intent', todo: 'map hex/name to neutral|info|success|danger' },
    { component: 'Timeline', from: 'events', to: 'items' },
    { component: 'ActivityFeed', from: 'entries', to: 'items' },
    { component: 'FilterBar', from: 'fields', to: 'schema' },
    { component: 'FilterBar', from: 'filters', to: 'value' },
    { component: 'FilterBar', from: 'onChange', to: 'onValueChange' },
    { component: 'TreeView', from: 'nodes', to: 'items' },
    { component: 'TreeView', from: 'selectedId', to: 'selectedKeys', todo: 'single key -> [key]' },
    { component: 'TreeView', from: 'onSelect', to: 'onSelectionChange', todo: 'id -> Set<React.Key>' },
    { component: 'Chip', from: 'label', to: null, todo: 'children carry the label' },
    { component: 'Chip', from: 'text', to: null, todo: 'children carry the label' },
    { component: 'Chip', from: 'onSelect', to: 'onSelectedChange' },
    { component: 'KeyValueEditor', from: 'entries', to: 'value', todo: 'Record -> [{key,value}] pairs' },
    { component: 'KeyValueEditor', from: 'pairs', to: 'value', todo: 'Record -> [{key,value}] pairs' },
    { component: 'KeyValueEditor', from: 'onChange', to: 'onValueChange' },
    { component: 'Calendar', from: 'onChange', to: 'onValueChange' },
    { component: 'Calendar', from: 'weekNumbers', to: 'showWeekNumbers' },
  ],
  renames: [
    { from: 'GlassDataTable', fromEntry: 'aura-glass', to: 'Table', toEntry: 'aura-glass/data' },
    { from: 'GlassDataGrid', fromEntry: 'aura-glass', to: 'Table', toEntry: 'aura-glass/data' },
    { from: 'GlassVirtualTable', fromEntry: 'aura-glass', to: 'GlassVirtualTable', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassVirtualList', fromEntry: 'aura-glass', to: 'GlassVirtualList', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassTreeView', fromEntry: 'aura-glass', to: 'TreeView', toEntry: 'aura-glass/data' },
    { from: 'TreeView', fromEntry: 'aura-glass', to: 'TreeView', toEntry: 'aura-glass/data' },
    { from: 'GlassFileTree', fromEntry: 'aura-glass', to: 'GlassFileTree', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassFileExplorer', fromEntry: 'aura-glass', to: 'GlassFileExplorer', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassFilterBar', fromEntry: 'aura-glass', to: 'FilterBar', toEntry: 'aura-glass/data' },
    { from: 'GlassStatCard', fromEntry: 'aura-glass', to: 'StatCard', toEntry: 'aura-glass/data' },
    { from: 'GlassKPICard', fromEntry: 'aura-glass', to: 'StatCard', toEntry: 'aura-glass/data' },
    { from: 'GlassMetricCard', fromEntry: 'aura-glass', to: 'StatCard', toEntry: 'aura-glass/data' },
    { from: 'GlassMetricChip', fromEntry: 'aura-glass', to: 'Chip', toEntry: 'aura-glass/data' },
    { from: 'GlassAnimatedNumber', fromEntry: 'aura-glass', to: 'GlassAnimatedNumber', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassSparkline', fromEntry: 'aura-glass', to: 'Sparkline', toEntry: 'aura-glass/data' },
    { from: 'GlassTimeline', fromEntry: 'aura-glass', to: 'Timeline', toEntry: 'aura-glass' },
    { from: 'GlassActivityFeed', fromEntry: 'aura-glass', to: 'ActivityFeed', toEntry: 'aura-glass' },
    { from: 'GlassChip', fromEntry: 'aura-glass', to: 'Chip', toEntry: 'aura-glass/data' },
    { from: 'GlassKeyValueEditor', fromEntry: 'aura-glass', to: 'KeyValueEditor', toEntry: 'aura-glass/data' },
    { from: 'GlassDateField', fromEntry: 'aura-glass', to: 'DateField', toEntry: 'aura-glass/date' },
    { from: 'GlassTimeField', fromEntry: 'aura-glass', to: 'TimeField', toEntry: 'aura-glass/date' },
    { from: 'GlassDatePicker', fromEntry: 'aura-glass', to: 'DatePicker', toEntry: 'aura-glass/date' },
    { from: 'GlassDateRangePicker', fromEntry: 'aura-glass', to: 'DateRangePicker', toEntry: 'aura-glass/date' },
    { from: 'GlassCalendar', fromEntry: 'aura-glass', to: 'Calendar', toEntry: 'aura-glass/date' },
    { from: 'GlassSearchBar', fromEntry: 'aura-glass', to: 'FilterBar', toEntry: 'aura-glass/data' },
  ],
  removed: [
    { symbol: 'GlassDataChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'DataChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'ModularGlassDataChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassLineChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassBarChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassAreaChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassPieChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassDonutChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', registryItem: 'chart-adapter', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassChartContainer', entry: 'aura-glass', reason: 'chart engines removed at 5.0', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassChartWidget', entry: 'aura-glass', reason: 'chart engines removed at 5.0', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassAdvancedDataViz', entry: 'aura-glass', reason: 'chart engines removed at 5.0', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassChartsDemo', entry: 'aura-glass', reason: 'demo-only export removed at 5.0', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassHeatmap', entry: 'aura-glass', reason: 'no 5.0 successor (5.x candidate)', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassGanttChart', entry: 'aura-glass', reason: 'moved to a registry item owned by PLAT', registryItem: 'gantt', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'KpiChart', entry: 'aura-glass', reason: 'chart engines removed at 5.0', doc: 'docs/auraglass-5/migration/chart-adapter.md' },
    { symbol: 'GlassMetricsGrid', entry: 'aura-glass', reason: 'docs composition over StatCard grid', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'GlassVirtualGrid', entry: 'aura-glass', reason: 'replaced; no 5.0 successor', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'GlassInfiniteScroll', entry: 'aura-glass', reason: 'no 5.0 successor; cursor paging via Table', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'GlassListView', entry: 'aura-glass', reason: 'docs composition', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'GlassFormTable', entry: 'aura-glass', reason: 'no 5.0 successor until 5.1 inline edit', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'TableWidget', entry: 'aura-glass', reason: 'no 5.0 successor', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'GlassDataGridPro', entry: 'aura-glass', reason: 'REMOVE disposition at 4.2', doc: 'docs/auraglass-5/migration/data-table.md' },
    { symbol: 'QueryBuilder', entry: 'aura-glass', reason: 'moved to a registry item', registryItem: 'query-builder', doc: 'docs/auraglass-5/migration/data-table.md' },
  ],
  deps: [
    { pkg: 'react-aria-components', range: '^1.0.0', when: 'aura-glass/date imported' },
    { pkg: '@internationalized/date', range: '^3.6.0', when: 'aura-glass/date imported' },
    { pkg: 'chart.js', range: '-', when: 'consumer direct import — remove; wrap a chart lib in ChartFrame' },
    { pkg: 'react-chartjs-2', range: '-', when: 'consumer direct import — remove' },
    { pkg: 'date-fns', range: '-', when: 'consumer direct import — migrate to @internationalized/date' },
  ],
  fixtures: ['fragments/codemods/surf/fixtures/data-grid-columns'],
};
// --- lane W2 end ---

// --- lane W3 begin ---
const w3: CodemodMappingFragment = {
  renames: [
    { from: 'GlassChat', fromEntry: 'aura-glass', to: 'GlassChat', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassChatInput', fromEntry: 'aura-glass', to: 'GlassChatInput', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassMessageList', fromEntry: 'aura-glass', to: 'GlassMessageList', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassTypingIndicator', fromEntry: 'aura-glass', to: 'GlassTypingIndicator', toEntry: 'aura-glass/compat', compatOnly: true },
  ],
  props: [
    { component: 'Thread', from: 'messages', to: 'messages', values: { ChatMessage: 'AgMessage' } },
    { component: 'Composer', from: 'value', to: 'value' },
    { component: 'Composer', from: 'onSend', to: 'onSubmit', values: { '(text)': '{ text, files }' } },
    { component: 'Composer', from: 'onVoiceRecording', to: null, todo: 'use the ai-voice-input registry item' },
    { component: 'Composer', from: 'placeholder', to: 'labels.input' },
    { component: 'Thread', from: 'virtualScroll', to: null, todo: 'virtualization is automatic above virtualizeAfter' },
    { component: 'Message', from: 'reactions', to: null, todo: 'no 5.0 successor' },
    { component: 'Message', from: 'replyTo', to: null, todo: 'no 5.0 successor' },
    { component: 'Message', from: 'edited', to: null, todo: 'no 5.0 successor' },
  ],
  removed: [
    { symbol: 'GlassPredictiveChat', entry: 'aura-glass', reason: 'predictive/simulated AI rejected at 5.0', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassVoiceInput', entry: 'aura-glass', reason: 'moved to a registry item', registryItem: 'ai-voice-input', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassGANGenerator', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassDeepDreamGlass', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassStyleTransfer', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassGenerativeArt', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'AIGlassThemeProvider', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'NeuromorphicLearningNetwork', entry: 'aura-glass', reason: 'rejected; none in 5.0', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassPredictiveEngine', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassAutoComposer', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'useAutoComposer', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'NeuralWeightVisualization', entry: 'aura-glass', reason: 'generic matrix viz; none in 5.0', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassMusicVisualizer', entry: 'aura-glass', reason: 'no successor until 5.1 (Waveform)', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassVoiceWaveform', entry: 'aura-glass', reason: 'no successor until 5.1 (Waveform)', doc: 'apps/docs/content/surf/migration/ai.md' },
    { symbol: 'GlassLiveFilter', entry: 'aura-glass', reason: 'rejected simulated-AI family', doc: 'apps/docs/content/surf/migration/ai.md' },
  ],
  areaTransforms: [
    {
      id: 'ai-chat',
      module: 'packages/cli/src/migrate/4to5/transforms/ai-chat.ts',
      spec: "Rewrite the four chat imports (GlassChat, GlassChatInput, GlassMessageList, GlassTypingIndicator) from 'aura-glass' to 'aura-glass/compat' and insert '// TODO(aura-glass 5): migrate to aura-glass/ai Thread/Message/Composer, see <doc>' above the import without touching JSX structure.",
    },
  ],
  fixtures: ['fragments/codemods/surf/fixtures/ai-chat-imports'],
};
// --- lane W3 end ---

// --- lane W4 begin ---
// W4 rows (REQ-SURF-14, media/backdrop family): renames for every absorbed
// name, the media-backdrops areaTransform spec, prop rows equal to the meta
// `migration` fields, and removed rows with registryItem pointers.
const w4: CodemodMappingFragment = {
  renames: [
    { from: 'LiquidGlassMediaControls', fromEntry: 'aura-glass', to: 'MediaControls', toEntry: 'aura-glass/media' },
    { from: 'GlassMediaControls', fromEntry: 'aura-glass', to: 'MediaControls', toEntry: 'aura-glass/media' },
    { from: 'LiquidGlassNowPlayingBar', fromEntry: 'aura-glass', to: 'NowPlayingBar', toEntry: 'aura-glass/media' },
    { from: 'LiquidGlassPhotoInspector', fromEntry: 'aura-glass', to: 'ImageViewer', toEntry: 'aura-glass/media' },
    { from: 'GlassImageViewer', fromEntry: 'aura-glass', to: 'ImageViewer', toEntry: 'aura-glass/media' },
    { from: 'GlassCarousel', fromEntry: 'aura-glass', to: 'CarouselRail', toEntry: 'aura-glass/media' },
    { from: 'LiquidGlassCarouselRail', fromEntry: 'aura-glass', to: 'CarouselRail', toEntry: 'aura-glass/media' },
    { from: 'AuroraBackground', fromEntry: 'aura-glass', to: 'Backdrop', toEntry: 'aura-glass/backdrops' },
    { from: 'AuroraOrb', fromEntry: 'aura-glass', to: 'Backdrop', toEntry: 'aura-glass/backdrops' },
    { from: 'AtmosphericBackground', fromEntry: 'aura-glass', to: 'Backdrop', toEntry: 'aura-glass/backdrops' },
    { from: 'GlassDynamicAtmosphere', fromEntry: 'aura-glass', to: 'Backdrop', toEntry: 'aura-glass/backdrops' },
    { from: 'DynamicAtmosphere', fromEntry: 'aura-glass', to: 'GlassDynamicAtmosphere', toEntry: 'aura-glass/compat', compatOnly: true },
    { from: 'GlassMeshGradient', fromEntry: 'aura-glass', to: 'Backdrop', toEntry: 'aura-glass/backdrops' },
  ],
  props: [
    { component: 'MediaControls', from: 'onPlayPause', to: 'onPlayingChange' },
    { component: 'MediaControls', from: 'compact', to: null, todo: 'compose MediaControls.PlayButton + MediaControls.Scrubber' },
    { component: 'ImageViewer', from: 'images', to: 'items', todo: 'items gain ids (img-<index>) and required alt' },
    { component: 'ImageViewer', from: 'initialIndex', to: 'defaultValue' },
    { component: 'CarouselRail', from: 'infinite', to: 'loop' },
    { component: 'CarouselRail', from: 'slidesToShow', to: 'slidesPerView' },
    { component: 'CarouselRail', from: 'autoPlay', to: 'autoplay', todo: 'autoplay={{ interval }} only with an allowContinuous provider' },
    { component: 'Backdrop', from: 'motion', to: 'motion', values: { 'none': 'static', 'subtle': 'static', 'full': 'drift' } },
    { component: 'Backdrop', from: 'colors', to: null, todo: 'mesh/aurora palettes come from S-03 colours' },
  ],
  removed: [
    { symbol: 'GlassGallery', entry: 'aura-glass', reason: 'absorbed; lightbox is ImageViewer', registryItem: 'media-gallery', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'ImageList', entry: 'aura-glass', reason: 'absorbed; CMP Grid + native img', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'ImageListItem', entry: 'aura-glass', reason: 'absorbed; CMP Grid + native img', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'ImageListItemBar', entry: 'aura-glass', reason: 'absorbed; CMP Grid + native img', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassLazyImage', entry: 'aura-glass', reason: 'absorbed; native img loading="lazy"', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassVideoPlayer', entry: 'aura-glass', reason: 'media players are consumer element + useMediaElement + MediaControls', registryItem: 'media-video-player', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassAdvancedVideoPlayer', entry: 'aura-glass', reason: 'media players are consumer element + useMediaElement + MediaControls', registryItem: 'media-video-player', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassAdvancedAudioPlayer', entry: 'aura-glass', reason: 'media players are consumer element + useMediaElement + MediaControls', registryItem: 'media-audio-player', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassMediaProvider', entry: 'aura-glass', reason: 'replaced by useMediaElement', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassVoiceWaveform', entry: 'aura-glass', reason: 'no successor until 5.1 (Waveform)', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassMusicVisualizer', entry: 'aura-glass', reason: 'no successor until 5.1 (Waveform)', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'ParticleBackground', entry: 'aura-glass', reason: 'particles move to the labs package', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassParticles', entry: 'aura-glass', reason: 'particles move to the labs package', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'GlassParticleField', entry: 'aura-glass', reason: 'particles move to the labs package', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'LiquidGlassBackdropSampler', entry: 'aura-glass', reason: 'tone sampling is Backdrop/useMediaElement({sampleTone})', doc: 'apps/docs/content/surf/migration/media.md' },
    { symbol: 'useLiquidGlassBackdrop', entry: 'aura-glass', reason: 'tone sampling is Backdrop/useMediaElement({sampleTone})', doc: 'apps/docs/content/surf/migration/media.md' },
  ],
  areaTransforms: [
    {
      id: 'media-backdrops',
      module: 'packages/cli/src/migrate/4to5/transforms/media-backdrops.ts',
      spec: [
        'LiquidGlassMediaControls: onPlayPause -> onPlayingChange; compact -> compose <MediaControls.PlayButton/><MediaControls.Scrubber/>.',
        'GlassImageViewer: images -> items (ids img-<index>), initialIndex -> defaultValue; missing alt -> alt: "" + TODO.',
        'GlassCarousel/LiquidGlassCarouselRail: infinite -> loop; slidesToShow -> slidesPerView; autoPlay + autoPlayInterval -> autoplay={{ interval }} (+ TODO when no allowContinuous provider is found).',
        'AuroraBackground: motion none|subtle -> static, full -> drift.',
        'GlassMeshGradient colors[], AtmosphericBackground variant/weather/colorScheme, DynamicAtmosphere type/primaryColor/secondaryColor -> TODO rows.',
      ].join(' '),
    },
  ],
  fixtures: [
    'fragments/codemods/surf/fixtures/media-backdrops/media-controls',
    'fragments/codemods/surf/fixtures/media-backdrops/image-viewer',
    'fragments/codemods/surf/fixtures/media-backdrops/carousel-autoplay',
    'fragments/codemods/surf/fixtures/media-backdrops/aurora-motion',
  ],
};
// --- lane W4 end ---

// --- lane W5 begin ---
// W5 rows: workspace/workflows subpaths plus the commerce/presence/comment
// 4.x exports removed at 5.0 (DEP-S0800..S0813). Every row names a real
// release/4.x export; `registryItem` points at the 5.1 successor block/item.
const w5: CodemodMappingFragment = {
  renames: [
    {
      from: 'SmartShoppingCart',
      fromEntry: '.',
      to: 'GlassSmartShoppingCart',
      toEntry: '.',
      compatOnly: false,
    },
  ],
  removed: [
    { symbol: '*', entry: './workspace', reason: 'subpath removed; the app-shell workspace recipes replace it', doc: '#dep-s0800' },
    { symbol: '*', entry: './workflows', reason: 'subpath removed; the app-shell workspace recipes and 5.x registry blocks replace it', doc: '#dep-s0801' },
    { symbol: 'GlassSmartShoppingCart', entry: '.', reason: 'baked-in commerce logic; the registry block takes data by props', registryItem: 'commerce-cart', doc: '#dep-s0804' },
    { symbol: 'GlassEcommerceProvider', entry: '.', reason: 'consumer-owned commerce state; no successor', doc: '#dep-s0806' },
    { symbol: 'GlassProductRecommendations', entry: '.', reason: 'compose the commerce blocks on Card and CarouselRail', registryItem: 'commerce-cart', doc: '#dep-s0805' },
    { symbol: 'GlassCommentThread', entry: '.', reason: 'consolidated into the single comment surface', registryItem: 'comment-thread', doc: '#dep-s0803' },
    { symbol: 'GlassCollaborativeComments', entry: '.', reason: 'comment-thread item plus an anchored-popover pin primitive', registryItem: 'comment-thread', doc: '#dep-s0809' },
    { symbol: 'GlassTeamCursors', entry: '.', reason: 'drew fake cursors with no data input', registryItem: 'presence-stack', doc: '#dep-s0807' },
    { symbol: 'GlassTeamCursorsWithEffects', entry: '.', reason: 'effect variant layered static circles on fake cursors', registryItem: 'presence-stack', doc: '#dep-s0808' },
    { symbol: 'GlassUserPresence', entry: '.', reason: 'random presence colours; deterministic ids in the registry item', registryItem: 'presence-stack', doc: '#dep-s0810' },
    { symbol: 'GlassPresenceIndicator', entry: '.', reason: 'consolidated into presence-stack', registryItem: 'presence-stack', doc: '#dep-s0811' },
    { symbol: 'GlassLiveCursorPresence', entry: '.', reason: 'render cursors from a consumer presence channel', registryItem: 'presence-stack', doc: '#dep-s0812' },
    { symbol: 'GlassCollaborativeCursor', entry: '.', reason: 'render cursors from a consumer presence channel', registryItem: 'presence-stack', doc: '#dep-s0813' },
  ],
};
// --- lane W5 end ---

export default {
  renames: [...(w1.renames ?? []), ...(w2.renames ?? []), ...(w3.renames ?? []), ...(w4.renames ?? []), ...(w5.renames ?? [])],
  props: [...(w1.props ?? []), ...(w2.props ?? []), ...(w3.props ?? []), ...(w4.props ?? []), ...(w5.props ?? [])],
  removed: [...(w1.removed ?? []), ...(w2.removed ?? []), ...(w3.removed ?? []), ...(w4.removed ?? []), ...(w5.removed ?? [])],
  deps: [...(w1.deps ?? []), ...(w2.deps ?? []), ...(w3.deps ?? []), ...(w4.deps ?? []), ...(w5.deps ?? [])],
  areaTransforms: [...(w1.areaTransforms ?? []), ...(w2.areaTransforms ?? []), ...(w3.areaTransforms ?? []), ...(w4.areaTransforms ?? []), ...(w5.areaTransforms ?? [])],
  fixtures: [...(w1.fixtures ?? []), ...(w2.fixtures ?? []), ...(w3.fixtures ?? []), ...(w4.fixtures ?? []), ...(w5.fixtures ?? [])],
  cssVars: { ...(w1.cssVars ?? {}), ...(w2.cssVars ?? {}), ...(w3.cssVars ?? {}), ...(w4.cssVars ?? {}), ...(w5.cssVars ?? {}) },
} satisfies CodemodMappingFragment;
