/* PLAT-293: `import *` from every emitted entry under strict +
   exactOptionalPropertyTypes + skipLibCheck:false. Entries still seed-pending
   are added as they land (the manifest is regenerated by the runner). */
import * as material from 'aura-glass/material';
import * as tokens from 'aura-glass/tokens';
import * as icons from 'aura-glass/icons';
import * as data from 'aura-glass/data';
import * as date from 'aura-glass/date';
import * as three from 'aura-glass/three';
import * as charts from 'aura-glass/charts';
import * as internal from 'aura-glass/internal';

export const modules = { material, tokens, icons, data, date, three, charts, internal };
