// @auraglass/registry package manifest invariants (REQ-FIN-09: `npm test -w packages/registry`
// runs real assertions; REQ-PLAT-94 data-only package shape). Registry item/index behaviour
// tests are REQ-FIN-42's (plat:test:registry) and land with that PR.
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));

/** True when a package-relative path is shipped by the `files` allowlist (npm always ships package.json). */
const shipped = (rel) => {
  const p = rel.replace(/^\.\//, '');
  if (p === 'package.json') return true;
  return pkg.files.some((f) => p === f || p.startsWith(`${f}/`));
};

describe('@auraglass/registry package.json', () => {
  test('is the public ESM package @auraglass/registry', () => {
    expect(pkg.name).toBe('@auraglass/registry');
    expect(pkg.type).toBe('module');
    expect(pkg.private).toBe(false);
    expect(pkg.license).toBe('MIT');
  });

  test('is data-only: no runtime dependencies, no bin, no main entry', () => {
    expect(pkg.dependencies).toBeUndefined();
    expect(pkg.peerDependencies).toBeUndefined();
    expect(pkg.bin).toBeUndefined();
    expect(pkg.main).toBeUndefined();
  });

  test('ships r/*.json and index.json and every exports target is inside `files`', () => {
    expect(pkg.files).toEqual(expect.arrayContaining(['r', 'index.json']));
    expect(pkg.exports['./index.json']).toBe('./index.json');
    expect(pkg.exports['./r/*.json']).toBe('./r/*.json');
    const notShipped = Object.values(pkg.exports).filter((t) => !shipped(t.replace('*', 'x')));
    expect(notShipped).toEqual([]);
  });

  test('every literal (non-generated) `files` entry exists in the package', () => {
    // r/ and index.json are generated by scripts/registry/build.mjs and git-ignored until packed.
    const generated = new Set(['r', 'index.json']);
    const missing = pkg.files.filter((f) => !generated.has(f) && !existsSync(join(pkgDir, f)));
    expect(missing).toEqual([]);
  });

  test('publishes publicly with provenance', () => {
    expect(pkg.publishConfig).toEqual(expect.objectContaining({ access: 'public', provenance: true }));
  });
});
