// QUAL (REQ-FIN-106, FIN-450; PRD-F §4.3 rule 3): the expiring baseline of the Storybook story gates.
// `certification/baselines-gates/story-contract.json` lists every pre-existing offender (by owner) of the
// story-contract validator, the title lint, the copy lint and the docs-page check at the time the gate landed.
// A violation that is NOT in the baseline fails. The baseline only shrinks: `--prune` removes rows that no longer
// reproduce, there is no "add" mode (only `--init`, which refuses to overwrite an existing file). It expires at
// RC-1: once package.json reaches 5.0.0-rc.1 (or GA) every remaining row is itself a failure.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { ROOT } from './story-static.mjs';

export const BASELINE_PATH = 'certification/baselines-gates/story-contract.json';
export const CHECKS = ['story-contract', 'story-titles', 'story-copy', 'docs-pages'];

export const rowKey = (r) => `${r.check}|${r.rule}|${r.key}`;

/** True once the package version is a 5.x release candidate or GA (the baseline's `expires: RC-1`). */
export function baselineExpired(version) {
  const m = /^(\d+)\.(\d+)\.(\d+)(?:-([a-z]+)\.(\d+))?$/.exec(String(version));
  if (!m) throw new Error(`baseline: unparseable package version ${version}`);
  if (Number(m[1]) < 5) return false;
  return m[4] === undefined || m[4] === 'rc';
}

export function loadBaseline(root = ROOT, path = BASELINE_PATH) {
  const abs = join(root, path);
  if (!existsSync(abs)) return { rows: [], missing: true };
  const b = JSON.parse(readFileSync(abs, 'utf8'));
  if (b.version !== 1 || b.expires !== 'RC-1' || !Array.isArray(b.rows)) throw new Error(`baseline: ${path} must be { version: 1, expires: "RC-1", rows: [] }`);
  for (const r of b.rows) {
    if (!CHECKS.includes(r.check) || typeof r.rule !== 'string' || typeof r.key !== 'string' || typeof r.owner !== 'string') {
      throw new Error(`baseline: malformed row ${JSON.stringify(r)}`);
    }
  }
  return b;
}

/**
 * Split violations into `introduced` (fail), `baselined` (pre-existing, owner fixes them) and list `stale` baseline rows
 * of the given checks that no longer reproduce (pruned by QUAL with `--prune`). After RC-1 every violation is introduced.
 */
export function compare(violations, baseline, { checks, version }) {
  const expired = baselineExpired(version);
  const rows = baseline.rows.filter((r) => checks.includes(r.check));
  const known = new Set(expired ? [] : rows.map(rowKey));
  const seen = new Set(violations.map(rowKey));
  return {
    expired,
    introduced: violations.filter((v) => !known.has(rowKey(v))),
    baselined: violations.filter((v) => known.has(rowKey(v))),
    stale: rows.filter((r) => !seen.has(rowKey(r))),
    expiredRows: expired ? rows : [],
  };
}

const toRow = (v) => ({ check: v.check, rule: v.rule, key: v.key, owner: v.owner, ...(v.file ? { file: v.file } : {}) });
const sortRows = (rows) => rows.sort((a, b) => a.owner.localeCompare(b.owner) || a.check.localeCompare(b.check) || a.rule.localeCompare(b.rule) || a.key.localeCompare(b.key));

/** Create the baseline from the current offenders. Refuses to run when the file exists (the baseline never grows). */
export function initBaseline(violations, root = ROOT, path = BASELINE_PATH) {
  const abs = join(root, path);
  if (existsSync(abs)) throw new Error(`baseline: ${path} exists; it only shrinks (use --prune)`);
  mkdirSync(dirname(abs), { recursive: true });
  const rows = sortRows([...new Map(violations.map((v) => [rowKey(v), toRow(v)])).values()]);
  writeFileSync(abs, `${JSON.stringify({
    $comment: 'Expiring baseline (PRD-F §4.3 rule 3) for the QUAL story gates: story-contract (REQ-QUAL-50), story-titles (REQ-QUAL-49), story-copy (REQ-QUAL-50), docs-pages (REQ-QUAL-51). Generated by the gate scripts (--init); shrinks only (--prune); every row is an owner fix. Empty at RC-1.',
    version: 1, gate: 'story-contract', reqFin: 'REQ-FIN-106', expires: 'RC-1', rows,
  }, null, 2)}\n`);
  return rows.length;
}

/** Remove rows (of the given checks) that no longer reproduce. Never adds a row. */
export function pruneBaseline(violations, checks, root = ROOT, path = BASELINE_PATH) {
  const b = loadBaseline(root, path);
  if (b.missing) throw new Error(`baseline: ${path} does not exist`);
  const seen = new Set(violations.map(rowKey));
  const before = b.rows.length;
  b.rows = b.rows.filter((r) => !checks.includes(r.check) || seen.has(rowKey(r)));
  writeFileSync(join(root, path), `${JSON.stringify(b, null, 2)}\n`);
  return before - b.rows.length;
}

/** Human summary grouped by owner (failures are attributed to the owner's paths, contract §6.1). */
export function formatByOwner(violations) {
  const by = new Map();
  for (const v of violations) {
    if (!by.has(v.owner)) by.set(v.owner, []);
    by.get(v.owner).push(v);
  }
  return [...by.keys()].sort().map((o) => `${o} (${by.get(o).length})\n${by.get(o).map((v) => `  [${v.check}/${v.rule}] ${v.message}`).join('\n')}`).join('\n');
}

export function packageVersion(root = ROOT) {
  return JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
}
