/* @generated by scripts/release/sync-fragments.mjs — do not edit by hand.
   Contract seed: the 4.x deprecations fragment folds into this file once a
   sync/fragments-deprecations-* PR lands (§3.6). */
import type { DeprecationFragment } from '../contracts/fragments';

export const deprecations: DeprecationFragment = [];
