/* @ag-contract-seed: S-37. PLAT-owned internals. cn and warnDeprecated are final;
   deprecations is the generated table (empty until a sync/fragments-* PR lands it). */
import clsx, { type ClassValue } from 'clsx';

export const cn = (...inputs: ClassValue[]) => clsx(...inputs);

const warned = new Set<string>();
export function warnDeprecated(id: string): void {
  if (process.env.NODE_ENV === 'production') return;
  if (warned.has(id)) return;
  warned.add(id);
  console.warn(`aura-glass: '${id}' is deprecated (see deprecations.json)`);
}

/** Generated by scripts/release/sync-fragments.mjs — do not edit by hand. */
export { deprecations } from './deprecations.generated';
