/* @generated by scripts/tokens/build.mjs. Do not edit by hand. */
export const motionTokens = {
  "duration.ambient": 40000,
  "duration.instant": 90,
  "duration.instant-exit": 60,
  "duration.large": 450,
  "duration.large-exit": 320,
  "duration.medium": 320,
  "duration.medium-exit": 220,
  "duration.micro": 120,
  "duration.micro-exit": 80,
  "duration.small": 200,
  "duration.small-exit": 140,
  "ease.accelerate": "cubic-bezier(0.3, 0, 1, 1)",
  "ease.emphasized": "cubic-bezier(0.2, 0, 0, 1)",
  "ease.emphasized-decelerate": "cubic-bezier(0.05, 0.7, 0.1, 1)",
  "ease.standard": "cubic-bezier(0.2, 0, 0, 1)",
  "spring.fluid":
    "linear(0, 0.0059, 0.0247, 0.054, 0.0958, 0.1396, 0.1931, 0.4232, 0.5321, 0.6346, 0.7189, 0.7897, 0.8501, 0.8976, 0.9369, 0.9651, 0.9865, 1, 1, 1, 1, 1)",
  "spring.fluid-duration": 700,
  "spring.smooth":
    "linear(0, 0.0054, 0.0204, 0.0474, 0.0879, 0.1749, 0.3979, 0.4969, 0.5976, 0.6797, 0.7491, 0.8097, 0.8582, 0.8982, 0.9327, 0.958, 0.9768, 0.9899, 0.9968, 1, 1)",
  "spring.smooth-duration": 520,
  "spring.snappy":
    "linear(0, 0.0042, 0.0209, 0.0476, 0.0816, 0.1637, 0.369, 0.4657, 0.571, 0.653, 0.7281, 0.789, 0.8414, 0.8818, 0.9167, 0.9448, 0.9656, 0.9809, 0.9902, 0.9958, 1)",
  "spring.snappy-duration": 350,
} as const;
