/**
 * Compiled codemod mappings loader (S-50/S-39). The JSON under mappings/ is
 * generated by scripts/gen-mappings.mjs from loadFragments('codemods') +
 * loadFragments('deprecations'). Transforms consume only this compiled
 * output — no hard-coded tables in transforms/**.
 */
import fs from 'node:fs';
import path from 'node:path';

/** prop-grammar row (S-39 shape). */
export interface PropRow {
  component: string;
  from: string;
  to: string | null;
  values?: Record<string, string | Record<string, unknown>>;
  todo?: string;
}
export interface ComponentMapping {
  to?: string;
  toEntry?: string;
  compatOnly: boolean;
  props?: PropRow[];
}
export interface RemovedRow { symbol: string; entry: string; reason: string; registryItem?: string; doc: string }
export interface CompiledMappings {
  /** 4.x export name -> target. */
  components: Record<string, ComponentMapping>;
  /** symbol OR subpath -> removed row. */
  removed: Record<string, RemovedRow>;
  /** --glass-* -> --ag-* (null = deleted). */
  cssVars: Record<string, string | null>;
  /** npm deps plan. */
  deps: Array<{ pkg: string; range: string; when: string }>;
  /**
   * Exact subpath rewrites (fromEntry -> toEntry) plus prefix rules.
   * Keys ending `/*` are prefix rules; `$basename` in a value substitutes the
   * final path segment of the matched specifier.
   */
  subpaths: Record<string, string>;
  /** removeIn entries for doctor --v5. */
  deprecations: Array<Record<string, unknown>>;
  /** area transform spec text (id -> spec). */
  areaSpecs: Record<string, string>;
}

function findPkgRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 12; i += 1) {
    const pj = path.join(dir, 'package.json');
    if (fs.existsSync(pj)) {
      try {
        const j = JSON.parse(fs.readFileSync(pj, 'utf8')) as { name?: string };
        if (j.name === '@auraglass/cli') return dir;
      } catch { /* keep walking */ }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}
export const MAPPINGS_DIR = path.join(findPkgRoot(), 'src', 'migrate', '4to5', 'mappings');

interface RawFragment {
  renames?: Array<{ from: string; fromEntry: string; to: string; toEntry: string; compatOnly?: boolean }>;
  props?: PropRow[];
  cssVars?: Record<string, string | null>;
  removed?: RemovedRow[];
  deps?: Array<{ pkg: string; range: string; when: string }>;
  deprecations?: Array<Record<string, unknown>>;
  areaTransforms?: Array<{ id: string; module?: string; spec: string }>;
}

function normEntry(e: string | undefined): string {
  if (!e) return 'aura-glass';
  if (e === '.') return 'aura-glass';
  if (e.startsWith('./')) return `aura-glass/${e.slice(2)}`;
  return e;
}

export function loadCompiledMappings(dir: string = MAPPINGS_DIR): CompiledMappings {
  const out: CompiledMappings = {
    components: {}, removed: {}, cssVars: {}, deps: [], subpaths: {}, deprecations: [], areaSpecs: {},
  };
  if (!fs.existsSync(dir)) return out;
  for (const file of fs.readdirSync(dir).sort()) {
    if (!file.endsWith('.json') || file === 'deprecations.json') continue;
    const raw = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')) as RawFragment;
    for (const r of raw.renames ?? []) {
      if (r.from === '*') {
        out.subpaths[normEntry(r.fromEntry)] ??= normEntry(r.toEntry);
        continue;
      }
      const c = out.components[r.from] ?? (out.components[r.from] = { compatOnly: false } as CompiledMappings['components'][string]);
      if (c.to === undefined || c.to === r.from) {
        c.to = r.to;
        c.toEntry = normEntry(r.toEntry);
        c.compatOnly = c.compatOnly || r.compatOnly === true;
      } else if (c.to !== r.to) {
        // First non-identity mapping wins; record conflict as compat target.
        c.toEntry = c.toEntry ?? normEntry(r.toEntry);
      }
    }
    for (const row of raw.props ?? []) {
      const c = out.components[row.component] ?? (out.components[row.component] = { compatOnly: false } as CompiledMappings['components'][string]);
      (c.props ??= []).push(row);
    }
    for (const row of raw.removed ?? []) {
      out.removed[row.symbol] ??= row;
      const ne = normEntry(row.entry);
      out.removed[ne] ??= row;
      if (row.entry) out.removed[row.entry] ??= row;
    }
    for (const [k, v] of Object.entries(raw.cssVars ?? {})) out.cssVars[k] ??= v;
    for (const row of raw.deps ?? []) {
      if (!out.deps.some((d) => d.pkg === row.pkg)) out.deps.push(row);
    }
    for (const spec of raw.areaTransforms ?? []) out.areaSpecs[spec.id] = spec.spec;
  }
  const depPath = path.join(dir, 'deprecations.json');
  if (fs.existsSync(depPath)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(depPath, 'utf8')) as unknown;
      const env = parsed as { entries?: Array<Record<string, unknown>> };
      out.deprecations = Array.isArray(parsed) ? parsed : (env.entries ?? []);
    } catch { /* leave empty */ }
  }
  return out;
}
