// Shared emit helpers for scripts/tokens/formats/* (extracted from build.mjs).
import { createRequire } from 'node:module';
import { colorToCss, gamutMapOklch, oklchToSrgb, clampSrgb, srgbToHex } from '../color.mjs';
import { compileSpring } from '../transforms/motion-spring.mjs';

export function die(msg) {
  console.error(`tokens: ${msg}`);
  process.exit(1);
}

export const PRETTIER_MISSING =
  'prettier is required for tokens:build but is not installed — install the pinned prettier devDependency (FIN-C) and retry';

/** Loads prettier or throws (REQ-FIN-01 / MAT-03: no silent unformatted fallback).
 *  `req` is injectable so the missing-prettier path is testable. */
export function loadPrettier(req = createRequire(import.meta.url)) {
  try {
    return req('prettier');
  } catch (cause) {
    throw new Error(`tokens: ${PRETTIER_MISSING}`, { cause });
  }
}

export async function prettierFormat(code, parser, req) {
  // createRequire — dynamic import() fails under jest's CJS runtime.
  const prettier = loadPrettier(req);
  return await prettier.format(code, { parser });
}

export const dim = (v) => `${v.value}${v.unit}`;
const bezier = (v) => `cubic-bezier(${v.join(', ')})`;

export const AXIS_ORDER = ['scheme', 'contrast', 'transparency', 'density', 'preset'];

export function renderValue(rec) {
  const v = rec.value;
  switch (rec.renderType ?? rec.type) {
    case 'color': {
      if (v && typeof v === 'object' && 'light' in v && 'dark' in v)
        return `light-dark(${colorToCss(v.light)}, ${colorToCss(v.dark)})`;
      return colorToCss(v);
    }
    case 'dimension': {
      if (rec.ext?.['ag.calc'] === 'density')
        return `calc(${dim(v)} * var(--_ag-density))`;                        // MAT-015: density-scaled space
      if (v && typeof v === 'object' && 'min' in v && 'max' in v) {
        const { min, max } = v;
        const minVw = v.minVw?.value ?? 320, maxVw = v.maxVw?.value ?? 1440; // MAT-014: fluid clamps over 320-1440
        const preferred = v.preferred ?? `calc(${dim(min)} + (${max.value - min.value}) * ((100vw - ${minVw}px) / ${maxVw - minVw}))`;
        return `clamp(${dim(min)}, ${preferred}, ${dim(max)})`;
      }
      return dim(v);
    }
    case 'duration': return `${v.value}${v.unit}`;
    case 'cubicBezier': return bezier(v);
    case 'motion-spring': return compileSpring(v, rec.name).linear;
    case 'shadow': {
      // DTCG shadow: one layer or an array of layers (REQ-MAT-07 two-layer ambient + key)
      const layer = (s) => `${dim(s.offsetX)} ${dim(s.offsetY)} ${dim(s.blur)} ${s.spread ? dim(s.spread) : '0px'} ${colorToCss(s.color)}`;
      return Array.isArray(v) ? v.map(layer).join(', ') : layer(v);
    }
    case 'number': case 'fontWeight': return String(v);
    case 'fontFamily': return String(v);
    case 'string': return typeof v === 'string' ? v : JSON.stringify(v);
    default: return typeof v === 'string' ? v : JSON.stringify(v);
  }
}


// NOTE: never put `**/` inside a /* */ comment — it terminates the comment (postcss-parse trap).
export const HEADER_CSS = '/* @generated by scripts/tokens/build.mjs. Source: tokens/(recursive) *.tokens.json. Do not edit. */';

export const LAYER_ORDER = '@layer ag.compat, ag.reset, ag.tokens, ag.material, ag.components, ag.a11y;';

/** REQ-MAT-19 item 1 (REQ-FIN-01): an emitted token CSS file starts with
 *  LAYER_ORDER_STATEMENT on line 1; the @generated header comment follows it.
 *  Any copy of the statement already in the body is removed so it appears once. */
export function layerFirst(css) {
  const body = css
    .split('\n')
    .filter((line) => line.trim() !== LAYER_ORDER)
    .join('\n')
    .replace(/^\n+/, '');
  return `${LAYER_ORDER}\n${body.replace(/^(\/\*[\s\S]*?\*\/)\n+/, '$1\n\n')}`;
}

/** shadcn <-> ag var pairs (MAT-070; contract PUBLIC_CSS_VARS.shadcn). */
export const SHADCN_MAP = {
  '--background': '--ag-color-canvas',
  '--foreground': '--ag-color-on-surface',
  '--primary': '--ag-color-accent',
  '--primary-foreground': '--ag-color-on-accent',
  '--muted': '--ag-color-on-surface-muted',
  '--border': '--ag-color-border',
  '--ring': '--ag-color-focus-inner',
  '--radius': '--ag-radius-md',
};
