// Shared emit helpers for scripts/tokens/formats/* (extracted from build.mjs).
import { createRequire } from 'node:module';
import { colorToCss, gamutMapOklch, oklchToSrgb, clampSrgb, srgbToHex } from '../color.mjs';
import { compileSpring } from '../transforms/motion-spring.mjs';

export function die(msg) {
  console.error(`tokens: ${msg}`);
  process.exit(1);
}

export async function prettierFormat(code, parser) {
  // createRequire — dynamic import() fails under jest's CJS runtime.
  let prettier;
  try {
    prettier = createRequire(import.meta.url)('prettier');
  } catch {
    die('prettier is required for tokens:build but is not installed — install the pinned prettier devDependency (FIN-C) and retry');
  }
  return await prettier.format(code, { parser });
}

export const dim = (v) => `${v.value}${v.unit}`;
const bezier = (v) => `cubic-bezier(${v.join(', ')})`;

export const AXIS_ORDER = ['scheme', 'contrast', 'transparency', 'density', 'preset'];

export function renderValue(rec) {
  const v = rec.value;
  switch (rec.renderType ?? rec.type) {
    case 'color': {
      if (v && typeof v === 'object' && 'light' in v && 'dark' in v)
        return `light-dark(${colorToCss(v.light)}, ${colorToCss(v.dark)})`;
      return colorToCss(v);
    }
    case 'dimension': {
      if (rec.ext?.['ag.calc'] === 'density')
        return `calc(${dim(v)} * var(--_ag-density))`;                        // MAT-015: density-scaled space
      if (v && typeof v === 'object' && 'min' in v && 'max' in v) {
        const { min, max } = v;
        const minVw = v.minVw?.value ?? 320, maxVw = v.maxVw?.value ?? 1440; // MAT-014: fluid clamps over 320-1440
        const preferred = v.preferred ?? `calc(${dim(min)} + (${max.value - min.value}) * ((100vw - ${minVw}px) / ${maxVw - minVw}))`;
        return `clamp(${dim(min)}, ${preferred}, ${dim(max)})`;
      }
      return dim(v);
    }
    case 'duration': return `${v.value}${v.unit}`;
    case 'cubicBezier': return bezier(v);
    case 'motion-spring': return compileSpring(v, rec.name).linear;
    case 'shadow': {
      const s = v;
      return `${dim(s.offsetX)} ${dim(s.offsetY)} ${dim(s.blur)} ${s.spread ? dim(s.spread) : '0px'} ${colorToCss(s.color)}`;
    }
    case 'number': case 'fontWeight': return String(v);
    case 'fontFamily': return String(v);
    case 'string': return typeof v === 'string' ? v : JSON.stringify(v);
    default: return typeof v === 'string' ? v : JSON.stringify(v);
  }
}


// NOTE: never put `**/` inside a /* */ comment — it terminates the comment (postcss-parse trap).
export const HEADER_CSS = '/* @generated by scripts/tokens/build.mjs. Source: tokens/(recursive) *.tokens.json. Do not edit. */';

export const LAYER_ORDER = '@layer ag.compat, ag.reset, ag.tokens, ag.material, ag.components, ag.a11y;';

/** shadcn <-> ag var pairs (MAT-070; contract PUBLIC_CSS_VARS.shadcn). */
export const SHADCN_MAP = {
  '--background': '--ag-color-canvas',
  '--foreground': '--ag-color-on-surface',
  '--primary': '--ag-color-accent',
  '--primary-foreground': '--ag-color-on-accent',
  '--muted': '--ag-color-on-surface-muted',
  '--border': '--ag-color-border',
  '--ring': '--ag-color-focus-inner',
  '--radius': '--ag-radius-md',
};
