// AuraGlass 5.0 — compat layer tooling (MAT-004/073/074/075/076).
//
// Reads the frozen 4.1.0 primitives (git show 15b6de6f7:src/styles/tokens.css,
// vendored verbatim at dist/css/compat/legacy-primitives.css) plus the reader set
// (every --glass-*, --aura-*, --persona-*, --glass-theme-* custom property read by
// the 4.x source at that commit) and emits:
//   tokens/legacy/4x-rendered.tokens.json  — private, pre-resolved token records
//   tokens/generated/compat-alias-map.json — reader -> successor map
//   dist/compat/tokens.css                 — @layer ag.compat alias block
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LAYER_ORDER } from './css-layered.mjs';
import { guardColorMix } from '../../build/lib/css.mjs';

export const COMPAT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
export const LEGACY_COMMIT = '15b6de6f7';
export const LEGACY_CSS_PATH = 'src/styles/tokens.css';

/** All custom-property declarations in a CSS file (multi-line aware). */
export function extractLegacyDeclarations(cssText) {
  const out = [];
  const re = /(--(?:glass|aura|persona|glass-theme)[a-zA-Z0-9-]*)\s*:\s*([^;]+);/g;
  let m;
  while ((m = re.exec(cssText))) {
    out.push({ name: m[1], value: m[2].replace(/\s+/g, ' ').trim() });
  }
  return out;
}

// Every --glass-* / --aura-* / --persona-* / --glass-theme-* name read by 4.x source.
export function legacyReaderSet() {
  const files = execSync(
    `git ls-tree -r ${LEGACY_COMMIT} --name-only`,
    { cwd: COMPAT_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
  ).split('\n').filter((f) => /^src\/.*\.(ts|tsx|css)$/.test(f));
  const names = new Set();
  for (const f of files) {
    let src;
    try { src = execSync(`git show ${LEGACY_COMMIT}:${f}`, { cwd: COMPAT_ROOT, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 }); }
    catch { continue; }
    for (const m of src.matchAll(/--(?:glass|aura|persona|glass-theme)[a-zA-Z0-9-]*/g)) names.add(m[0]);
  }
  return [...names].sort();
}

export function legacySourceCss() {
  return execSync(`git show ${LEGACY_COMMIT}:${LEGACY_CSS_PATH}`, { cwd: COMPAT_ROOT, encoding: 'utf8' });
}

/**
 * Successor table: scripts/tokens/compat-successors.json (ordered, first match
 * wins). `to` carries $N capture refs; {group, map} looks a capture up in a
 * table; a missing/null `to` freezes the 4.x value verbatim. `shims` declares
 * compat-emitted shim vars successors may point at.
 */
const SUCCESSOR_DOC = JSON.parse(
  readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'compat-successors.json'), 'utf8')
);
export const SHIM_VARS = SUCCESSOR_DOC.shims;

const resolveTo = (to, m) => {
  if (to == null) return null;
  if (typeof to === 'string') return to.replace(/\$(\d+)/g, (_, i) => m[Number(i)] ?? '');
  if (to.map) return to.map[m[to.group ?? 1]] ?? null;
  return null;
};

export const SUCCESSOR_RULES = SUCCESSOR_DOC.rules.map(
  (r) => [new RegExp(r.match), r.to],
);

/** Name -> { successor: string|null, frozen: string|null, defined: boolean } */
export function buildCompatMap(legacyDecls, readers) {
  const defined = new Map(legacyDecls.map((d) => [d.name, d.value]));
  const names = new Set([...defined.keys(), ...readers]);
  const map = {};
  for (const name of [...names].sort()) {
    let successor = null;
    for (const [re, target] of SUCCESSOR_RULES) {
      const m = re.exec(name);
      if (m) { successor = resolveTo(target, m); break; }
    }
    map[name] = { successor, frozen: defined.get(name) ?? null, defined: defined.has(name) };
  }
  return map;
}

/** tokens/legacy/4x-rendered.tokens.json — private pre-resolved records. */
export function legacyTokensJson(legacyDecls) {
  const legacy = {};
  for (const d of legacyDecls) {
    const key = d.name.replace(/^--/, '');
    legacy[key] = {
      $type: 'string',
      $value: d.value,
      $extensions: { 'ag.legacyVar': d.name, 'ag.legacy': true, 'ag.tier': 'legacy' },
    };
  }
  return { legacy };
}

/** dist/compat/tokens.css — one @layer ag.compat :where(:root) block. */
export function compatCss(map) {
  const lines = [
    '/* @generated by scripts/tokens/build.mjs (scripts/tokens/formats/compat-aliases.mjs). 4.x compat aliases — do not edit. */',
    "@import '../css/tokens.css';",
    '@layer ag.compat {',
    '  :where(:root) {',
  ];
  for (const [shim, target] of Object.entries(SHIM_VARS)) lines.push(`    ${shim}: ${target};`);
  for (const [name, e] of Object.entries(map)) {
    if (!e.defined) { lines.push(`    /* ${name}: never defined in 4.x tokens.css — no output */`); continue; }
    if (e.successor) lines.push(`    ${name}: var(${e.successor});`);
    else lines.push(`    ${name}: ${e.frozen};`);
  }
  lines.push('  }', '}', '');
  return lines.join('\n');
}

/** Emits all compat artifacts; called from runBuild when tokens/legacy/ exists. */
export function emitCompat(write, tokenDir) {
  const css = legacySourceCss();
  const decls = extractLegacyDeclarations(css);
  const readers = legacyReaderSet();
  const map = buildCompatMap(decls, readers);
  write('tokens/generated/compat-alias-map.json', JSON.stringify(map, null, 2) + '\n');
  write('dist/compat/tokens.css', compatCss(map));
  // REQ-PLAT-74: the vendored 4.x primitives are compat content — ship them
  // inside @layer ag.compat so their bare :root block never sits unlayered.
  write('dist/css/compat/legacy-primitives.css', `${LAYER_ORDER}\n\n@layer ag.compat {\n${guardColorMix(css.trim())}\n}\n`);
  return { count: Object.keys(map).length };
}
