// MAT-029: dist/tokens/manifest.json + src/tokens/generated/manifest.ts.
import { colorToCss } from '../color.mjs';
import { compileSpring } from '../transforms/motion-spring.mjs';
import { renderValue } from './_shared.mjs';

/** Emit dist/tokens/manifest.json (MAT-029, contract TokenManifest shape).
 *  `readerCorpus`: emitted-css + hand-written src texts; consumers counts recorded. */
export function emitManifest(records, cells, readerCorpus = []) {
  const MODES_KEYS = new Set(['light', 'dark', 'more', 'tinted', 'solid', 'compact', 'spacious']);
  const countReaders = (v) => {
    const re = new RegExp(`var\\(\\s*${v.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'g');
    let n = 0;
    for (const text of readerCorpus) n += (text.match(re) ?? []).length;
    return n;
  };
  const byToken = new Map();
  for (const c of cells) if (c.cssVar) {
    if (!byToken.has(c.name)) byToken.set(c.name, []);
    byToken.get(c.name).push(c);
  }
  const tokens = [];
  for (const [name, rec] of [...records.entries()].sort()) {
    const cs = byToken.get(name);
    if (!cs || !rec.ext?.['ag.public']) continue;
    const tier = rec.ext['ag.tier'];
    if (tier === 'ref') continue;
    const base = cs.find((c) => !c.axis || c.axisValue === 'light' || c.axisValue === 'regular' || c.axisValue === 'tinted' || c.axisValue === 'aura' || c.axisValue === 'standard') ?? cs[0];
    const modes = {};
    for (const c of cs) {
      if (!c.axisValue || !MODES_KEYS.has(c.axisValue)) continue;
      modes[c.axisValue] = renderValue({ ...c, renderType: c.renderType });
    }
    const typeMap = { 'mode-table': rec.ext?.['ag.valueType'] ?? 'number' };
    tokens.push({
      name,
      cssVar: base.cssVar,
      type: typeMap[rec.type] ?? rec.type,
      tier,
      group: name.split('.')[0],
      modes,
      since: rec.ext['ag.since'] ?? '5.0.0',
      public: true,
      consumers: [{ count: countReaders(base.cssVar) }],
      // resolved default: light scheme, standard contrast, tinted, regular density, aura preset
      value: base.axis === 'scheme' && base.value?.light !== undefined ? colorToCss(base.value.light) : renderValue(base),
    });
    if (rec.type === 'motion-spring') {
      const { durationMs } = compileSpring(base.value ?? resolved.get(name), name);
      tokens.push({
        name,
        cssVar: `${base.cssVar}-duration`,
        type: 'duration',
        tier,
        group: name.split('.')[0],
        modes: {},
        since: rec.ext['ag.since'] ?? '5.0.0',
        public: true,
        consumers: [{ count: countReaders(`${base.cssVar}-duration`) }],
        value: `${durationMs}ms`,
      });
    }
  }
  return JSON.stringify({ version: 1, generatedFrom: 'tokens/**/*.tokens.json', tokens }, null, 1) + '\n';
}

/** Emit src/tokens/generated/manifest.ts — manifest embedded for the aura-glass/tokens map. */
export function emitManifestTs(manifestJson) {
  const body = `/* @generated by scripts/tokens/build.mjs. Do not edit by hand. */\nexport const manifest = ${manifestJson.trim().replace(/\n/g, '\n')} as const;\n`;
  return body;
}

