// MAT-029: dist/tokens/manifest.json + src/tokens/generated/manifest.ts.
import { colorToCss } from '../color.mjs';
import { compileSpring } from '../transforms/motion-spring.mjs';
import { die, renderValue } from './_shared.mjs';

/** REQ-MAT-04 / S-11: the closed `TokenManifestEntry['type']` union of
 *  src/contracts/tokens.ts. tests/tokens/private-ag-namespace.test.ts proves this
 *  list and the contract union are the same set (compile-time) and that every
 *  emitted entry is in it. */
export const MANIFEST_TYPES = Object.freeze([
  'color', 'dimension', 'number', 'duration', 'cubicBezier', 'motion-spring',
  'shadow', 'glass-material', 'fontFamily', 'fontWeight',
]);

/** Map a token record's DTCG/AuraGlass `$type` to the contract union.
 *  `mode-table` (per-axis cells) and `string` (a raw CSS expression such as
 *  `clamp()`/`calc()`/`var()`) are carriers, not value types: they must declare
 *  the value type they resolve to in `$extensions["ag.valueType"]`. Anything that
 *  does not land in the union fails the build instead of shipping. */
export function manifestType(name, rec) {
  const carrier = rec.type === 'mode-table' || rec.type === 'string';
  const type = carrier ? rec.ext?.['ag.valueType'] ?? (rec.type === 'mode-table' ? 'number' : undefined) : rec.type;
  if (!MANIFEST_TYPES.includes(type))
    die(`manifest: ${name} ($type ${rec.type}) maps to '${type}', outside the TokenManifestEntry type union`
      + (carrier ? ' — set $extensions["ag.valueType"]' : ''));
  return type;
}

/** Emit dist/tokens/manifest.json (MAT-029, contract TokenManifest shape).
 *  `readerCorpus`: emitted-css + hand-written src texts; consumers counts recorded. */
export function emitManifest(records, cells, readerCorpus = []) {
  const MODES_KEYS = new Set(['light', 'dark', 'more', 'tinted', 'solid', 'compact', 'spacious']);
  const countReaders = (v) => {
    const re = new RegExp(`var\\(\\s*${v.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'g');
    let n = 0;
    for (const text of readerCorpus) n += (text.match(re) ?? []).length;
    return n;
  };
  const byToken = new Map();
  for (const c of cells) if (c.cssVar) {
    if (!byToken.has(c.name)) byToken.set(c.name, []);
    byToken.get(c.name).push(c);
  }
  const tokens = [];
  for (const [name, rec] of [...records.entries()].sort()) {
    const cs = byToken.get(name);
    if (!cs || !rec.ext?.['ag.public']) continue;
    const tier = rec.ext['ag.tier'];
    if (tier === 'ref') continue;
    const base = cs.find((c) => !c.axis || c.axisValue === 'light' || c.axisValue === 'regular' || c.axisValue === 'tinted' || c.axisValue === 'aura' || c.axisValue === 'standard') ?? cs[0];
    const modes = {};
    for (const c of cs) {
      if (!c.axisValue || !MODES_KEYS.has(c.axisValue)) continue;
      modes[c.axisValue] = renderValue({ ...c, renderType: c.renderType });
    }
    const type = manifestType(name, rec);
    tokens.push({
      name,
      cssVar: base.cssVar,
      type,
      tier,
      group: name.split('.')[0],
      modes,
      since: rec.ext['ag.since'] ?? '5.0.0',
      public: true,
      consumers: [{ count: countReaders(base.cssVar) }],
      // resolved default: light scheme, standard contrast, tinted, regular density, aura preset
      value: base.axis === 'scheme' && base.value?.light !== undefined ? colorToCss(base.value.light) : renderValue(base),
    });
    if (rec.type === 'motion-spring') {
      const { durationMs } = compileSpring(base.value ?? resolved.get(name), name);
      tokens.push({
        name,
        cssVar: `${base.cssVar}-duration`,
        type: 'duration',
        tier,
        group: name.split('.')[0],
        modes: {},
        since: rec.ext['ag.since'] ?? '5.0.0',
        public: true,
        consumers: [{ count: countReaders(`${base.cssVar}-duration`) }],
        value: `${durationMs}ms`,
      });
    }
  }
  return JSON.stringify({ version: 1, generatedFrom: 'tokens/**/*.tokens.json', tokens }, null, 1) + '\n';
}

/** Emit src/tokens/generated/manifest.ts — manifest embedded for the aura-glass/tokens map. */
export function emitManifestTs(manifestJson) {
  const body = `/* @generated by scripts/tokens/build.mjs. Do not edit by hand. */\nexport const manifest = ${manifestJson.trim().replace(/\n/g, '\n')} as const;\n`;
  return body;
}

