// MAT-068: dist/css/tailwind.css — @theme inline map, 6 @utility rules,
// custom variants, shadcn-source scoped dark.
import { die, dim, prettierFormat } from './_shared.mjs';

/** Emit dist/css/tailwind.css — Tailwind v4 bridge (MAT-068).
 *  @theme inline maps every public colour/radius/ease/duration/shadow/type-size/breakpoint;
 *  6 @utility rules whose declarations are byte-equal to the compiled attribute rules. */
export async function emitTailwind(cells, records, resolved) {
  const cssVar = (name) => records.get(name)?.ext?.['ag.cssVar'];
  const theme = ['@theme inline {'];
  const push = (tw, ag) => {
    const v = resolved.get(ag) !== undefined ? cssVar(ag) : null;
    if (!v) die(`tailwind bridge: ${ag} has no public cssVar`);
    theme.push(`  --${tw}: var(${v});`);
  };
  for (const c of ['canvas', 'on-surface', 'on-surface-muted', 'accent', 'on-accent', 'border',
    'focus-inner', 'focus-outer', 'specular', 'danger', 'warning', 'success', 'info'])
    push(`color-${c}`, `sys.color.${c}`);
  for (const r of ['xs', 'sm', 'md', 'lg', 'xl', 'full']) push(`radius-${r}`, `sys.radius.${r}`);
  for (const e of ['standard', 'emphasized', 'emphasized-decelerate', 'accelerate'])
    push(`ease-${e}`, `sys.motion.ease.${e}`);
  for (const d of ['instant', 'instant-exit', 'micro', 'micro-exit', 'small', 'small-exit',
    'medium', 'medium-exit', 'large', 'large-exit', 'ambient'])
    push(`duration-${d}`, `sys.motion.duration.${d}`);
  for (const s of ['thin', 'regular', 'thick']) push(`shadow-${s}`, `material.shadow.${s}`);
  for (const t of ['display', 'title-1', 'title-2', 'title-3', 'body', 'callout', 'caption', 'label', 'mono'])
    push(`text-${t}`, `sys.type.${t}.size`);
  for (const k of ['sm', 'md', 'lg', 'xl']) {
    const v = resolved.get(`sys.breakpoint.${k}`);
    if (!v) die(`tailwind bridge: missing sys.breakpoint.${k}`);
    theme.push(`  --breakpoint-${k}: ${v.value}${v.unit};`);
  }
  theme.push('}');

  // @utility decls byte-equal to the compiled [data-ag-variant][data-ag-thickness] rules
  const spec = resolved.get('material.material');
  const cellDecls = (v, t) => {
    const c = spec.variants[v][t];
    return [
      `--_ag-mat-blur: ${dim(c.blur)};`,
      `--_ag-mat-saturation: ${c.saturation};`,
      `--_ag-mat-grain: ${c.grain};`,
      `--_ag-mat-rim: ${dim(c.rim)};`,
      `--_ag-mat-bezel: ${dim(spec.refraction.bezel[t])};`,
      `--_ag-mat-tint-alpha: ${c.alpha};`,
      `--_ag-mat-shadow: var(--ag-shadow-${t});`,
      `--_ag-surface-alpha: ${c.alpha};`,
      `--ag-surface-fill: oklch(from var(--ag-color-canvas) l c h / var(--_ag-alpha, ${c.alpha}));`,
    ];
  };
  const utilities = [
    ['glass-regular', cellDecls('regular', 'regular')],
    ['glass-clear', cellDecls('clear', 'regular')],
    ['glass-thin', cellDecls('regular', 'thin')],
    ['glass-thick', cellDecls('regular', 'thick')],
    ['content-raised', [`--_ag-mat-tint-alpha: ${spec.content.raised.regular.alpha};`, `--_ag-surface-alpha: ${spec.content.raised.regular.alpha};`]],
    ['content-sunken', [`--_ag-mat-tint-alpha: ${spec.content.sunken.regular.alpha};`, `--_ag-surface-alpha: ${spec.content.sunken.regular.alpha};`]],
  ];
  const parts = [
    '/* @generated by scripts/tokens/build.mjs (tailwind bridge, MAT-068). Do not edit. */',
    '@import "./tokens.css";',
    '', ...theme, '',
    ...utilities.flatMap(([name, decls]) => [`@utility ${name} {`, ...decls.map((d) => `  ${d}`), '}', '']),
    '@custom-variant ag-dark (&:where([data-ag-scheme="dark"], [data-ag-scheme="dark"] *));',
    '@custom-variant ag-tinted (&:where([data-ag-transparency="tinted"], [data-ag-transparency="tinted"] *));',
    '@custom-variant ag-solid (&:where([data-ag-transparency="solid"], [data-ag-transparency="solid"] *));',
    '@custom-variant ag-contrast-more (&:where([data-ag-contrast="more"], [data-ag-contrast="more"] *));',
    '',
  ];
  return prettierFormat(parts.join('\n'), 'css');
}

