/* QUAL (REQ-QUAL-09, -10, -11, -49, -51; REQ-FIN-106; REQ-FIN-05 transfer; FIN-449, FIN-450). Global names and values are frozen (S-20/S-42).
   One decorator: AuraGlassProvider (props from the globals; it applies the OS motion floor, D-11) → Environment
   (backdrop = SCENE_BACKDROP[scene], image /scenes/<file>) → StoryRoot. No parameters.backgrounds, no extra toolbars,
   no direct data-ag-* writes. Stylesheets load through the single loader: `?ag-cert=1` loads only dist/styles.css.
   Information architecture (REQ-QUAL-49): storySort is the REQ order, with each Flagships group's children in
   ComponentMeta.flagship order (generated block; Storybook reads storySort statically, so it must be an inline literal).
   Docs (REQ-QUAL-51): every CSF file gets a docs entry (`autodocs`); the page renders the six generated sections when
   the story subject resolves to a ComponentMeta, Storybook's default composition otherwise. */
import * as React from 'react';
import type { Decorator, Preview } from '@storybook/react-vite';
import { SCENES } from '../src/contracts/testing';
import type { StoryAgParameters } from '../src/contracts/testing';
import { StoryFrame } from './contract/StoryFrame';
import { loadStoryStyles } from './contract/styles';
import { AgDocsPage } from './docs/AgDocsPage';

const item = (v: readonly string[]) => ({ toolbar: { items: [...v], dynamicTitle: true } });
const decorator: Decorator = (Story, ctx) => (
  <StoryFrame storyId={ctx.id} globals={ctx.globals} ag={ctx.parameters.ag as Partial<StoryAgParameters> | undefined}>
    <Story />
  </StoryFrame>
);

const preview: Preview = {
  globalTypes: {
    scheme: { defaultValue: 'light', ...item(['light', 'dark']) },
    contrast: { defaultValue: 'standard', ...item(['standard', 'more']) },
    transparency: { defaultValue: 'glass', ...item(['glass', 'tinted', 'solid']) },
    motion: { defaultValue: 'full', ...item(['full', 'calm', 'none']) },
    density: { defaultValue: 'regular', ...item(['compact', 'regular', 'spacious']) },
    tier: { defaultValue: 'standard', ...item(['lightweight', 'standard', 'enhanced']) },
    scene: { defaultValue: 'photo', ...item(SCENES) },
  },
  tags: ['autodocs'],
  parameters: {
    options: {
      // <ag:story-sort> generated by `node scripts/storybook/lint-titles.mjs --write-story-sort` (REQ-QUAL-49)
      storySort: {
        order: [
          'Start Here',
          'Material Lab',
          'Scenes',
          'Showcases',
          'Flagships',
          [
            'Controls',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
            'Overlays',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
            'App Shell',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
            'Data',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
            'AI',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
            'Media',
            ['Button', 'IconButton', 'ToggleGroup', 'Toolbar', 'SegmentedControl', 'Switch', 'Slider', 'Checkbox', 'CheckboxGroup', 'RadioGroup', 'Field', 'Fieldset', 'Form', 'TextField', 'SearchField', 'Select', 'Combobox', 'NumberField', 'Calendar', 'DateField', 'DatePicker', 'DateRangePicker', 'TimeField', 'Dialog', 'AlertDialog', 'Sheet', 'Popover', 'Tooltip', 'Toast', 'AppShell', 'Menu', 'Sidebar', 'TopBar', 'Tabs', 'TabBar', 'Breadcrumbs', 'Pagination', 'Command', 'CommandPalette', 'ResizablePanels', 'SourceTransition', 'Table', 'TreeView', 'FilterBar', 'StatCard', 'ChartFrame', 'Sparkline', 'ActivityFeed', 'Timeline', 'Thread', 'Message', 'Composer', 'ToolCall', 'Citation', 'SourceList', 'MediaControls', 'NowPlayingBar', 'CarouselRail'],
          ],
          'Core',
          'Foundations',
          'Migration',
        ],
      },
      // </ag:story-sort>
    },
    docs: { page: AgDocsPage },
  },
  loaders: [async () => { await loadStoryStyles(); return {}; }],
  decorators: [decorator],
};
export default preview;
