/* fragments/deprecations/cmp.ts — CMP owns this file on both branches (§3.4). */
import type { DeprecationFragment } from '../../src/contracts/fragments';

export default [
  { id: 'DEP-C0001', kind: 'export', status: 'active', entry: '.', symbol: 'GlassButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0001', compat: 'GlassButton' },
  { id: 'DEP-C0003', kind: 'export', status: 'active', entry: '.', symbol: 'EnhancedGlassButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'EnhancedGlassButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0003', compat: 'EnhancedGlassButton' },
  { id: 'DEP-C0004', kind: 'export', status: 'active', entry: '.', symbol: 'RippleButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'RippleButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0004', compat: 'RippleButton' },
  { id: 'DEP-C0005', kind: 'export', status: 'active', entry: '.', symbol: 'GlassLinkButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassLinkButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0005', compat: 'GlassLinkButton' },
  { id: 'DEP-C0006', kind: 'export', status: 'active', entry: '.', symbol: 'ToggleButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'ToggleGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'ToggleButton\' is renamed to \'ToggleGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0006', compat: 'ToggleButton' },
  { id: 'DEP-C0007', kind: 'export', status: 'active', entry: '.', symbol: 'MagneticButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'MagneticButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0007', compat: 'MagneticButton' },
  { id: 'DEP-C0008', kind: 'export', status: 'active', entry: '.', symbol: 'GlassFab', since: '4.3.0', removeIn: '5.0.0', replacement: 'IconButton', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassFab\' is renamed to \'IconButton\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0008', compat: 'GlassFab' },
  { id: 'DEP-C0009', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassButtonStyle', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'partial', breaking: 'B5', message: '\'LiquidGlassButtonStyle\' style presets are gone; Button variants cover them. Compat export warns on first read.', doc: '#dep-dep-c0009', compat: 'LiquidGlassButtonStyle' },
  { id: 'DEP-C0010', kind: 'export', status: 'active', entry: '.', symbol: 'GlassIconButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'IconButton', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassIconButton\' is renamed to \'IconButton\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0010', compat: 'GlassIconButton' },
  { id: 'DEP-C0011', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassControlGroup', since: '4.3.0', removeIn: '5.0.0', replacement: 'ButtonGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassControlGroup\' is renamed to \'ButtonGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0011', compat: 'LiquidGlassControlGroup' },
  { id: 'DEP-C0012', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassToolbar', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toolbar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassToolbar\' is renamed to \'Toolbar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0012', compat: 'LiquidGlassToolbar' },
  { id: 'DEP-C0013', kind: 'export', status: 'active', entry: '.', symbol: 'GlassToolbar', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toolbar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassToolbar\' is renamed to \'Toolbar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0013', compat: 'GlassToolbar' },
  { id: 'DEP-C0014', kind: 'export', status: 'active', entry: '.', symbol: 'ToggleButtonGroup', since: '4.3.0', removeIn: '5.0.0', replacement: 'ToggleGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'ToggleButtonGroup\' is renamed to \'ToggleGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0014', compat: 'ToggleButtonGroup' },
  { id: 'DEP-C0015', kind: 'export', status: 'active', entry: '.', symbol: 'GlassToggle', since: '4.3.0', removeIn: '5.0.0', replacement: 'ToggleGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassToggle\' is renamed to \'ToggleGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0015', compat: 'GlassToggle' },
  { id: 'DEP-C0016', kind: 'export', status: 'active', entry: '.', symbol: 'GlassCommandBar', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toolbar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassCommandBar\' is renamed to \'Toolbar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0016', compat: 'GlassCommandBar' },
  { id: 'DEP-C0017', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassMapControls', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toolbar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassMapControls\' is renamed to \'Toolbar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0017', compat: 'LiquidGlassMapControls' },
  { id: 'DEP-C0018', kind: 'export', status: 'active', entry: '.', symbol: 'GlassActionBar', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toolbar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassActionBar\' is renamed to \'Toolbar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0018', compat: 'GlassActionBar' },
  { id: 'DEP-C0019', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSegmentedControl', since: '4.3.0', removeIn: '5.0.0', replacement: 'SegmentedControl', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSegmentedControl\' is renamed to \'SegmentedControl\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0019', compat: 'GlassSegmentedControl' },
  { id: 'DEP-C0020', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassSegmentedControl', since: '4.3.0', removeIn: '5.0.0', replacement: 'SegmentedControl', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassSegmentedControl\' is renamed to \'SegmentedControl\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0020', compat: 'LiquidGlassSegmentedControl' },
  { id: 'DEP-C0021', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSwitch', since: '4.3.0', removeIn: '5.0.0', replacement: 'Switch', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSwitch\' is renamed to \'Switch\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0021', compat: 'GlassSwitch' },
  { id: 'DEP-C0022', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSlider', since: '4.3.0', removeIn: '5.0.0', replacement: 'Slider', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSlider\' is renamed to \'Slider\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0022', compat: 'GlassSlider' },
  { id: 'DEP-C0023', kind: 'export', status: 'active', entry: '.', symbol: 'GlassCheckbox', since: '4.3.0', removeIn: '5.0.0', replacement: 'Checkbox', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassCheckbox\' is renamed to \'Checkbox\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0023', compat: 'GlassCheckbox' },
  { id: 'DEP-C0024', kind: 'export', status: 'active', entry: '.', symbol: 'GlassCheckboxGroup', since: '4.3.0', removeIn: '5.0.0', replacement: 'CheckboxGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassCheckboxGroup\' is renamed to \'CheckboxGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0024', compat: 'GlassCheckboxGroup' },
  { id: 'DEP-C0025', kind: 'export', status: 'active', entry: '.', symbol: 'GlassRadioGroup', since: '4.3.0', removeIn: '5.0.0', replacement: 'RadioGroup', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassRadioGroup\' is renamed to \'RadioGroup\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0025', compat: 'GlassRadioGroup' },
  { id: 'DEP-C0026', kind: 'export', status: 'active', entry: '.', symbol: 'GlassInput', since: '4.3.0', removeIn: '5.0.0', replacement: 'TextField', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassInput\' is renamed to \'TextField\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0026', compat: 'GlassInput' },
  { id: 'DEP-C0027', kind: 'export', status: 'active', entry: '.', symbol: 'GlassTextarea', since: '4.3.0', removeIn: '5.0.0', replacement: 'TextField', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassTextarea\' is renamed to \'TextField\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0027', compat: 'GlassTextarea' },
  { id: 'DEP-C0028', kind: 'export', status: 'active', entry: '.', symbol: 'GlassFieldGroup', since: '4.3.0', removeIn: '5.0.0', replacement: 'Fieldset', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassFieldGroup\' is renamed to \'Fieldset\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0028', compat: 'GlassFieldGroup' },
  { id: 'DEP-C0029', kind: 'export', status: 'active', entry: '.', symbol: 'GlassValidationMessage', since: '4.3.0', removeIn: '5.0.0', replacement: 'Field.Error', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassValidationMessage\' is renamed to \'Field.Error\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0029', compat: 'GlassValidationMessage' },
  { id: 'DEP-C0030', kind: 'export', status: 'active', entry: '.', symbol: 'GlassFormField', since: '4.3.0', removeIn: '5.0.0', replacement: 'Field', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassFormField\' is renamed to \'Field\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0030', compat: 'GlassFormField' },
  { id: 'DEP-C0031', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassSearchField', since: '4.3.0', removeIn: '5.0.0', replacement: 'SearchField', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassSearchField\' is renamed to \'SearchField\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0031', compat: 'LiquidGlassSearchField' },
  { id: 'DEP-C0032', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSearchField', since: '4.3.0', removeIn: '5.0.0', replacement: 'SearchField', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSearchField\' is renamed to \'SearchField\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0032', compat: 'GlassSearchField' },
  { id: 'DEP-C0033', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSearchInterface', since: '4.3.0', removeIn: '5.0.0', replacement: 'SearchField', codemod: 'canonical-names', automation: 'partial', breaking: 'B5', message: '\'GlassSearchInterface\' results pane has no 5.0 equivalent; the input maps to SearchField, the pane to Combobox/registry faceted-search.', doc: '#dep-dep-c0033', compat: 'GlassSearchInterface' },
  { id: 'DEP-C0034', kind: 'export', status: 'active', entry: '.', symbol: 'GlassIntelligentSearch', since: '4.3.0', removeIn: '5.0.0', replacement: 'SearchField', codemod: 'canonical-names', automation: 'partial', breaking: 'B5', message: '\'GlassIntelligentSearch\' AI features were 4.x speculation; the input maps to SearchField.', doc: '#dep-dep-c0034', compat: 'GlassIntelligentSearch' },
  { id: 'DEP-C0035', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSelect', since: '4.3.0', removeIn: '5.0.0', replacement: 'Select', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSelect\' is renamed to \'Select\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0035', compat: 'GlassSelect' },
  { id: 'DEP-C0036', kind: 'export', status: 'active', entry: '.', symbol: 'GlassSelectCompound', since: '4.3.0', removeIn: '5.0.0', replacement: 'Select', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassSelectCompound\' is renamed to \'Select\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0036', compat: 'GlassSelectCompound' },
  { id: 'DEP-C0037', kind: 'export', status: 'active', entry: '.', symbol: 'GlassCombobox', since: '4.3.0', removeIn: '5.0.0', replacement: 'Combobox', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassCombobox\' is renamed to \'Combobox\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0037', compat: 'GlassCombobox' },
  { id: 'DEP-C0038', kind: 'export', status: 'active', entry: '.', symbol: 'GlassMultiSelect', since: '4.3.0', removeIn: '5.0.0', replacement: 'Combobox', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassMultiSelect\' is renamed to \'Combobox\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0038', compat: 'GlassMultiSelect' },
  { id: 'DEP-C0039', kind: 'export', status: 'active', entry: '.', symbol: 'GlassTagInput', since: '4.3.0', removeIn: '5.0.0', replacement: 'Combobox', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassTagInput\' is renamed to \'Combobox\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0039', compat: 'GlassTagInput' },
  { id: 'DEP-C0040', kind: 'export', status: 'active', entry: '.', symbol: 'GlassMentionList', since: '4.3.0', removeIn: '5.0.0', replacement: 'Combobox', codemod: 'canonical-names', automation: 'partial', breaking: 'B5', message: '\'GlassMentionList\' trigger detection is consumer code in 5.0; the list maps to Combobox.', doc: '#dep-dep-c0040', compat: 'GlassMentionList' },
  { id: 'DEP-C0041', kind: 'export', status: 'active', entry: '.', symbol: 'GlassMagneticButton', since: '4.3.0', removeIn: '5.0.0', replacement: 'Button', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassMagneticButton\' is renamed to \'Button\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0041', compat: 'MagneticButton' },
  { id: 'DEP-C0101', kind: 'export', status: 'active', entry: '.', symbol: 'GlassModal', since: '4.3.0', removeIn: '5.0.0', replacement: 'Dialog', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassModal\' is renamed to \'Dialog\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0101', compat: 'GlassModal' },
  { id: 'DEP-C0102', kind: 'export', status: 'active', entry: '.', symbol: 'GlassDialog', since: '4.3.0', removeIn: '5.0.0', replacement: 'Dialog', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassDialog\' is renamed to \'Dialog\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0102', compat: 'GlassDialog' },
  { id: 'DEP-C0103', kind: 'export', status: 'active', entry: '.', symbol: 'GlassDrawer', since: '4.3.0', removeIn: '5.0.0', replacement: 'Sheet', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassDrawer\' is renamed to \'Sheet\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0103', compat: 'GlassDrawer' },
  { id: 'DEP-C0104', kind: 'export', status: 'active', entry: '.', symbol: 'GlassBottomSheet', since: '4.3.0', removeIn: '5.0.0', replacement: 'Sheet', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassBottomSheet\' is renamed to \'Sheet\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0104', compat: 'GlassBottomSheet' },
  { id: 'DEP-C0105', kind: 'export', status: 'active', entry: '.', symbol: 'GlassActionSheet', since: '4.3.0', removeIn: '5.0.0', replacement: 'Sheet', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassActionSheet\' is renamed to \'Sheet\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0105', compat: 'GlassActionSheet' },
  { id: 'DEP-C0106', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassAdaptiveSheet', since: '4.3.0', removeIn: '5.0.0', replacement: 'Sheet', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassAdaptiveSheet\' is renamed to \'Sheet\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0106', compat: 'LiquidGlassAdaptiveSheet' },
  { id: 'DEP-C0107', kind: 'export', status: 'active', entry: '.', symbol: 'GlassPopover', since: '4.3.0', removeIn: '5.0.0', replacement: 'Popover', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassPopover\' is renamed to \'Popover\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0107', compat: 'GlassPopover' },
  { id: 'DEP-C0108', kind: 'export', status: 'active', entry: '.', symbol: 'GlassHoverCard', since: '4.3.0', removeIn: '5.0.0', replacement: 'Popover', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassHoverCard\' is renamed to \'Popover\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0108', compat: 'GlassHoverCard' },
  { id: 'DEP-C0109', kind: 'export', status: 'active', entry: '.', symbol: 'GlassTooltip', since: '4.3.0', removeIn: '5.0.0', replacement: 'Tooltip', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassTooltip\' is renamed to \'Tooltip\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0109', compat: 'GlassTooltip' },
  { id: 'DEP-C0110', kind: 'export', status: 'active', entry: '.', symbol: 'Positioner', since: '4.3.0', removeIn: '5.0.0', replacement: 'Popover.Positioner', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'Positioner\' is renamed to \'Popover.Positioner\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0110', compat: 'Positioner' },
  { id: 'DEP-C0111', kind: 'export', status: 'active', entry: '.', symbol: 'GlassDropdownMenu', since: '4.3.0', removeIn: '5.0.0', replacement: 'Menu', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassDropdownMenu\' is renamed to \'Menu\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0111', compat: 'GlassDropdownMenu' },
  { id: 'DEP-C0112', kind: 'export', status: 'active', entry: '.', symbol: 'GlassContextMenu', since: '4.3.0', removeIn: '5.0.0', replacement: 'ContextMenu', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassContextMenu\' is renamed to \'ContextMenu\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0112', compat: 'GlassContextMenu' },
  { id: 'DEP-C0113', kind: 'export', status: 'active', entry: '.', symbol: 'GlassMenubar', since: '4.3.0', removeIn: '5.0.0', replacement: 'Menubar', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassMenubar\' is renamed to \'Menubar\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0113', compat: 'GlassMenubar' },
  { id: 'DEP-C0114', kind: 'export', status: 'active', entry: '.', symbol: 'LiquidGlassPopoverMenu', since: '4.3.0', removeIn: '5.0.0', replacement: 'Menu', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'LiquidGlassPopoverMenu\' is renamed to \'Menu\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0114', compat: 'LiquidGlassPopoverMenu' },
  { id: 'DEP-C0115', kind: 'export', status: 'active', entry: '.', symbol: 'GlassToast', since: '4.3.0', removeIn: '5.0.0', replacement: 'useToast', codemod: 'canonical-names', automation: 'partial', breaking: 'B5', message: '\'GlassToast\' declarative mounts map to useToast().add; keep markup only for bespoke layouts.', doc: '#dep-dep-c0115', compat: 'GlassToast' },
  { id: 'DEP-C0116', kind: 'export', status: 'active', entry: '.', symbol: 'GlassToastProvider', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toast.Provider', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassToastProvider\' is renamed to \'Toast.Provider\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0116', compat: 'GlassToastProvider' },
  { id: 'DEP-C0117', kind: 'export', status: 'active', entry: '.', symbol: 'GlassToastViewport', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toast.Viewport', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassToastViewport\' is renamed to \'Toast.Viewport\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0117', compat: 'GlassToastViewport' },
  { id: 'DEP-C0118', kind: 'export', status: 'active', entry: '.', symbol: 'useToast', since: '4.3.0', removeIn: '5.0.0', replacement: 'useToast', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '4.x useToast returns {toast,addToast,dismiss,removeToast}; 5.0 useToast returns {add,close,update,promise,history,toasts}.', doc: '#dep-dep-c0118', compat: 'useToast' },
  { id: 'DEP-C0119', kind: 'export', status: 'active', entry: '.', symbol: 'GlassNotificationCenter', since: '4.3.0', removeIn: '5.0.0', replacement: 'Popover', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassNotificationCenter\' is renamed to \'Popover\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0119', compat: 'GlassNotificationCenter' },
  { id: 'DEP-C0120', kind: 'export', status: 'active', entry: '.', symbol: 'GlassPositioner', since: '4.3.0', removeIn: '5.0.0', replacement: 'Popover.Positioner', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassPositioner\' is renamed to \'Popover.Positioner\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0120', compat: 'GlassPositioner' },
  { id: 'DEP-C0121', kind: 'export', status: 'active', entry: '.', symbol: 'GlassNotificationProvider', since: '4.3.0', removeIn: '5.0.0', replacement: 'Toast.Provider', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'GlassNotificationProvider\' is renamed to \'Toast.Provider\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0121', compat: null },
  { id: 'DEP-C0122', kind: 'export', status: 'active', entry: '.', symbol: 'useNotifications', since: '4.3.0', removeIn: '5.0.0', replacement: 'useToast', codemod: 'canonical-names', automation: 'full', breaking: 'B5', message: '\'useNotifications\' is renamed to \'useToast\' in aura-glass 5.0; run `aura-glass migrate 5` (canonical-names).', doc: '#dep-dep-c0122', compat: 'useNotifications' },
  { id: 'DEP-C0123', kind: 'subpath', status: 'active', entry: './overlays', symbol: '*', since: '4.3.0', removeIn: '5.0.0', replacement: '.', codemod: 'imports-subpaths', automation: 'full', breaking: 'B4', message: 'The \'aura-glass/overlays\' subpath is gone; overlay exports live on the root entry.', doc: '#dep-dep-c0123' },
  { id: 'DEP-C0130', kind: 'export', status: 'active', entry: '.', symbol: 'GlassAchievementNotifications', since: '4.3.0', removeIn: '5.0.0', replacement: 'useToast', codemod: 'removed', automation: 'full', breaking: 'B3', message: '\'GlassAchievementNotifications\' is removed; feed achievements through useToast().add.', doc: '#dep-dep-c0130' },
  { id: 'DEP-C0131', kind: 'export', status: 'active', entry: '.', symbol: 'GlassTransitions.GlassModal', since: '4.3.0', removeIn: '5.0.0', replacement: 'Dialog', codemod: 'removed', automation: 'full', breaking: 'B3', message: '\'GlassTransitions.GlassModal\' is removed; use Dialog (transitions are built in).', doc: '#dep-dep-c0131' },
  { id: 'DEP-C0132', kind: 'export', status: 'active', entry: '.', symbol: 'MobileGlassBottomSheet', since: '4.3.0', removeIn: '5.0.0', replacement: 'Sheet', codemod: 'removed', automation: 'full', breaking: 'B3', message: '\'MobileGlassBottomSheet\' is removed; use Sheet with side=\'bottom\'.', doc: '#dep-dep-c0132' },
  { id: 'DEP-C0200', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.predictive', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'predictive\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0200' },
  { id: 'DEP-C0201', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.eyeTracking', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'eyeTracking\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0201' },
  { id: 'DEP-C0202', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.adaptive', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'adaptive\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0202' },
  { id: 'DEP-C0203', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.spatialAudio', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'spatialAudio\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0203' },
  { id: 'DEP-C0204', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.trackAchievements', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'trackAchievements\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0204' },
  { id: 'DEP-C0205', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.usageContext', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'usageContext\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0205' },
  { id: 'DEP-C0206', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.glassVariant', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'glassVariant\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0206' },
  { id: 'DEP-C0207', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassButton.materialProps', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassButton\' prop \'materialProps\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0207' },
  { id: 'DEP-C0208', kind: 'prop-value', status: 'active', entry: '.', symbol: 'GlassButton.material', since: '4.3.0', removeIn: '5.0.0', replacement: '\'prominent\'', codemod: 'prop-grammar', automation: 'partial', breaking: 'B11', message: 'GlassButton material=\'liquid\' maps to variant=\'prominent\' in 5.0 (the default material changed).', doc: '#dep-dep-c0208' },
  { id: 'DEP-C0209', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassSelect.options', since: '4.2.0', removeIn: '5.0.0', replacement: '\'items\'', codemod: 'prop-grammar', automation: 'mostly', breaking: 'B6', message: 'GlassSelect \'options\' maps to Select \'items\' in 5.0.', doc: '#dep-dep-c0209' },
  { id: 'DEP-C0210', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.backdropBlur', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'backdropBlur\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0210' },
  { id: 'DEP-C0211', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.material', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'material\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0211' },
  { id: 'DEP-C0212', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.materialProps', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'materialProps\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0212' },
  { id: 'DEP-C0213', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.consciousness', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'consciousness\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0213' },
  { id: 'DEP-C0214', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.predictive', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'predictive\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0214' },
  { id: 'DEP-C0215', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.adaptive', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'adaptive\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0215' },
  { id: 'DEP-C0216', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.eyeTracking', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'eyeTracking\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0216' },
  { id: 'DEP-C0217', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.trackAchievements', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'trackAchievements\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0217' },
  { id: 'DEP-C0218', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.animation', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'animation\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0218' },
  { id: 'DEP-C0219', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.compact', since: '4.2.0', removeIn: '5.0.0', replacement: null, codemod: 'dead-optical-props', automation: 'full', breaking: 'B6', message: '\'GlassModal\' prop \'compact\' has no 5.0 equivalent and is removed.', doc: '#dep-dep-c0219' },
  { id: 'DEP-C0220', kind: 'prop', status: 'active', entry: '.', symbol: 'GlassModal.isContained', since: '4.2.0', removeIn: '5.0.0', replacement: 'Surface', codemod: null, automation: 'manual', breaking: 'B6', message: 'GlassModal \'isContained\' has no direct 5.0 prop; compose with Surface and set data-ag-transparency.', doc: '#dep-dep-c0220' },
  {
    id: 'DEP-C0221',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'Button',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'Button is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0221',
    compat: 'Button',
  },
  {
    id: 'DEP-C0222',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuArrow',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuArrow is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0222',
    compat: 'GlassDropdownMenuArrow',
  },
  {
    id: 'DEP-C0223',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuCheckboxItem',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuCheckboxItem is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0223',
    compat: 'GlassDropdownMenuCheckboxItem',
  },
  {
    id: 'DEP-C0224',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuContent',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuContent is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0224',
    compat: 'GlassDropdownMenuContent',
  },
  {
    id: 'DEP-C0225',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuGroup',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuGroup is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0225',
    compat: 'GlassDropdownMenuGroup',
  },
  {
    id: 'DEP-C0226',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuItem',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuItem is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0226',
    compat: 'GlassDropdownMenuItem',
  },
  {
    id: 'DEP-C0227',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuLabel',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuLabel is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0227',
    compat: 'GlassDropdownMenuLabel',
  },
  {
    id: 'DEP-C0228',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuPortal',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuPortal is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0228',
    compat: 'GlassDropdownMenuPortal',
  },
  {
    id: 'DEP-C0229',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuRadioGroup',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuRadioGroup is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0229',
    compat: 'GlassDropdownMenuRadioGroup',
  },
  {
    id: 'DEP-C0230',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuRadioItem',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuRadioItem is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0230',
    compat: 'GlassDropdownMenuRadioItem',
  },
  {
    id: 'DEP-C0231',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuRoot',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuRoot is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0231',
    compat: 'GlassDropdownMenuRoot',
  },
  {
    id: 'DEP-C0232',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuSeparator',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuSeparator is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0232',
    compat: 'GlassDropdownMenuSeparator',
  },
  {
    id: 'DEP-C0233',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuSub',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuSub is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0233',
    compat: 'GlassDropdownMenuSub',
  },
  {
    id: 'DEP-C0234',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuSubTrigger',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuSubTrigger is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0234',
    compat: 'GlassDropdownMenuSubTrigger',
  },
  {
    id: 'DEP-C0235',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDropdownMenuTrigger',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassDropdownMenuTrigger is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0235',
    compat: 'GlassDropdownMenuTrigger',
  },
  {
    id: 'DEP-C0236',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectContent',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectContent is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0236',
    compat: 'GlassSelectContent',
  },
  {
    id: 'DEP-C0237',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectGroup',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectGroup is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0237',
    compat: 'GlassSelectGroup',
  },
  {
    id: 'DEP-C0238',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectItem',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectItem is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0238',
    compat: 'GlassSelectItem',
  },
  {
    id: 'DEP-C0239',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectLabel',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectLabel is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0239',
    compat: 'GlassSelectLabel',
  },
  {
    id: 'DEP-C0240',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectRoot',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectRoot is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0240',
    compat: 'GlassSelectRoot',
  },
  {
    id: 'DEP-C0241',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectScrollDown',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectScrollDown is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0241',
    compat: 'GlassSelectScrollDown',
  },
  {
    id: 'DEP-C0242',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectScrollUp',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectScrollUp is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0242',
    compat: 'GlassSelectScrollUp',
  },
  {
    id: 'DEP-C0243',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectSeparator',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectSeparator is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0243',
    compat: 'GlassSelectSeparator',
  },
  {
    id: 'DEP-C0244',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectTrigger',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectTrigger is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0244',
    compat: 'GlassSelectTrigger',
  },
  {
    id: 'DEP-C0245',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSelectValue',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassSelectValue is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0245',
    compat: 'GlassSelectValue',
  },
  {
    id: 'DEP-C0246',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'renderToolbarItems',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'renderToolbarItems is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0246',
    compat: 'renderToolbarItems',
  },
  {
    id: 'DEP-C0247',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'splitPlacement',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'splitPlacement is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0247',
    compat: 'splitPlacement',
  },
  {
    id: 'DEP-C0248',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'toSide',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'toSide is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0248',
    compat: 'toSide',
  },
  {
    id: 'DEP-C0249',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'toastPosition',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'toastPosition is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0249',
    compat: 'toastPosition',
  },
  {
    id: 'DEP-C0250',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'toastType',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'toastType is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0250',
    compat: 'toastType',
  },
  {
    id: 'DEP-C0251',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGlassModalMapping',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'useGlassModalMapping is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-c0251',
    compat: 'useGlassModalMapping',
  },
] satisfies DeprecationFragment;
