/* fragments/deprecations/mat.ts — MAT owns this file on both branches (§3.4). */
import type { DeprecationFragment } from '../../src/contracts/fragments';
const compat5x = [
  {
    id: 'DEP-M1000',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCore',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'GlassCore is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1000',
    compat: 'GlassCore',
  },
  {
    id: 'DEP-M1001',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassConcentricFrame',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'LiquidGlassConcentricFrame is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1001',
    compat: 'LiquidGlassConcentricFrame',
  },
  {
    id: 'DEP-M1002',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassEffectGroup',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'LiquidGlassEffectGroup is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1002',
    compat: 'LiquidGlassEffectGroup',
  },
  {
    id: 'DEP-M1003',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassLayerProvider',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'LiquidGlassLayerProvider is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1003',
    compat: 'LiquidGlassLayerProvider',
  },
  {
    id: 'DEP-M1004',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassMaterial',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'LiquidGlassMaterial is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1004',
    compat: 'LiquidGlassMaterial',
  },
  {
    id: 'DEP-M1005',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassScrollEdge',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'LiquidGlassScrollEdge is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1005',
    compat: 'LiquidGlassScrollEdge',
  },
  {
    id: 'DEP-M1006',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OptimizedGlass',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'OptimizedGlass is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1006',
    compat: 'OptimizedGlass',
  },
  {
    id: 'DEP-M1007',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OptimizedGlassAdvanced',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'the 5.0 equivalent',
    codemod: null,
    automation: 'none',
    breaking: 'B4',
    message: 'OptimizedGlassAdvanced is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0.',
    doc: '#dep-m1007',
    compat: 'OptimizedGlassAdvanced',
  },
] as const;

export default [...compat5x] satisfies DeprecationFragment;
