// deprecations fragment for MAT (contract S-38). Lane blocks are owned by MAT
// lanes 2a-T..2e-B; edit only your own block. Id ranges: 2a-T DEP-M0001..M0199,
// 2b-M DEP-M0200..M0399, 2c-V DEP-M0400..M0599, 2d-P DEP-M0600..M0799,
// 2e-B DEP-M0800..M0999. This file lives on release/4.x; the daily
// PLAT fragment sync mirrors it to next where it is read-only (§2.4.2).
//
// Row coverage (PRD-2 §9/§10, mapped to MAT.json):
//   MAT-338 4.2.0 token subpath/dist/type rows — the four subpaths
//     ./tokens/{json,tailwind,manifest,css} are PLAT's rows per contract §4.7
//     (fragments/deprecations/plat.ts, PLAT-161); MAT carries ./tokens/keyframes,
//     the two dist preset artifacts and the type-only getPersona/getPersonaModeTokens.
//   MAT-351/352 4.2.0 §9 material/core export + subpath + recipe rows; the
//     warn-once code edits on 4.x source are PLAT-executed per §2.4.1.
//   MAT-353 4.2.0 storybook-utility-shim.css css-global row (doctor --v5, DX-037).
//   MAT-364 4.2.0 §9/§10 motion rows (AC-MOT-18): Motion aliases, controller/
//     transition/engine families, physics/Galileo/orchestration public hooks,
//     preference providers/hooks, removed props, motion constants/vars/peer.
//   MAT-373 4.2.0 §9 accessibility rows (ContrastGuard/GlassA11y/focus/provider/
//     announcer/focus-trap families); its CSS hooks land at 4.3 per §9 row 18.
//   MAT-339 4.3.0 css-var/data-attr/persona/theme rows incl. createBrandGlassTheme
//     + createGlassThemeCssVars (MAT-066/067 warn-once edits are PLAT-executed).
//   MAT-340's warn-once list is covered by the rows below; the code edits on
//     4.x src/theme/* are PLAT-owned per §2.4.1.
// All rows are `status: 'planned'` until the 4.2/4.3 minors ship
// (verify-deprecations rejects 'active' while since > line version).
import type { DeprecationFragment } from '../../src/contracts/fragments';

// --- lane 2a-T begin ---
const t = [] as const;
// --- lane 2a-T end ---

// --- lane 2b-M begin ---
const m = [] as const;
// --- lane 2b-M end ---

// --- lane 2c-V begin ---
const v = [] as const;
// --- lane 2c-V end ---

// --- lane 2d-P begin ---
const p = [] as const;
// --- lane 2d-P end ---

// --- lane 2e-B begin ---
const b = [
  // ---- MAT-338 · 4.2 · token subpaths, dist presets, type-only persona APIs ----
  {
    id: 'DEP-M0800',
    kind: 'subpath',
    status: 'planned',
    entry: './tokens/keyframes',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/tokens.css (keyframes ship inside the 5.x tokens stylesheet)',
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      'aura-glass/tokens/keyframes is removed in 5.0; import aura-glass/tokens.css — the motion keyframes are emitted inside it.',
    doc: '#dep-m0800',
  },
  {
    id: 'DEP-M0801',
    kind: 'asset',
    status: 'planned',
    entry: './tokens/tailwind',
    symbol: 'dist/tokens/tailwind.theme.mjs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/tokens.css (Tailwind theme output of the 5.x token compiler)',
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      'the Tailwind v3 preset module (dist/tokens/tailwind.theme.mjs) is removed in 5.0; consume aura-glass/tokens.css instead.',
    doc: '#dep-m0801',
  },
  {
    id: 'DEP-M0802',
    kind: 'asset',
    status: 'planned',
    entry: './tokens',
    symbol: 'dist/tokens/unocss.preset.ts',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/tokens.css (UnoCSS users map the emitted --ag-* variables)',
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      'the UnoCSS preset module (dist/tokens/unocss.preset.ts) is removed in 5.0; consume aura-glass/tokens.css instead.',
    doc: '#dep-m0802',
  },
  {
    id: 'DEP-M0803',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'getPersona',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'presets (aura-glass/theme) — personas are replaced by the 5.x presets table',
    codemod: null,
    automation: 'manual',
    breaking: 'B3',
    message:
      'getPersona is removed in 5.0; persona lookup is replaced by the presets table on aura-glass/theme.',
    doc: '#dep-m0803',
  },
  {
    id: 'DEP-M0804',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'getPersonaModeTokens',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'createBrandTheme + presets (aura-glass/theme)',
    codemod: null,
    automation: 'manual',
    breaking: 'B3',
    message:
      'getPersonaModeTokens is removed in 5.0; derive themed tokens from createBrandTheme/presets on aura-glass/theme.',
    doc: '#dep-m0804',
  },
  // ---- MAT-351/352 · 4.2 · §9 glass core, liquid-glass and material rows ----
  {
    id: 'DEP-M0805',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OptimizedGlass',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'OptimizedGlass is deprecated; use Surface (codemod: canonical-names). Dead optical props are stripped by dead-optical-props.',
    doc: '#dep-m0805',
    compat: 'OptimizedGlass',
  },
  {
    id: 'DEP-M0806',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OptimizedGlassCore',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'OptimizedGlassCore is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0806',
    compat: 'OptimizedGlassCore',
  },
  {
    id: 'DEP-M0807',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvanced',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'GlassAdvanced is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0807',
    compat: 'GlassAdvanced',
  },
  {
    id: 'DEP-M0808',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OptimizedGlassAdvanced',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'OptimizedGlassAdvanced is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0808',
    compat: 'OptimizedGlassAdvanced',
  },
  {
    id: 'DEP-M0809',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassMaterial',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'LiquidGlassMaterial is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0809',
    compat: 'LiquidGlassMaterial',
  },
  {
    id: 'DEP-M0810',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'GlassCore',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'GlassCore is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0810',
    compat: 'GlassCore',
  },
  {
    id: 'DEP-M0811',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'GlassPrimitive',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'GlassPrimitive is deprecated; use Surface (codemod: canonical-names).',
    doc: '#dep-m0811',
    compat: 'GlassPrimitive',
  },
  {
    id: 'DEP-M0812',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassEffectGroup',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SurfaceGroup',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'LiquidGlassEffectGroup is deprecated; use SurfaceGroup (codemod: canonical-names).',
    doc: '#dep-m0812',
    compat: 'LiquidGlassEffectGroup',
  },
  {
    id: 'DEP-M0813',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassScrollEdge',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'ScrollEdge',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'LiquidGlassScrollEdge is deprecated; use ScrollEdge (codemod: canonical-names).',
    doc: '#dep-m0813',
    compat: 'LiquidGlassScrollEdge',
  },
  {
    id: 'DEP-M0814',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassConcentricFrame',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'ConcentricFrame',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'LiquidGlassConcentricFrame is deprecated; use ConcentricFrame (codemod: canonical-names).',
    doc: '#dep-m0814',
    compat: 'LiquidGlassConcentricFrame',
  },
  {
    id: 'DEP-M0815',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassLayerProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x nested-materials rule and dev layer counter',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'LiquidGlassLayerProvider is deprecated; counts nested layers in dev and needs no provider (codemod: providers).',
    doc: '#dep-m0815',
    compat: 'LiquidGlassLayerProvider',
  },
  {
    id: 'DEP-M0816',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassSurfaceLayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x nested-materials rule and dev layer counter',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'LiquidGlassSurfaceLayer is deprecated; layer is inferred from nesting in 5.x (codemod: providers).',
    doc: '#dep-m0816',
    compat: 'LiquidGlassSurfaceLayer',
  },
  {
    id: 'DEP-M0817',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'useLiquidGlassLayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x nested-materials rule and dev layer counter',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'useLiquidGlassLayer is deprecated; layer is inferred from nesting in 5.x (codemod: providers).',
    doc: '#dep-m0817',
    compat: 'useLiquidGlassLayer',
  },
  {
    id: 'DEP-M0818',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiquidGlassBackdropSampler',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop or Environment (backdrop is declared, never sampled)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'LiquidGlassBackdropSampler is removed in 5.0; declare the backdrop with data-ag-backdrop or Environment (codemod: removed).',
    doc: '#dep-m0818',
  },
  {
    id: 'DEP-M0819',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useLiquidGlassBackdrop',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop or Environment (backdrop is declared, never sampled)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useLiquidGlassBackdrop is removed in 5.0; declare the backdrop with data-ag-backdrop or Environment (codemod: removed).',
    doc: '#dep-m0819',
  },
  {
    id: 'DEP-M0820',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGlassProbes',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop or Environment (backdrop is declared, never sampled)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useGlassProbes is removed in 5.0; declare the backdrop with data-ag-backdrop or Environment (codemod: removed).',
    doc: '#dep-m0820',
  },
  {
    id: 'DEP-M0821',
    kind: 'subpath',
    status: 'planned',
    entry: './hooks/useGlassProbes',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop or Environment (no 5.x subpath)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B4',
    message:
      'aura-glass/hooks/useGlassProbes is removed in 5.0; declare the backdrop with data-ag-backdrop or Environment (codemod: removed).',
    doc: '#dep-m0821',
  },
  {
    id: 'DEP-M0822',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'createGlassStyle',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'createGlassStyle is removed in 5.0; use materialProps/MaterialSpec — unmapped call shapes get a TODO marker (codemod: removed).',
    doc: '#dep-m0822',
  },
  {
    id: 'DEP-M0823',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'glassFoundation',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'glassFoundation is removed in 5.0; use materialProps/MaterialSpec — unmapped call shapes get a TODO marker (codemod: removed).',
    doc: '#dep-m0823',
  },
  {
    id: 'DEP-M0824',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'glassSurface',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'glassSurface is removed in 5.0; use materialProps/MaterialSpec — unmapped call shapes get a TODO marker (codemod: removed).',
    doc: '#dep-m0824',
  },
  {
    id: 'DEP-M0825',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'glassTokenUtils',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'glassTokenUtils is removed in 5.0; use materialProps/MaterialSpec (codemod: removed).',
    doc: '#dep-m0825',
  },
  {
    id: 'DEP-M0826',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'glassUtils',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'glassUtils is removed in 5.0; use materialProps/MaterialSpec (codemod: removed).',
    doc: '#dep-m0826',
  },
  {
    id: 'DEP-M0827',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'liquidGlassUtils',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'liquidGlassUtils is removed in 5.0; use materialProps/MaterialSpec (codemod: removed).',
    doc: '#dep-m0827',
  },
  {
    id: 'DEP-M0828',
    kind: 'subpath',
    status: 'planned',
    entry: './core/mixins/glassMixins',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'materialProps / MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B4',
    message:
      'aura-glass/core/mixins/glassMixins is removed in 5.0; use materialProps/MaterialSpec (codemod: removed).',
    doc: '#dep-m0828',
  },
  {
    id: 'DEP-M0829',
    kind: 'export',
    status: 'planned',
    entry: './theme',
    symbol: 'GlassMaterialPreset',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'the GlassMaterialPreset type is removed in 5.0; use MaterialSpec (codemod: removed).',
    doc: '#dep-m0829',
  },
  {
    id: 'DEP-M0830',
    kind: 'export',
    status: 'planned',
    entry: './theme',
    symbol: 'GlassMaterialTokens',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'MaterialSpec (aura-glass/material)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'the GlassMaterialTokens type is removed in 5.0; use MaterialSpec (codemod: removed).',
    doc: '#dep-m0830',
  },
  // ---- MAT-351 · 4.2 · §9 recipe classes / emissions ----
  {
    id: 'DEP-M0831',
    kind: 'asset',
    status: 'planned',
    entry: './styles',
    symbol: 'glass.generated.css',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/material.css + data-ag-tier',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'glass.generated.css is removed in 5.0; the 5.x material.css emits solved recipes. doctor reports remaining class usage.',
    doc: '#dep-m0831',
  },
  {
    id: 'DEP-M0832',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'glass.css recipe classes',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/material.css + data-ag-tier',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass.css recipe classes are removed in 5.0; use aura-glass/material.css + data-ag-tier. doctor reports usage.',
    doc: '#dep-m0832',
  },
  {
    id: 'DEP-M0833',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'glass-backdrop-blur*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop + material.css tiers',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-backdrop-blur* are removed in 5.0; use data-ag-backdrop + material.css tiers. doctor reports usage.',
    doc: '#dep-m0833',
  },
  {
    id: 'DEP-M0834',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'glass-animate-*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens + aura-glass/motion',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-animate-* are removed in 5.0; use CSS motion tokens + aura-glass/motion. doctor reports usage.',
    doc: '#dep-m0834',
  },
  {
    id: 'DEP-M0835',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'glass-transition-all',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens (transition presets)',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-transition-all are removed in 5.0; use the 5.x motion tokens (transition presets). doctor reports usage.',
    doc: '#dep-m0835',
  },
  {
    id: 'DEP-M0836',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'glass-tier-*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-tier',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-tier-* are removed in 5.0; use data-ag-tier. doctor reports usage.',
    doc: '#dep-m0836',
  },
  {
    id: 'DEP-M0837',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'liquid-glass-* emissions',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-* attributes emitted by material.css',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the liquid-glass-* emissions are removed in 5.0; use data-ag-* attributes emitted by material.css. doctor reports usage.',
    doc: '#dep-m0837',
  },
  {
    id: 'DEP-M0838',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--aura-blur-amount',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the solved tier of material.css (blur is owned by the material, not tunable)',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      '--aura-blur-amount is removed in 5.0; blur is a solved material property (codemod: css-vars).',
    doc: '#dep-m0838',
  },
  // ---- MAT-351 · 4.2 · §9 GPU / effects rows ----
  {
    id: 'DEP-M0839',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'HoudiniGlassCard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'HoudiniGlassCard is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0839',
  },
  {
    id: 'DEP-M0840',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'HoudiniGlassProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'HoudiniGlassProvider is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0840',
  },
  {
    id: 'DEP-M0841',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassGPU',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'LiquidGlassGPU is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0841',
  },
  {
    id: 'DEP-M0842',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassWebGLShader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassWebGLShader is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0842',
  },
  {
    id: 'DEP-M0843',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'HeatGlass',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'HeatGlass is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0843',
  },
  {
    id: 'DEP-M0844',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'Glass3DEngine',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'Glass3DEngine is removed in 5.0; GPU/shader effects are labs-only over owned pixels, not part of core (codemod: removed).',
    doc: '#dep-m0844',
  },
  // ---- MAT-353 · 4.2 · storybook-utility-shim.css css-global row ----
  {
    id: 'DEP-M0845',
    kind: 'css-global',
    status: 'planned',
    entry: './styles',
    symbol: 'storybook-utility-shim.css',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B8',
    message:
      'the storybook-utility-shim.css import (src/styles/index.css) leaves the package at 5.0 — the file moves to .storybook/ (PKG-101). doctor --v5 reports it.',
    doc: '#dep-m0845',
  },
  // ---- MAT-364 · 4.2 · AC-MOT-18 motion exports, props, tokens ----
  {
    id: 'DEP-M0846',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'Motion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens, startMorph or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'Motion (root; MotionNative alias) is removed in 5.0; use CSS motion tokens, startMorph or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0846',
    compat: 'Motion',
  },
  {
    id: 'DEP-M0847',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'Motion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens, startMorph or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'Motion (MotionFramer alias) is removed in 5.0; use CSS motion tokens, startMorph or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0847',
    compat: 'Motion',
  },
  {
    id: 'DEP-M0848',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'GlassMotion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens, startMorph or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMotion is removed in 5.0; use CSS motion tokens, startMorph or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0848',
    compat: 'GlassMotion',
  },
  {
    id: 'DEP-M0849',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'MotionNative',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens, startMorph or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'MotionNative is removed in 5.0; use CSS motion tokens, startMorph or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0849',
    compat: 'MotionNative',
  },
  {
    id: 'DEP-M0850',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'MotionFramer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens, startMorph or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'MotionFramer is removed in 5.0; use CSS motion tokens, startMorph or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0850',
    compat: 'MotionFramer',
  },
  {
    id: 'DEP-M0851',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMotionController',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMotionController is removed in 5.0; use CSS motion tokens or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0851',
  },
  {
    id: 'DEP-M0852',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTransitions',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassTransitions is removed in 5.0; use CSS motion tokens or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0852',
  },
  {
    id: 'DEP-M0853',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'OrganicAnimationEngine',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'OrganicAnimationEngine is removed in 5.0; use CSS motion tokens or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0853',
  },
  {
    id: 'DEP-M0854',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AdvancedAnimations',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens or aura-glass/motion',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'AdvancedAnimations is removed in 5.0; use CSS motion tokens or aura-glass/motion (codemod: motion-imports).',
    doc: '#dep-m0854',
  },
  {
    id: 'DEP-M0855',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'animationPresets',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'animationPresets is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0855',
  },
  {
    id: 'DEP-M0856',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'usePhysicsEngine',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs (toMotionTransition)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'usePhysicsEngine is removed in 5.0; use aura-glass/motion springs (toMotionTransition) (codemod: motion-imports).',
    doc: '#dep-m0856',
  },
  {
    id: 'DEP-M0857',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'usePhysicsLayout',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion SharedLayout',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'usePhysicsLayout is removed in 5.0; use aura-glass/motion SharedLayout (codemod: motion-imports).',
    doc: '#dep-m0857',
  },
  {
    id: 'DEP-M0858',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'usePhysicsInteraction',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'usePhysicsInteraction is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0858',
  },
  {
    id: 'DEP-M0859',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGalileoStateSpring',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useGalileoStateSpring is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0859',
  },
  {
    id: 'DEP-M0860',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGalileoSprings',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useGalileoSprings is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0860',
  },
  {
    id: 'DEP-M0861',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMultiSpringBasic',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMultiSpringBasic is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0861',
  },
  {
    id: 'DEP-M0862',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMultiSpringPhysics',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMultiSpringPhysics is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0862',
  },
  {
    id: 'DEP-M0863',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGesturePhysics',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useGesturePhysics is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0863',
  },
  {
    id: 'DEP-M0864',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAnimationSequence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useAnimationSequence is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0864',
  },
  {
    id: 'DEP-M0865',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAnimationSequenceBasic',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useAnimationSequenceBasic is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0865',
  },
  {
    id: 'DEP-M0866',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAnimationSequenceOrchestrator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useAnimationSequenceOrchestrator is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0866',
  },
  {
    id: 'DEP-M0867',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'orchestrationUseAnimationSequence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'orchestrationUseAnimationSequence is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0867',
  },
  {
    id: 'DEP-M0868',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'orchestrationPresets',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'orchestrationPresets is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0868',
  },
  {
    id: 'DEP-M0869',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'createOrchestration',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'createOrchestration is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0869',
  },
  {
    id: 'DEP-M0870',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useOrchestration',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useOrchestration is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0870',
  },
  {
    id: 'DEP-M0871',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMouseMagneticEffect',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMouseMagneticEffect is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-imports).',
    doc: '#dep-m0871',
  },
  {
    id: 'DEP-M0872',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMagneticField',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMagneticField is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-imports).',
    doc: '#dep-m0872',
  },
  {
    id: 'DEP-M0873',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMagneticButton',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMagneticButton is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-imports).',
    doc: '#dep-m0873',
  },
  {
    id: 'DEP-M0874',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMagneticElement',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMagneticElement is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-imports).',
    doc: '#dep-m0874',
  },
  {
    id: 'DEP-M0875',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'use3DTransform',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS transforms + the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'use3DTransform is removed in 5.0; use CSS transforms + the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0875',
  },
  {
    id: 'DEP-M0876',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAmbientTilt',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS transforms + the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useAmbientTilt is removed in 5.0; use CSS transforms + the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0876',
  },
  {
    id: 'DEP-M0877',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useZSpaceAnimation',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion sequencing',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useZSpaceAnimation is removed in 5.0; use aura-glass/motion sequencing (codemod: motion-imports).',
    doc: '#dep-m0877',
  },
  {
    id: 'DEP-M0878',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useDraggableListPhysics',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useDraggableListPhysics is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0878',
  },
  {
    id: 'DEP-M0879',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'createMagneticEffect',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'createMagneticEffect is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-imports).',
    doc: '#dep-m0879',
  },
  {
    id: 'DEP-M0880',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'createRippleEffect',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — ripple effects are not part of the material grammar',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'createRippleEffect is removed in 5.0; use none — ripple effects are not part of the material grammar (codemod: motion-imports).',
    doc: '#dep-m0880',
  },
  {
    id: 'DEP-M0881',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'createAccessibleAnimation',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the preference-aware 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'createAccessibleAnimation is removed in 5.0; use the preference-aware 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0881',
  },
  {
    id: 'DEP-M0882',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'SpringPresets',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'SpringPresets is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0882',
  },
  {
    id: 'DEP-M0883',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'InterpolationUtils',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'InterpolationUtils is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0883',
  },
  {
    id: 'DEP-M0884',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'interpolate',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'interpolate is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0884',
  },
  {
    id: 'DEP-M0885',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GalileoPhysicsSystem',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion springs',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GalileoPhysicsSystem is removed in 5.0; use aura-glass/motion springs (codemod: motion-imports).',
    doc: '#dep-m0885',
  },
  {
    id: 'DEP-M0886',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ChartAnimationUtils',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'ChartAnimationUtils is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0886',
  },
  {
    id: 'DEP-M0887',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'animateChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'animateChart is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0887',
  },
  {
    id: 'DEP-M0888',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'chartAnimationPresets',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'chartAnimationPresets is removed in 5.0; use the 5.x motion tokens (codemod: motion-imports).',
    doc: '#dep-m0888',
  },
  {
    id: 'DEP-M0889',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'ReducedMotionProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\') — the OS floor cannot be overridden',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B13',
    message:
      'ReducedMotionProvider is deprecated; read motion preference via usePreference(\'motion\') — OS floors cannot be overridden (codemod: providers).',
    doc: '#dep-m0889',
    compat: 'ReducedMotionProvider',
  },
  {
    id: 'DEP-M0890',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'MotionPreferenceProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AuraGlassProvider + usePreference',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B13',
    message:
      'MotionPreferenceProvider is deprecated; preferences live under AuraGlassProvider and usePreference (codemod: providers).',
    doc: '#dep-m0890',
    compat: 'MotionPreferenceProvider',
  },
  {
    id: 'DEP-M0891',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'MotionPreferenceContext',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference / useResolvedPreferences',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B13',
    message:
      'MotionPreferenceContext is deprecated; use usePreference / useResolvedPreferences (codemod: providers).',
    doc: '#dep-m0891',
    compat: 'MotionPreferenceContext',
  },
  {
    id: 'DEP-M0892',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useReducedMotion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\')',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'useReducedMotion is deprecated; use usePreference(\'motion\') (codemod: motion-imports). A compat wrapper ships in aura-glass/compat.',
    doc: '#dep-m0892',
    compat: 'useReducedMotion',
  },
  {
    id: 'DEP-M0893',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useEnhancedReducedMotion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\')',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'useEnhancedReducedMotion is deprecated; use usePreference(\'motion\') (codemod: motion-imports).',
    doc: '#dep-m0893',
    compat: 'useEnhancedReducedMotion',
  },
  {
    id: 'DEP-M0894',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMotionPreference',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\')',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'useMotionPreference is deprecated; use usePreference(\'motion\') (codemod: motion-imports).',
    doc: '#dep-m0894',
    compat: 'useMotionPreference',
  },
  {
    id: 'DEP-M0895',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'prefersReducedMotion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\')',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'prefersReducedMotion is deprecated; use usePreference(\'motion\') (codemod: motion-imports). A compat wrapper ships in aura-glass/compat.',
    doc: '#dep-m0895',
    compat: 'prefersReducedMotion',
  },
  {
    id: 'DEP-M0896',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useMotionAwareAnimation',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens (preference-aware by construction)',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useMotionAwareAnimation is removed in 5.0; the motion tokens are preference-aware (codemod: motion-imports).',
    doc: '#dep-m0896',
  },
  {
    id: 'DEP-M0897',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGlassMotionPolicy',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference(\'motion\') — OS floors cannot be overridden',
    codemod: 'motion-imports',
    automation: 'partial',
    breaking: 'B13',
    message:
      'useGlassMotionPolicy is removed in 5.0; motion policy is a floor, not a prop — use usePreference(\'motion\') (codemod: motion-imports).',
    doc: '#dep-m0897',
  },
  {
    id: 'DEP-M0898',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'respectMotionPreference',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the OS motion floor (not overridable in 5.x)',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the respectMotionPreference prop is removed in 5.0; use the OS motion floor (not overridable in 5.x) (codemod: motion-props).',
    doc: '#dep-m0898',
  },
  {
    id: 'DEP-M0899',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'motionPolicy',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the OS motion floor (not overridable in 5.x)',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the motionPolicy prop is removed in 5.0; use the OS motion floor (not overridable in 5.x) (codemod: motion-props).',
    doc: '#dep-m0899',
  },
  {
    id: 'DEP-M0900',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'initialMotionPolicy',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the OS motion floor (not overridable in 5.x)',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the initialMotionPolicy prop is removed in 5.0; use the OS motion floor (not overridable in 5.x) (codemod: motion-props).',
    doc: '#dep-m0900',
  },
  {
    id: 'DEP-M0901',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'preset (motion) / animationPreset',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the preset (motion) / animationPreset prop is removed in 5.0; use the 5.x motion tokens (codemod: motion-props).',
    doc: '#dep-m0901',
  },
  {
    id: 'DEP-M0902',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'animate',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CSS motion tokens or aura-glass/motion',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the animate prop is removed in 5.0; use CSS motion tokens or aura-glass/motion (codemod: motion-props).',
    doc: '#dep-m0902',
  },
  {
    id: 'DEP-M0903',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'disableAnimation',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the OS motion floor / calm mode',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the disableAnimation prop is removed in 5.0; use the OS motion floor / calm mode (codemod: motion-props).',
    doc: '#dep-m0903',
  },
  {
    id: 'DEP-M0904',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'whileHover / whileTap pass-through',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/motion magnetic() / CSS motion tokens',
    codemod: 'motion-props',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the whileHover / whileTap pass-through prop is removed in 5.0; use aura-glass/motion magnetic() / CSS motion tokens (codemod: motion-props).',
    doc: '#dep-m0904',
  },
  {
    id: 'DEP-M0905',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMagneticButton',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Button + magnetic() (aura-glass/motion)',
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassMagneticButton is removed in 5.0; use Button + magnetic() (aura-glass/motion) (codemod: motion-props).',
    doc: '#dep-m0905',
  },
  {
    id: 'DEP-M0906',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMagneticCursor',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'magnetic() (aura-glass/motion)',
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassMagneticCursor is removed in 5.0; use magnetic() (aura-glass/motion) (codemod: motion-props).',
    doc: '#dep-m0906',
  },
  {
    id: 'DEP-M0907',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'RippleButton',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Button (5.x) — ripple effects are not part of the material grammar',
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'RippleButton is removed in 5.0; use Button (5.x) — ripple effects are not part of the material grammar (codemod: motion-props).',
    doc: '#dep-m0907',
  },
  {
    id: 'DEP-M0908',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'TouchRippleEffects',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'TouchRippleEffects is removed in 5.0; use none — ripple effects are not part of the material grammar (codemod: motion-props).',
    doc: '#dep-m0908',
  },
  {
    id: 'DEP-M0909',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'MotionAwareGlass',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface (motion is preference-driven in 5.x)',
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'MotionAwareGlass is removed in 5.0; use Surface (motion is preference-driven in 5.x) (codemod: motion-props).',
    doc: '#dep-m0909',
  },
  {
    id: 'DEP-M0910',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDepthLayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Surface layering (the 5.x nested-materials rule)',
    codemod: 'motion-props',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassDepthLayer is removed in 5.0; use Surface layering (the 5.x nested-materials rule) (codemod: motion-props).',
    doc: '#dep-m0910',
  },
  {
    id: 'DEP-M0911',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'ANIMATION',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ANIMATION is removed in 5.0; motion values ship as tokens (codemod: motion-imports).',
    doc: '#dep-m0911',
  },
  {
    id: 'DEP-M0912',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'AURA_GLASS.motion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'AURA_GLASS.motion is removed in 5.0; motion values ship as tokens (codemod: motion-imports).',
    doc: '#dep-m0912',
  },
  {
    id: 'DEP-M0913',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'LIQUID_GLASS.motionFluency',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x motion tokens',
    codemod: 'motion-imports',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'LIQUID_GLASS.motionFluency is removed in 5.0; motion values ship as tokens (codemod: motion-imports).',
    doc: '#dep-m0913',
  },
  {
    id: 'DEP-M0914',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--glass-motion-*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: '--ag-motion-* motion tokens',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --glass-motion-* variables are removed in 5.0; use the --ag-motion-* tokens (codemod: css-vars).',
    doc: '#dep-m0914',
  },
  {
    id: 'DEP-M0915',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--glass-motion-default',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: '--ag-motion-default',
    codemod: 'css-vars',
    automation: 'full',
    breaking: 'B9',
    message:
      '--glass-motion-default is removed in 5.0; use --ag-motion-default (codemod: css-vars).',
    doc: '#dep-m0915',
  },
  {
    id: 'DEP-M0916',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--glass-theme-duration-*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: '--ag-motion-duration-* tokens',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --glass-theme-duration-* variables are removed in 5.0; use the --ag-motion-duration-* tokens (codemod: css-vars).',
    doc: '#dep-m0916',
  },
  {
    id: 'DEP-M0917',
    kind: 'peer',
    status: 'planned',
    entry: '.',
    symbol: 'framer-motion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'motion@^12 as an optional peer of aura-glass/motion',
    codemod: 'deps',
    automation: 'full',
    breaking: 'B7',
    message:
      'the framer-motion peer is removed in 5.0; aura-glass/motion takes an optional motion@^12 peer (codemod: deps).',
    doc: '#dep-m0917',
  },
  // ---- MAT-373 · 4.2 · §9 accessibility rows ----
  {
    id: 'DEP-M0918',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ContrastGuard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (the material guarantees contrast)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ContrastGuard is removed in 5.0; contrast floors are solved by the material (codemod: removed, unwraps <ContrastGuard as=X>).',
    doc: '#dep-m0918',
  },
  {
    id: 'DEP-M0919',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'TextWithContrast',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (the material guarantees contrast)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'TextWithContrast is removed in 5.0; contrast floors are solved by the material (codemod: removed).',
    doc: '#dep-m0919',
  },
  {
    id: 'DEP-M0920',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'HighContrastText',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (the material guarantees contrast)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'HighContrastText is removed in 5.0; contrast floors are solved by the material (codemod: removed).',
    doc: '#dep-m0920',
  },
  {
    id: 'DEP-M0921',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useContrastGuard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (the material guarantees contrast)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useContrastGuard is removed in 5.0; contrast floors are solved by the material (codemod: removed).',
    doc: '#dep-m0921',
  },
  {
    id: 'DEP-M0922',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAutoTextContrast',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (the material guarantees contrast)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useAutoTextContrast is removed in 5.0; contrast floors are solved by the material (codemod: removed).',
    doc: '#dep-m0922',
  },
  {
    id: 'DEP-M0923',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'validateTextContrast',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (CI axe for audits)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'validateTextContrast is removed in 5.0; floors are solved — audit with the CI axe lane (codemod: removed).',
    doc: '#dep-m0923',
  },
  {
    id: 'DEP-M0924',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'validateLiquidContrast',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (CI axe for audits)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'validateLiquidContrast is removed in 5.0; floors are solved — audit with the CI axe lane (codemod: removed).',
    doc: '#dep-m0924',
  },
  {
    id: 'DEP-M0925',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'sampleBackdropLuminance',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (backdrop luminance is not sampled in 5.x)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'sampleBackdropLuminance is removed in 5.0; the material does not sample the backdrop (codemod: removed).',
    doc: '#dep-m0925',
  },
  {
    id: 'DEP-M0926',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassA11y',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassPreferencesPanel',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassA11y is removed in 5.0; use GlassPreferencesPanel (codemod: removed).',
    doc: '#dep-m0926',
  },
  {
    id: 'DEP-M0927',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassHighContrast',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassPreferencesPanel (contrast preference)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassHighContrast is removed in 5.0; use GlassPreferencesPanel (contrast preference) (codemod: removed).',
    doc: '#dep-m0927',
  },
  {
    id: 'DEP-M0928',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMotionControls',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassPreferencesPanel (motion preference)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassMotionControls is removed in 5.0; use GlassPreferencesPanel (motion preference) (codemod: removed).',
    doc: '#dep-m0928',
  },
  {
    id: 'DEP-M0929',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassScreenReader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassPreferencesPanel / useAnnouncer',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassScreenReader is removed in 5.0; use GlassPreferencesPanel / useAnnouncer (codemod: removed).',
    doc: '#dep-m0929',
  },
  {
    id: 'DEP-M0930',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassKeyboardNav',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x keyboard contract (built into components)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassKeyboardNav is removed in 5.0; use the 5.x keyboard contract (built into components) (codemod: removed).',
    doc: '#dep-m0930',
  },
  {
    id: 'DEP-M0931',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassA11yAuditor',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CI axe lane (audits run in CI, not in the bundle)',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassA11yAuditor is removed in 5.0; audits run in the CI axe lane (codemod: removed).',
    doc: '#dep-m0931',
  },
  {
    id: 'DEP-M0932',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFocusIndicators',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'focus.css + useAnnouncer',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassFocusIndicators is removed in 5.0; use focus.css + useAnnouncer (codemod: removed).',
    doc: '#dep-m0932',
  },
  {
    id: 'DEP-M0933',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'SkipLinks',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'focus.css landmark/focus styles',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'SkipLinks is removed in 5.0; use focus.css landmark/focus styles (codemod: removed).',
    doc: '#dep-m0933',
  },
  {
    id: 'DEP-M0934',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LandmarkAnnouncer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'LandmarkAnnouncer is removed in 5.0; use useAnnouncer (codemod: removed).',
    doc: '#dep-m0934',
  },
  {
    id: 'DEP-M0935',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'KeyboardShortcutsHelper',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x keyboard contract (built into components)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'KeyboardShortcutsHelper is removed in 5.0; use the 5.x keyboard contract (built into components) (codemod: removed).',
    doc: '#dep-m0935',
  },
  {
    id: 'DEP-M0936',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFocusIndicators CSS (focus-indicator rules)',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'focus.css',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B8',
    message:
      'the GlassFocusIndicators companion CSS is removed in 5.0; focus styles ship in focus.css (codemod: removed).',
    doc: '#dep-m0936',
  },
  {
    id: 'DEP-M0937',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFocusRing',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'focus.css',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassFocusRing is removed in 5.0; focus appearance ships in focus.css (codemod: removed).',
    doc: '#dep-m0937',
  },
  {
    id: 'DEP-M0938',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'FocusIndicator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'focus.css',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'FocusIndicator is removed in 5.0; focus appearance ships in focus.css (codemod: removed).',
    doc: '#dep-m0938',
  },
  {
    id: 'DEP-M0939',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AccessibilityProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AuraGlassProvider (highContrast→contrast="more", reducedTransparency→transparency="tinted", colorBlindness dropped)',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'AccessibilityProvider is deprecated; use AuraGlassProvider (highContrast→contrast="more", reducedTransparency→transparency="tinted", colorBlindness dropped) (codemod: providers).',
    doc: '#dep-m0939',
    compat: 'AccessibilityProvider',
  },
  {
    id: 'DEP-M0940',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAccessibility',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference / useResolvedPreferences',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'useAccessibility is deprecated; use usePreference / useResolvedPreferences (codemod: providers).',
    doc: '#dep-m0940',
    compat: 'useAccessibility',
  },
  {
    id: 'DEP-M0941',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAccessibilitySettings',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreferenceActions / useResolvedPreferences',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'useAccessibilitySettings is deprecated; use usePreferenceActions / useResolvedPreferences (codemod: providers).',
    doc: '#dep-m0941',
    compat: 'useAccessibilitySettings',
  },
  {
    id: 'DEP-M0942',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassThemeProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AuraGlassProvider',
    codemod: 'providers',
    automation: 'full',
    breaking: 'B5',
    message:
      'GlassThemeProvider is deprecated; use AuraGlassProvider (codemod: providers).',
    doc: '#dep-m0942',
    compat: 'GlassThemeProvider',
  },
  {
    id: 'DEP-M0943',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ThemeProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AuraGlassProvider',
    codemod: 'providers',
    automation: 'full',
    breaking: 'B5',
    message:
      'ThemeProvider is deprecated; use AuraGlassProvider (codemod: providers).',
    doc: '#dep-m0943',
    compat: 'ThemeProvider',
  },
  {
    id: 'DEP-M0944',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useGlassTheme',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'usePreference / useResolvedPreferences',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'useGlassTheme is deprecated; use usePreference / useResolvedPreferences (codemod: providers).',
    doc: '#dep-m0944',
    compat: 'useGlassTheme',
  },
  {
    id: 'DEP-M0945',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AIGlassThemeProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AuraGlassProvider',
    codemod: 'providers',
    automation: 'full',
    breaking: 'B5',
    message:
      'AIGlassThemeProvider is deprecated; use AuraGlassProvider (codemod: providers).',
    doc: '#dep-m0945',
    compat: 'AIGlassThemeProvider',
  },
  {
    id: 'DEP-M0946',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'ScreenReader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer (ScreenReaderOnly → VisuallyHidden)',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'ScreenReader is removed in 5.0; use useAnnouncer (ScreenReaderOnly → VisuallyHidden) (codemod: canonical-names).',
    doc: '#dep-m0946',
  },
  {
    id: 'DEP-M0947',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'ScreenReaderOnly',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'VisuallyHidden (CMP)',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'ScreenReaderOnly is removed in 5.0; use VisuallyHidden (CMP) (codemod: canonical-names).',
    doc: '#dep-m0947',
  },
  {
    id: 'DEP-M0948',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'LiveRegion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'LiveRegion is removed in 5.0; use useAnnouncer (codemod: canonical-names).',
    doc: '#dep-m0948',
  },
  {
    id: 'DEP-M0949',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'announce',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'announce is removed in 5.0; use useAnnouncer (codemod: canonical-names).',
    doc: '#dep-m0949',
  },
  {
    id: 'DEP-M0950',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'useAnnounce',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'useAnnounce is removed in 5.0; use useAnnouncer (codemod: canonical-names).',
    doc: '#dep-m0950',
  },
  {
    id: 'DEP-M0951',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'announceToScreenReader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useAnnouncer (both 4.x implementations)',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B5',
    message:
      'announceToScreenReader is removed in 5.0; use useAnnouncer (both 4.x implementations) (codemod: canonical-names).',
    doc: '#dep-m0951',
  },
  {
    id: 'DEP-M0952',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'FocusTrap',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x overlay components (focus managed internally)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'FocusTrap is removed in 5.0; overlay components manage focus internally (codemod: removed).',
    doc: '#dep-m0952',
  },
  {
    id: 'DEP-M0953',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'useFocusTrap',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x overlay components (focus managed internally)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'useFocusTrap is removed in 5.0; overlay components manage focus internally (codemod: removed).',
    doc: '#dep-m0953',
  },
  {
    id: 'DEP-M0954',
    kind: 'export',
    status: 'planned',
    entry: './primitives',
    symbol: 'trapFocus',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x overlay components (focus managed internally)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'trapFocus is removed in 5.0; overlay components manage focus internally (codemod: removed).',
    doc: '#dep-m0954',
  },
  // ---- MAT-373 · 4.3 · §9 accessibility CSS hooks ----
  {
    id: 'DEP-M0955',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: '.high-contrast',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-contrast="more"',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the .high-contrast hook is removed in 5.0; use data-ag-contrast="more".',
    doc: '#dep-m0955',
  },
  {
    id: 'DEP-M0956',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: '.large-text',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-text="large" (5.x preference attribute)',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the .large-text hook is removed in 5.0; use data-ag-text="large" (5.x preference attribute).',
    doc: '#dep-m0956',
  },
  {
    id: 'DEP-M0957',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-color-blindness',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the data-color-blindness hook is removed in 5.0; color-vision modes are dropped — contrast floors apply.',
    doc: '#dep-m0957',
  },
  {
    id: 'DEP-M0958',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: 'glass-contrast-guard',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'solved contrast floors (no CSS hook)',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-contrast-guard hook is removed in 5.0; use solved contrast floors (no CSS hook).',
    doc: '#dep-m0958',
  },
  {
    id: 'DEP-M0959',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: 'glass-focus',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'focus.css focus styles',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-focus hook is removed in 5.0; use focus.css focus styles.',
    doc: '#dep-m0959',
  },
  {
    id: 'DEP-M0960',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: 'glass-touch-target',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x target-size floor (built into components)',
    codemod: null,
    automation: 'manual',
    breaking: 'B8',
    message:
      'the glass-touch-target hook is removed in 5.0; use the 5.x target-size floor (built into components).',
    doc: '#dep-m0960',
  },
  // ---- MAT-339 · 4.3 · css vars + mode hooks + personas + theme APIs ----
  {
    id: 'DEP-M0961',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--glass-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: '--ag-* (compat/tokens.css aliases reads only)',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --glass-* variables are removed in 5.0; use --ag-* — compat/tokens.css aliases reads only (codemod: css-vars).',
    doc: '#dep-m0961',
  },
  {
    id: 'DEP-M0962',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--aura-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: '--ag-* (compat/tokens.css aliases reads only)',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --aura-* variables are removed in 5.0; use --ag-* — compat/tokens.css aliases reads only (codemod: css-vars).',
    doc: '#dep-m0962',
  },
  {
    id: 'DEP-M0963',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--persona-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: '--ag-* (compat/tokens.css aliases reads only)',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --persona-* variables are removed in 5.0; use --ag-* — compat/tokens.css aliases reads only (codemod: css-vars).',
    doc: '#dep-m0963',
  },
  {
    id: 'DEP-M0964',
    kind: 'css-var',
    status: 'planned',
    entry: '.',
    symbol: '--glass-theme-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: '--ag-* (compat/tokens.css aliases reads only)',
    codemod: 'css-vars',
    automation: 'mostly',
    breaking: 'B9',
    message:
      'the --glass-theme-* variables are removed in 5.0; use --ag-* — compat/tokens.css aliases reads only (codemod: css-vars).',
    doc: '#dep-m0964',
  },
  {
    id: 'DEP-M0965',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-theme',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-scheme (compat/tokens.css aliases the scheme hooks only)',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the data-theme hook is removed in 5.0; use data-ag-scheme (compat/tokens.css aliases the scheme hooks only).',
    doc: '#dep-m0965',
  },
  {
    id: 'DEP-M0966',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-aura-theme',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-scheme',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the data-aura-theme hook is removed in 5.0; use data-ag-scheme.',
    doc: '#dep-m0966',
  },
  {
    id: 'DEP-M0967',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-aura-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-* attributes',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the data-aura-* hook is removed in 5.0; use data-ag-* attributes.',
    doc: '#dep-m0967',
  },
  {
    id: 'DEP-M0968',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-persona',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-preset',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the data-persona hook is removed in 5.0; use data-ag-preset.',
    doc: '#dep-m0968',
  },
  {
    id: 'DEP-M0969',
    kind: 'data-attr',
    status: 'planned',
    entry: '.',
    symbol: 'data-bg',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-backdrop',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the data-bg hook is removed in 5.0; use data-ag-backdrop.',
    doc: '#dep-m0969',
  },
  {
    id: 'DEP-M0970',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: '.dark / .light',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-scheme="dark|light" (compat aliases the scheme hooks only)',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the .dark / .light hook is removed in 5.0; use data-ag-scheme="dark|light" (compat aliases the scheme hooks only).',
    doc: '#dep-m0970',
  },
  {
    id: 'DEP-M0971',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: '.glass-on-light / .glass-on-dark',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'data-ag-scheme-scoped selectors',
    codemod: null,
    automation: 'manual',
    breaking: 'B10',
    message:
      'the .glass-on-light / .glass-on-dark hook is removed in 5.0; use data-ag-scheme-scoped selectors.',
    doc: '#dep-m0971',
  },
  {
    id: 'DEP-M0972',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'personas (10 persona records)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'presets + createBrandTheme(accent)',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'personas (10 persona records) is removed in 5.0; use presets + createBrandTheme(accent) (codemod: providers).',
    doc: '#dep-m0972',
  },
  {
    id: 'DEP-M0973',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'auraTokens',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'tokens (the only aura-glass/tokens export in 5.0)',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'auraTokens is removed in 5.0; use tokens (the only aura-glass/tokens export in 5.0) (codemod: providers).',
    doc: '#dep-m0973',
  },
  {
    id: 'DEP-M0974',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'PersonaPicker',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'presets + createBrandTheme (no picker ships in 5.x)',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'PersonaPicker is removed in 5.0; use presets + createBrandTheme (no picker ships in 5.x) (codemod: providers).',
    doc: '#dep-m0974',
  },
  {
    id: 'DEP-M0975',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'usePersonaTheme',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'createBrandTheme + usePreference',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'usePersonaTheme is removed in 5.0; use createBrandTheme + usePreference (codemod: providers).',
    doc: '#dep-m0975',
  },
  {
    id: 'DEP-M0976',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'PERSONA_IDS',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x presets table',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'PERSONA_IDS is removed in 5.0; use the 5.x presets table (codemod: providers).',
    doc: '#dep-m0976',
  },
  {
    id: 'DEP-M0977',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'THEME_NAMES',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x presets table',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'THEME_NAMES is removed in 5.0; use the 5.x presets table (codemod: providers).',
    doc: '#dep-m0977',
  },
  {
    id: 'DEP-M0978',
    kind: 'export',
    status: 'planned',
    entry: './theme',
    symbol: 'glassMaterialPresets',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x presets table / MaterialSpec',
    codemod: 'providers',
    automation: 'partial',
    breaking: 'B3',
    message:
      'glassMaterialPresets is removed in 5.0; use the 5.x presets table / MaterialSpec (codemod: providers).',
    doc: '#dep-m0978',
  },
  {
    id: 'DEP-M0979',
    kind: 'export',
    status: 'planned',
    entry: './theme',
    symbol: 'createBrandGlassTheme',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'createBrandTheme (aura-glass/theme)',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'createBrandGlassTheme is deprecated; use createBrandTheme (codemod: providers). A compat re-export ships at aura-glass/compat.',
    doc: '#dep-m0979',
    compat: 'createBrandGlassTheme',
  },
  {
    id: 'DEP-M0980',
    kind: 'export',
    status: 'planned',
    entry: './theme',
    symbol: 'createGlassThemeCssVars',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'createGlassTheme(...).vars',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B5',
    message:
      'createGlassThemeCssVars is deprecated; use createGlassTheme(...).vars (codemod: providers).',
    doc: '#dep-m0980',
  },
  {
    id: 'DEP-M0981',
    kind: 'prop-value',
    status: 'planned',
    entry: '.',
    symbol: 'GlassThemeMode "high-contrast"',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'contrast="more" preference',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the "high-contrast" GlassThemeMode is removed in 5.0; high contrast is the contrast="more" preference (codemod: providers).',
    doc: '#dep-m0981',
  },
  {
    id: 'DEP-M0982',
    kind: 'prop-value',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDensity "comfortable"',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x density scale (§21 OI-03)',
    codemod: 'providers',
    automation: 'mostly',
    breaking: 'B6',
    message:
      'the "comfortable" GlassDensity is removed in 5.0; density maps onto the 5.x scale (codemod: providers; see §21 OI-03).',
    doc: '#dep-m0982',
  },
  {
    id: 'DEP-M0983',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'COLORS (designConstants)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x tokens export',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'the COLORS design constant is removed in 5.0; values ship as tokens (codemod: removed).',
    doc: '#dep-m0983',
  },
  {
    id: 'DEP-M0984',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'BORDER_RADIUS (designConstants)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x tokens export',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'the BORDER_RADIUS design constant is removed in 5.0; values ship as tokens (codemod: removed).',
    doc: '#dep-m0984',
  },
  {
    id: 'DEP-M0985',
    kind: 'export',
    status: 'planned',
    entry: './tokens',
    symbol: 'BOX_SHADOW (designConstants)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x tokens export',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'the BOX_SHADOW design constant is removed in 5.0; values ship as tokens (codemod: removed).',
    doc: '#dep-m0985',
  },
  {
    id: 'DEP-M0986',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: 'glass-* slash utilities',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'the 5.x tokens.css utility output (--ag-* driven)',
    codemod: 'css-vars',
    automation: 'partial',
    breaking: 'B8',
    message:
      'the glass-* slash utilities are removed in 5.0; utility output is generated from --ag-* tokens (codemod: css-vars).',
    doc: '#dep-m0986',
  },
] as const;
// --- lane 2e-B end ---

export default [...t, ...m, ...v, ...p, ...b] satisfies DeprecationFragment;
