/* fragments/deprecations/plat.ts — PLAT owns this file on both branches (§3.4). */
import type { DeprecationFragment } from '../../src/contracts/fragments';

const REPORT_PATH_ENTRIES = [
  ['component_inventory_json', 'reports/component_inventory.json'],
  ['COMPONENT_INVENTORY_JSON_PATH', 'reports/component_inventory.json'],
  ['component_inventory_json_path', 'reports/component_inventory.json'],
  ['GILDED_TOKENS_CATALOGUE_MD', 'reports/GILDED_TOKENS_CATALOGUE.md'],
  ['REDUCED_MOTION_100_COMPLETE_MD', 'reports/REDUCED_MOTION_100_COMPLETE.md'],
  ['REDUCED_MOTION_101_GUIDE_MD', 'reports/REDUCED_MOTION_101_GUIDE.md'],
  ['GILDED_TOKENS_CATALOGUE_MD_PATH', 'reports/GILDED_TOKENS_CATALOGUE.md'],
  ['REDUCED_MOTION_101_GUIDE_MD_PATH', 'reports/REDUCED_MOTION_101_GUIDE.md'],
  ['REDUCED_MOTION_100_COMPLETE_MD_PATH', 'reports/REDUCED_MOTION_100_COMPLETE.md'],
  ['TYPESCRIPT_FIX_PROGRESS_MD_PATH', 'reports/TYPESCRIPT_FIX_PROGRESS.md'],
  ['REDUCED_MOTION_FINAL_REPORT_JSON_PATH', 'reports/reduced-motion-final-report.json'],
] as const;

// PLAT-115 — the 11 root-exported report-path constants are deprecated:
// reports/ is no longer a tracked artifact directory (evidence lives in CI
// artifacts), so these public path strings are sunset in 5.0.0. Values are
// unchanged for the 4.1.x line.
export default REPORT_PATH_ENTRIES.map(([symbol, value], i) => ({
  id: `DEP-P${String(i + 1).padStart(4, '0')}` as `DEP-P${number}`,
  kind: 'export' as const,
  status: 'active' as const,
  entry: '.',
  symbol,
  since: '4.1.1' as const,
  removeIn: '5.0.0' as const,
  replacement: null,
  codemod: null,
  automation: 'none' as const,
  breaking: 'B14',
  exception: 'honesty' as const,
  evidence: 'docs/release/decisions/4.1.1-trust-patch.md' as const,
  message: `root export '${symbol}' ("${value}") is a tracked-reports path constant; reports/ is untracked evidence now — drop the import.`,
  doc: `#dep-${symbol.toLowerCase()}`,
})).concat([
  {
    id: 'DEP-P0012',
    kind: 'export',
    status: 'active',
    entry: '.',
    symbol: 'enableAdaptiveAI',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: 'enableAdaptiveAI opt-in flag (adaptive AI is disabled unless explicitly enabled)',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy',
    evidence: 'docs/security/GHSA-4.1.1-draft.md',
    message: "adaptive AI heuristics now require the explicit 'enableAdaptiveAI' opt-in; unconditional adaptive behavior is removed in 5.0.0.",
    doc: '#dep-enableadaptiveai',
  },
  {
    id: 'DEP-P0013',
    kind: 'prop',
    status: 'active',
    entry: '.',
    symbol: 'GlassCanvas string action execution',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: 'onComponentAction callback prop',
    codemod: null,
    automation: 'manual',
    breaking: 'B14',
    exception: 'security',
    evidence: 'docs/security/GHSA-4.1.1-draft.md',
    message: "GlassCanvas no longer executes string-supplied actions; pass 'onComponentAction' to receive dispatched action descriptors.",
    doc: '#dep-glasscanvas-string-actions',
  },
  {
    id: 'DEP-P0014',
    kind: 'prop',
    status: 'active',
    entry: '.',
    symbol: 'ContrastGuard unconditional pass',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: "'unverified' contrast state when a ratio cannot be computed",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'honesty',
    evidence: 'docs/release/decisions/4.1.1-trust-patch.md',
    message: "contrast utilities report 'unverified' instead of passing when the ratio is uncomputable; handle the new state before 5.0.0.",
    doc: '#dep-contrast-unverified',
  },
  {
    id: 'DEP-P0016',
    kind: 'export',
    status: 'active',
    entry: '.',
    symbol: 'adaptiveAI',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: "the explicit 'enableAdaptiveAI' opt-in surface",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy',
    evidence: 'docs/security/GHSA-4.1.1-draft.md',
    message: "the implicit 'adaptiveAI' export is replaced by the opt-in enableAdaptiveAI surface; implicit adaptive behavior is removed in 5.0.0.",
    doc: '#dep-adaptiveai',
  },
  {
    id: 'DEP-P0017',
    kind: 'export',
    status: 'active',
    entry: '.',
    symbol: 'useAdaptiveAI',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: "enableAdaptiveAI opt-in flag + the non-adaptive default hooks",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy',
    evidence: 'docs/security/GHSA-4.1.1-draft.md',
    message: "'useAdaptiveAI' is superseded by the explicit opt-in path; the implicit adaptive hook is removed in 5.0.0.",
    doc: '#dep-useadaptiveai',
  },
  {
    id: 'DEP-P0018',
    kind: 'prop',
    status: 'active',
    entry: '.',
    symbol: 'data-meets-wcag attribute',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: "'unverified' contrast state + computed data-contrast-state",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'honesty',
    evidence: 'docs/release/decisions/4.1.1-trust-patch.md',
    message: "'data-meets-wcag' claimed a guarantee components could not verify; contrast state is now reported honestly via 'unverified'.",
    doc: '#dep-data-meets-wcag',
  },
  {
    id: 'DEP-P0019',
    kind: 'prop',
    status: 'active',
    entry: '.',
    symbol: 'data-contrast-ratio attribute',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: "computed contrast state ('pass' | 'warn' | 'unverified')",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'honesty',
    evidence: 'docs/release/decisions/4.1.1-trust-patch.md',
    message: "'data-contrast-ratio' emitted values for ratios that were not actually computed; consumers should read the honest contrast state instead.",
    doc: '#dep-data-contrast-ratio',
  },
  {
    id: 'DEP-P0020',
    kind: 'prop',
    status: 'active',
    entry: '.',
    symbol: 'cookie banner auto-display',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: 'explicit consent-driven visibility (consent gating before display)',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy',
    evidence: 'docs/security/GHSA-4.1.1-draft.md',
    message: "cookie consent banners no longer auto-display before consent state resolves; wire visibility to your consent provider before 5.0.0.",
    doc: '#dep-cookie-banner-auto',
  },
  {
    id: 'DEP-P0015',
    kind: 'css-global',
    status: 'active',
    entry: '.',
    symbol: '--glass-font-sans (Aeonik)',
    since: '4.1.1',
    removeIn: '5.0.0',
    replacement: 'system stack: system-ui, -apple-system, "Segoe UI", sans-serif',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'legal',
    evidence: 'docs/release/decisions/4.1.1-font-aeonik.md',
    message: "the bundled Aeonik family is removed (licence unconfirmed, D-31); '--glass-font-sans' resolves to the platform system stack.",
    doc: '#dep-aeonik-font-stack',
  },
]) satisfies DeprecationFragment;
