/* fragments/deprecations/plat.ts — PLAT owns this file on both branches (§3.4). */
import type { DeprecationFragment } from '../../src/contracts/fragments';

const breakingNotices = [
  {
    id: 'DEP-P1000',
    kind: 'peer',
    status: 'active',
    entry: '.',
    symbol: 'React ^19.0 floor',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B1',
    message: 'React ^19.0 floor — see the migration guide (#b-1).',
    doc: '#dep-1',
  },
  {
    id: 'DEP-P1001',
    kind: 'engine',
    status: 'active',
    entry: '.',
    symbol: 'ESM-only, Node >=20.19',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B2',
    message: 'ESM-only, Node >=20.19 — see the migration guide (#b-2).',
    doc: '#dep-2',
  },
  {
    id: 'DEP-P1002',
    kind: 'dependency',
    status: 'active',
    entry: '.',
    symbol: 'Dependency diet',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B7',
    message: 'Dependency diet — see the migration guide (#b-7).',
    doc: '#dep-7',
  },
  {
    id: 'DEP-P1003',
    kind: 'css-global',
    status: 'active',
    entry: '.',
    symbol: 'Global CSS removed; layered CSS',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B8',
    message: 'Global CSS removed; layered CSS — see the migration guide (#b-8).',
    doc: '#dep-8',
  },
  {
    id: 'DEP-P1004',
    kind: 'css-var',
    status: 'active',
    entry: '.',
    symbol: '--glass-* renamed to --ag-*',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B9',
    message: '--glass-* renamed to --ag-* — see the migration guide (#b-9).',
    doc: '#dep-9',
  },
  {
    id: 'DEP-P1005',
    kind: 'data-attr',
    status: 'active',
    entry: '.',
    symbol: 'Base UI DOM, ARIA and data-* changes',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B10',
    message: 'Base UI DOM, ARIA and data-* changes — see the migration guide (#b-10).',
    doc: '#dep-10',
  },
  {
    id: 'DEP-P1006',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Content layer is no longer glass by default',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B12',
    message: 'Content layer is no longer glass by default — see the migration guide (#b-12).',
    doc: '#dep-12',
  },
  {
    id: 'DEP-P1007',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'OS signals are floors; reduced motion cannot be overridden',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B13',
    message: 'OS signals are floors; reduced motion cannot be overridden — see the migration guide (#b-13).',
    doc: '#dep-13',
  },
  {
    id: 'DEP-P1008',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Server, services and simulated AI removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    message: 'Server, services and simulated AI removed — see the migration guide (#b-14).',
    doc: '#dep-14',
  },
  {
    id: 'DEP-P1009',
    kind: 'cli',
    status: 'active',
    entry: '.',
    symbol: 'CLI moved to @auraglass/cli',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B15',
    message: 'CLI moved to @auraglass/cli — see the migration guide (#b-15).',
    doc: '#dep-15',
  },
  {
    id: 'DEP-P1010',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'ssr/server shims removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B16',
    message: 'ssr/server shims removed — see the migration guide (#b-16).',
    doc: '#dep-16',
  },
  {
    id: 'DEP-P1011',
    kind: 'asset',
    status: 'active',
    entry: '.',
    symbol: 'Asset subpath renames (icons/env/json/manifest namespaces)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B17',
    message: 'Asset subpath renames (icons/env/json/manifest namespaces) — see the migration guide (#b-17).',
    doc: '#dep-17',
  },
  {
    id: 'DEP-P1012',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Primitives collapse (4.x primitive set folds into the 5.0 primitives entry)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B18',
    message: 'Primitives collapse (4.x primitive set folds into the 5.0 primitives entry) — see the migration guide (#b-18).',
    doc: '#dep-18',
  },
  {
    id: 'DEP-P1013',
    kind: 'asset',
    status: 'active',
    entry: '.',
    symbol: 'Icons, env vars, .json/.css manifest subpaths removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B19',
    message: 'Icons, env vars, .json/.css manifest subpaths removed — see the migration guide (#b-19).',
    doc: '#dep-19',
  },
  {
    id: 'DEP-P1014',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Dead optical props removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B20',
    message: 'Dead optical props removed — see the migration guide (#b-20).',
    doc: '#dep-20',
  },
  {
    id: 'DEP-P1015',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Provider trees collapse to the 5.0 provider',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B21',
    message: 'Provider trees collapse to the 5.0 provider — see the migration guide (#b-21).',
    doc: '#dep-21',
  },
] as const;

export default [...breakingNotices] satisfies DeprecationFragment;
