/* fragments/deprecations/plat.ts — PLAT owns this file on both branches (§3.4). */
import type { DeprecationFragment } from '../../src/contracts/fragments';

const REPORT_PATH_ENTRIES = [
  ['component_inventory_json', 'reports/component_inventory.json'],
  ['COMPONENT_INVENTORY_JSON_PATH', 'reports/component_inventory.json'],
  ['component_inventory_json_path', 'reports/component_inventory.json'],
  ['GILDED_TOKENS_CATALOGUE_MD', 'reports/GILDED_TOKENS_CATALOGUE.md'],
  ['REDUCED_MOTION_100_COMPLETE_MD', 'reports/REDUCED_MOTION_100_COMPLETE.md'],
  ['REDUCED_MOTION_101_GUIDE_MD', 'reports/REDUCED_MOTION_101_GUIDE.md'],
  ['GILDED_TOKENS_CATALOGUE_MD_PATH', 'reports/GILDED_TOKENS_CATALOGUE.md'],
  ['REDUCED_MOTION_101_GUIDE_MD_PATH', 'reports/REDUCED_MOTION_101_GUIDE.md'],
  ['REDUCED_MOTION_100_COMPLETE_MD_PATH', 'reports/REDUCED_MOTION_100_COMPLETE.md'],
  ['TYPESCRIPT_FIX_PROGRESS_MD_PATH', 'reports/TYPESCRIPT_FIX_PROGRESS.md'],
  ['REDUCED_MOTION_FINAL_REPORT_JSON_PATH', 'reports/reduced-motion-final-report.json'],
] as const;

// PLAT-115 — the 11 root-exported report-path constants are deprecated:
// reports/ is no longer a tracked artifact directory (evidence lives in CI
// artifacts), so these public path strings are sunset in 5.0.0. Values are
// unchanged for the 4.1.x line.
export default REPORT_PATH_ENTRIES.map(([symbol, value], i) => ({
  id: `DEP-P${String(i + 1).padStart(4, '0')}` as `DEP-P${number}`,
  kind: 'export' as const,
  status: 'planned' as const,
  entry: '.',
  symbol,
  since: '4.2.0' as const,
  removeIn: '5.0.0' as const,
  replacement: null,
  codemod: null,
  automation: 'none' as const,
  breaking: 'B14',
  message: `root export '${symbol}' ("${value}") is a tracked-reports path constant; reports/ is untracked evidence now — drop the import.`,
  doc: `#dep-${symbol.toLowerCase()}`,
})).concat([
  {
    id: 'DEP-P0012',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'enableAdaptiveAI',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'enableAdaptiveAI opt-in flag (adaptive AI is disabled unless explicitly enabled)',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    message: "adaptive AI heuristics now require the explicit 'enableAdaptiveAI' opt-in; unconditional adaptive behavior is removed in 5.0.0.",
    doc: '#dep-enableadaptiveai',
  },
  {
    id: 'DEP-P0013',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCanvas string action execution',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'onComponentAction callback prop',
    codemod: null,
    automation: 'manual',
    breaking: 'B14',
    message: "GlassCanvas no longer executes string-supplied actions; pass 'onComponentAction' to receive dispatched action descriptors.",
    doc: '#dep-glasscanvas-string-actions',
  },
  {
    id: 'DEP-P0014',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'ContrastGuard unconditional pass',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "'unverified' contrast state when a ratio cannot be computed",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    message: "contrast utilities report 'unverified' instead of passing when the ratio is uncomputable; handle the new state before 5.0.0.",
    doc: '#dep-contrast-unverified',
  },
  {
    id: 'DEP-P0016',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'adaptiveAI',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "the explicit 'enableAdaptiveAI' opt-in surface",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy', evidence: 'docs/release/exception-allowlist.json',
    message: "the implicit 'adaptiveAI' export is replaced by the opt-in enableAdaptiveAI surface; implicit adaptive behavior is removed in 5.0.0.",
    doc: '#dep-adaptiveai',
  },
  {
    id: 'DEP-P0017',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAdaptiveAI',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "enableAdaptiveAI opt-in flag + the non-adaptive default hooks",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy', evidence: 'docs/release/exception-allowlist.json',
    message: "'useAdaptiveAI' is superseded by the explicit opt-in path; the implicit adaptive hook is removed in 5.0.0.",
    doc: '#dep-useadaptiveai',
  },
  {
    id: 'DEP-P0018',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'data-meets-wcag attribute',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "'unverified' contrast state + computed data-contrast-state",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'honesty', evidence: 'docs/release/exception-allowlist.json',
    message: "'data-meets-wcag' claimed a guarantee components could not verify; contrast state is now reported honestly via 'unverified'.",
    doc: '#dep-data-meets-wcag',
  },
  {
    id: 'DEP-P0019',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'data-contrast-ratio attribute',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "computed contrast state ('pass' | 'warn' | 'unverified')",
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'honesty', evidence: 'docs/release/exception-allowlist.json',
    message: "'data-contrast-ratio' emitted values for ratios that were not actually computed; consumers should read the honest contrast state instead.",
    doc: '#dep-data-contrast-ratio',
  },
  {
    id: 'DEP-P0020',
    kind: 'prop',
    status: 'planned',
    entry: '.',
    symbol: 'cookie banner auto-display',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'explicit consent-driven visibility (consent gating before display)',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    exception: 'privacy', evidence: 'docs/release/exception-allowlist.json',
    message: "cookie consent banners no longer auto-display before consent state resolves; wire visibility to your consent provider before 5.0.0.",
    doc: '#dep-cookie-banner-auto',
  },
  {
    id: 'DEP-P0021',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'express',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'express' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'express' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-express',
  },
  {
    id: 'DEP-P0022',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'express-rate-limit',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'express-rate-limit' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'express-rate-limit' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-express-rate-limit',
  },
  {
    id: 'DEP-P0023',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'helmet',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'helmet' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'helmet' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-helmet',
  },
  {
    id: 'DEP-P0024',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'cors',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'cors' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'cors' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-cors',
  },
  {
    id: 'DEP-P0025',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'compression',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'compression' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'compression' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-compression',
  },
  {
    id: 'DEP-P0026',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'socket.io',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'socket.io' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'socket.io' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-socket-io',
  },
  {
    id: 'DEP-P0027',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'socket.io-client',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'socket.io-client' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'socket.io-client' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-socket-io-client',
  },
  {
    id: 'DEP-P0028',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'ioredis',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'ioredis' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'ioredis' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-ioredis',
  },
  {
    id: 'DEP-P0029',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'redis',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'redis' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'redis' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-redis',
  },
  {
    id: 'DEP-P0030',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'jsonwebtoken',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'jsonwebtoken' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'jsonwebtoken' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-jsonwebtoken',
  },
  {
    id: 'DEP-P0031',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'bcryptjs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'bcryptjs' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'bcryptjs' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-bcryptjs',
  },
  {
    id: 'DEP-P0032',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'dotenv',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'dotenv' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'dotenv' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-dotenv',
  },
  {
    id: 'DEP-P0033',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'openai',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'openai' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'openai' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-openai',
  },
  {
    id: 'DEP-P0034',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: '@pinecone-database/pinecone',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install '@pinecone-database/pinecone' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'@pinecone-database/pinecone' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-pinecone-database-pinecone',
  },
  {
    id: 'DEP-P0035',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: '@google-cloud/vision',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install '@google-cloud/vision' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'@google-cloud/vision' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-google-cloud-vision',
  },
  {
    id: 'DEP-P0036',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: '@sentry/node',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install '@sentry/node' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'@sentry/node' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-sentry-node',
  },
  {
    id: 'DEP-P0037',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'chart.js',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'chart.js' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'chart.js' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-chart-js',
  },
  {
    id: 'DEP-P0038',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'react-chartjs-2',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'react-chartjs-2' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'react-chartjs-2' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-react-chartjs-2',
  },
  {
    id: 'DEP-P0039',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'date-fns',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'date-fns' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'date-fns' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-date-fns',
  },
  {
    id: 'DEP-P0040',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'zod',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'zod' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'zod' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-zod',
  },
  {
    id: 'DEP-P0041',
    kind: 'dependency',
    status: 'planned',
    entry: '.',
    symbol: 'framer-motion',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "optional peer — install 'framer-motion' only when using the matching feature",
    codemod: 'deps',
    automation: 'partial',
    breaking: 'B14',
    message: "'framer-motion' moved from dependencies to an optional peer; install it yourself or the lazy loader throws at feature call time.",
    doc: '#dep-peer-framer-motion',
  },

  // §14.4 4.2 rows: six ./services/* keys + useGlassProbes (B21 providers below)
  { id: 'DEP-P0042', kind: 'subpath', status: 'planned', entry: './services/ai/config', symbol: 'services/ai/config', since: '4.2.0', removeIn: '5.0.0', replacement: 'aura-glass/services moved to the extracted runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services/ai/config subpath leaves the component package in 5.0.0; migrate to the runtime package.", doc: '#dep-services-ai-config' },
  { id: 'DEP-P0043', kind: 'subpath', status: 'planned', entry: './services/ai/cache-service', symbol: 'services/ai/cache-service', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services/ai/cache-service subpath leaves the component package in 5.0.0.", doc: '#dep-services-ai-cache' },
  { id: 'DEP-P0044', kind: 'subpath', status: 'planned', entry: './services/ai/openai-service', symbol: 'services/ai/openai-service', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services/ai/openai-service subpath leaves the component package in 5.0.0.", doc: '#dep-services-ai-openai' },
  { id: 'DEP-P0045', kind: 'subpath', status: 'planned', entry: './services/ai/vision-service', symbol: 'services/ai/vision-service', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services/ai/vision-service subpath leaves the component package in 5.0.0.", doc: '#dep-services-ai-vision' },
  { id: 'DEP-P0046', kind: 'subpath', status: 'planned', entry: './services/websocket/collaboration-service', symbol: 'services/websocket/collaboration-service', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services/websocket/collaboration-service subpath leaves the component package in 5.0.0.", doc: '#dep-services-websocket-collab' },
  { id: 'DEP-P0047', kind: 'subpath', status: 'planned', entry: './services', symbol: 'services', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./services namespace leaves the component package in 5.0.0.", doc: '#dep-services' },
  { id: 'DEP-P0048', kind: 'subpath', status: 'planned', entry: './hooks/useGlassProbes', symbol: 'useGlassProbes', since: '4.2.0', removeIn: '5.0.0', replacement: 'aura-glass/probes (5.0 runtime probe API)', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./hooks/useGlassProbes subpath is replaced by the 5.0 probe API.", doc: '#dep-useglassprobes' },
  { id: 'DEP-P0049', kind: 'prop', status: 'planned', entry: '.', symbol: 'dead optical props (shimmer, glowIntensity aliases)', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical prop names per the prop-grammar codemod', codemod: 'dead-optical-props', automation: 'full', breaking: 'B20', message: "dead optical props removed in 5.0.0; run the prop-grammar/dead-optical-props codemods.", doc: '#dep-dead-optical-props' },
  { id: 'DEP-P0050', kind: 'prop', status: 'planned', entry: '.', symbol: 'old theme providers (ThemeProvider, GlassThemeProvider, DarkModeProvider, MotionProvider, AnimationProvider)', since: '4.2.0', removeIn: '5.0.0', replacement: 'AuraGlassProvider', codemod: 'providers', automation: 'mostly', breaking: 'B21', message: "the five old theme/motion providers wrap AuraGlassProvider and warn once; migrate to AuraGlassProvider directly.", doc: '#dep-old-providers' },
  { id: 'DEP-P0051', kind: 'subpath', status: 'planned', entry: './navigation', symbol: 'navigation alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical component exports', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./navigation alias subpath is removed in 5.0.0.", doc: '#dep-subpath-navigation' },
  { id: 'DEP-P0052', kind: 'subpath', status: 'planned', entry: './overlays', symbol: 'overlays alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical component exports', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./overlays alias subpath is removed in 5.0.0.", doc: '#dep-subpath-overlays' },
  { id: 'DEP-P0053', kind: 'subpath', status: 'planned', entry: './marketing', symbol: 'marketing alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical component exports', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./marketing alias subpath is removed in 5.0.0.", doc: '#dep-subpath-marketing' },
  { id: 'DEP-P0054', kind: 'subpath', status: 'planned', entry: './workflows', symbol: 'workflows alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical component exports', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./workflows alias subpath is removed in 5.0.0.", doc: '#dep-subpath-workflows' },
  { id: 'DEP-P0055', kind: 'subpath', status: 'planned', entry: './workspace', symbol: 'workspace alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'canonical component exports', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./workspace alias subpath is removed in 5.0.0.", doc: '#dep-subpath-workspace' },
  { id: 'DEP-P0056', kind: 'subpath', status: 'planned', entry: './client', symbol: 'client alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: "'use client' entry contract", codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./client alias subpath is removed in 5.0.0.", doc: '#dep-subpath-client' },
  { id: 'DEP-P0057', kind: 'subpath', status: 'planned', entry: './ssr', symbol: 'ssr alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: '5.0 server-safe entry', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: "the ./ssr alias subpath is removed in 5.0.0.", doc: '#dep-subpath-ssr' },
  { id: 'DEP-P0058', kind: 'subpath', status: 'planned', entry: './server', symbol: 'server alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: 'runtime package', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./server alias subpath is removed in 5.0.0.", doc: '#dep-subpath-server' },
  { id: 'DEP-P0059', kind: 'subpath', status: 'planned', entry: './registry', symbol: 'registry alias subpath', since: '4.2.0', removeIn: '5.0.0', replacement: '5.0 recipe registry', codemod: 'imports-subpaths', automation: 'mostly', breaking: 'B14', message: "the ./registry alias subpath is removed in 5.0.0.", doc: '#dep-subpath-registry' },
  {
    id: 'DEP-P0015',
    kind: 'css-global',
    status: 'planned',
    entry: '.',
    symbol: '--glass-font-sans (Aeonik)',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'system stack: system-ui, -apple-system, "Segoe UI", sans-serif',
    codemod: null,
    automation: 'none',
    breaking: 'B14',
    message: "the bundled Aeonik family is removed (licence unconfirmed, D-31); '--glass-font-sans' resolves to the platform system stack.",
    doc: '#dep-aeonik-font-stack',
  },
  { id: 'DEP-P0060', kind: 'subpath', status: 'planned', entry: 'bin/aura-glass.cjs', symbol: 'aura-glass bin', since: '4.3.0', removeIn: '5.0.0', replacement: 'npx @auraglass/cli', codemod: null, automation: 'none', breaking: 'B21', exception: 'honesty', evidence: 'docs/release/exception-allowlist.json', message: 'the bundled aura-glass CLI moved to @auraglass/cli in 5.0.0.', doc: '#dep-bin-aura-glass' },
  { id: 'DEP-P0061', kind: 'subpath', status: 'planned', entry: './styles', symbol: 'styles subpath', since: '4.3.0', removeIn: '5.0.0', replacement: './styles/v5.css', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./styles subpath is replaced by ./styles/v5.css in 5.0.0.', doc: '#dep-subpath-styles' },
  { id: 'DEP-P0062', kind: 'subpath', status: 'planned', entry: './tokens/css', symbol: 'tokens css subpath', since: '4.3.0', removeIn: '5.0.0', replacement: '5.0 tokens css', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./tokens/css subpath moves to the 5.0 token table.', doc: '#dep-subpath-tokens-css' },
  { id: 'DEP-P0063', kind: 'subpath', status: 'planned', entry: './tokens/tailwind', symbol: 'tailwind theme subpath', since: '4.3.0', removeIn: '5.0.0', replacement: '5.0 tailwind preset', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./tokens/tailwind subpath moves to the 5.0 preset.', doc: '#dep-subpath-tokens-tailwind' },
  { id: 'DEP-P0064', kind: 'subpath', status: 'planned', entry: './tokens/json', symbol: 'tokens json subpath', since: '4.3.0', removeIn: '5.0.0', replacement: '5.0 tokens manifest', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./tokens/json subpath moves to the 5.0 manifest.', doc: '#dep-subpath-tokens-json' },
  { id: 'DEP-P0065', kind: 'subpath', status: 'planned', entry: './tokens/manifest', symbol: 'tokens manifest subpath', since: '4.3.0', removeIn: '5.0.0', replacement: '5.0 tokens manifest', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./tokens/manifest subpath moves to the 5.0 manifest.', doc: '#dep-subpath-tokens-manifest' },
  { id: 'DEP-P0066', kind: 'export', status: 'planned', entry: './primitives/*', symbol: 'per-primitive deep imports', since: '4.3.0', removeIn: '5.0.0', replacement: 'root export', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'deep ./primitives/<name> imports move to the root export in 5.0.0.', doc: '#dep-deep-primitives' },
  { id: 'DEP-P0067', kind: 'export', status: 'planned', entry: './icons/*', symbol: 'per-category icon imports', since: '4.3.0', removeIn: '5.0.0', replacement: './icons root', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'deep ./icons/<category> imports move to ./icons in 5.0.0.', doc: '#dep-deep-icons' },
  { id: 'DEP-P0068', kind: 'export', status: 'planned', entry: './utils/env', symbol: 'utils env subpath', since: '4.3.0', removeIn: '5.0.0', replacement: '5.0 env helper', codemod: 'imports-subpaths', automation: 'full', breaking: 'B14', message: 'the ./utils/env subpath is removed in 5.0.0.', doc: '#dep-utils-env' },
  { id: 'DEP-P0069', kind: 'behavior', status: 'planned', entry: '.', symbol: 'CJS/require entry', since: '4.3.0', removeIn: '5.0.0', replacement: 'ESM entry only', codemod: null, automation: 'none', breaking: 'B21', message: 'the CommonJS require() entry is removed in 5.0.0; consume the ESM build.', doc: '#dep-cjs-entry' },
  { id: 'DEP-P0070', kind: 'peer', status: 'planned', entry: '.', symbol: 'react@18', since: '4.3.0', removeIn: '5.0.0', replacement: 'react@19', codemod: null, automation: 'none', breaking: 'B21', message: 'React 18 support ends with 5.0.0; React 19 is the floor.', doc: '#dep-peer-react18' },
  { id: 'DEP-P0071', kind: 'engine', status: 'planned', entry: '.', symbol: 'node < 20.19', since: '4.3.0', removeIn: '5.0.0', replacement: 'node >= 20.19', codemod: null, automation: 'none', breaking: 'B21', message: 'Node < 20.19 support ends with 5.0.0.', doc: '#dep-engine-node-20-19' },
  {
    id: 'DEP-P0072',
    kind: 'peer',
    status: 'active',
    entry: '.',
    symbol: 'React ^19.0 floor',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B1',
    message: 'React ^19.0 floor — see the migration guide (#b-1).',
    doc: '#dep-1',
  },
  {
    id: 'DEP-P0073',
    kind: 'engine',
    status: 'active',
    entry: '.',
    symbol: 'ESM-only, Node >=20.19',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B2',
    message: 'ESM-only, Node >=20.19 — see the migration guide (#b-2).',
    doc: '#dep-2',
  },
  {
    id: 'DEP-P0074',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'New default material (every surface changes pixels)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B11',
    message: 'New default material (every surface changes pixels) — see the migration guide (#b-11).',
    doc: '#dep-11',
  },
  {
    id: 'DEP-P0075',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Content layer is no longer glass by default',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B12',
    message: 'Content layer is no longer glass by default — see the migration guide (#b-12).',
    doc: '#dep-12',
  },
  {
    id: 'DEP-P0076',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'OS signals are floors; reduced motion cannot be overridden',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B13',
    message: 'OS signals are floors; reduced motion cannot be overridden — see the migration guide (#b-13).',
    doc: '#dep-13',
  },
  {
    id: 'DEP-P0077',
    kind: 'cli',
    status: 'active',
    entry: '.',
    symbol: 'CLI moved to @auraglass/cli',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B15',
    message: 'CLI moved to @auraglass/cli — see the migration guide (#b-15).',
    doc: '#dep-15',
  },
  {
    id: 'DEP-P0078',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'ssr/server shims removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B16',
    message: 'ssr/server shims removed — see the migration guide (#b-16).',
    doc: '#dep-16',
  },
  {
    id: 'DEP-P0079',
    kind: 'asset',
    status: 'active',
    entry: '.',
    symbol: 'Asset subpath renames (icons/env/json/manifest namespaces)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B17',
    message: 'Asset subpath renames (icons/env/json/manifest namespaces) — see the migration guide (#b-17).',
    doc: '#dep-17',
  },
  {
    id: 'DEP-P0080',
    kind: 'behavior',
    status: 'active',
    entry: '.',
    symbol: 'Primitives collapse (4.x primitive set folds into the 5.0 primitives entry)',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B18',
    message: 'Primitives collapse (4.x primitive set folds into the 5.0 primitives entry) — see the migration guide (#b-18).',
    doc: '#dep-18',
  },
  {
    id: 'DEP-P0081',
    kind: 'asset',
    status: 'active',
    entry: '.',
    symbol: 'Icons, env vars, .json/.css manifest subpaths removed',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'none',
    breaking: 'B19',
    message: 'Icons, env vars, .json/.css manifest subpaths removed — see the migration guide (#b-19).',
    doc: '#dep-19',
  },
]) satisfies DeprecationFragment;
