// deprecations fragment for SURF (contract S-38). Lane blocks are owned by SURF
// lanes W1..W5; edit only your own block. Id ranges: W1 DEP-S0001..S0199,
// W2 DEP-S0200..S0399, W3 DEP-S0400..S0599, W4 DEP-S0600..S0799,
// W5 DEP-S0800..S0999 (SURF-632). This file lives on release/4.x; the daily
// PLAT sync mirrors it to next where it is read-only (REQ-SURF-12).
import type { DeprecationFragment } from '../../src/contracts/fragments';

// --- lane W1 begin ---
// W1 rows: every absorbed 4.x shell/navigation export (PROMPT-4a SURF-112).
// Each keeps working in 5.x through its aura-glass/compat adapter; removal
// lands at 6.0.0 per the migration window. `status: 'planned'` holds until
// PLAT's release tooling publishes 4.2.0.
const w1 = [
  {
    id: 'DEP-S0001',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAppShell',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassAppShell is removed in 5.0; use the AppShell entry and migrate slot props to slot children.',
    doc: '#dep-s0001',
    compat: 'GlassAppShell',
  },
  {
    id: 'DEP-S0002',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassHeader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TopBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassHeader is removed in 5.0; use TopBar — AppShell.SidebarToggle replaces the built-in burger.',
    doc: '#dep-s0002',
    compat: 'GlassHeader',
  },
  {
    id: 'DEP-S0003',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTopBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TopBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTopBar is removed in 5.0; use TopBar inside AppShell.Root.',
    doc: '#dep-s0003',
    compat: 'GlassTopBar',
  },
  {
    id: 'DEP-S0004',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSidebar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Sidebar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassSidebar is removed in 5.0; use Sidebar with Sidebar.Nav/Sidebar.Item children.',
    doc: '#dep-s0004',
    compat: 'GlassSidebar',
  },
  {
    id: 'DEP-S0005',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMain',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell.Main from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMain is removed in 5.0; use AppShell.Main inside AppShell.Root.',
    doc: '#dep-s0005',
    compat: 'GlassMain',
  },
  {
    id: 'DEP-S0006',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPageHeader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell.PageHeader from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPageHeader is removed in 5.0; use AppShell.PageHeader.',
    doc: '#dep-s0006',
    compat: 'GlassPageHeader',
  },
  {
    id: 'DEP-S0007',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassStatusBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatusBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassStatusBar is removed in 5.0; use StatusBar inside AppShell.Root.',
    doc: '#dep-s0007',
    compat: 'GlassStatusBar',
  },
  {
    id: 'DEP-S0008',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassInspector',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Inspector from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassInspector is removed in 5.0; use Inspector inside AppShell.Root.',
    doc: '#dep-s0008',
    compat: 'GlassInspector',
  },
  {
    id: 'DEP-S0009',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMobileShell',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'MobileShell from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMobileShell is removed in 5.0; use MobileShell.',
    doc: '#dep-s0009',
    compat: 'GlassMobileShell',
  },
  {
    id: 'DEP-S0010',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ZSpaceAppLayout',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell composition',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'ZSpaceAppLayout is removed in 5.0; the AppShell composition replaces z-depth layouts.',
    doc: '#dep-s0010',
    compat: 'ZSpaceAppLayout',
  },
  {
    id: 'DEP-S0011',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTabs is removed in 5.0; use Tabs with Tabs.List/Tabs.Tab/Tabs.Panel.',
    doc: '#dep-s0011',
    compat: 'GlassTabs',
  },
  {
    id: 'DEP-S0012',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPageTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPageTabs is removed in 5.0; use Tabs inside AppShell.PageHeader actions.',
    doc: '#dep-s0012',
    compat: 'GlassPageTabs',
  },
  {
    id: 'DEP-S0013',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTabBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTabBar is removed in 5.0; use TabBar.',
    doc: '#dep-s0013',
    compat: 'GlassTabBar',
  },
  {
    id: 'DEP-S0014',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassWorkspaceTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassWorkspaceTabs is removed in 5.0; use Tabs.',
    doc: '#dep-s0014',
    compat: 'GlassWorkspaceTabs',
  },
  {
    id: 'DEP-S0015',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassTabBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassTabBar is removed in 5.0; use TabBar with material variants.',
    doc: '#dep-s0015',
    compat: 'LiquidGlassTabBar',
  },
  {
    id: 'DEP-S0016',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassBottomNav',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassBottomNav is removed in 5.0; use TabBar in the MobileShell tabBar slot.',
    doc: '#dep-s0016',
    compat: 'GlassBottomNav',
  },
  {
    id: 'DEP-S0017',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassBottomAccessory',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar accessory',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassBottomAccessory is removed in 5.0; use TabBar accessory slot.',
    doc: '#dep-s0017',
    compat: 'LiquidGlassBottomAccessory',
  },
  {
    id: 'DEP-S0018',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMobileNav',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SidebarDrawer from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMobileNav is removed in 5.0; Sidebar.Drawer provides the overlay navigation.',
    doc: '#dep-s0018',
    compat: 'GlassMobileNav',
  },
  {
    id: 'DEP-S0019',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassBreadcrumb',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Breadcrumbs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassBreadcrumb is removed in 5.0; use Breadcrumbs.',
    doc: '#dep-s0019',
    compat: 'GlassBreadcrumb',
  },
  {
    id: 'DEP-S0020',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPagination',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Pagination from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPagination is removed in 5.0; use Pagination (currentPage->page, totalPages->pageCount).',
    doc: '#dep-s0020',
    compat: 'GlassPagination',
  },
  {
    id: 'DEP-S0021',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommandPalette',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CommandPalette from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassCommandPalette is removed in 5.0; use CommandPalette.',
    doc: '#dep-s0021',
    compat: 'GlassCommandPalette',
  },
  {
    id: 'DEP-S0022',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommand',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Command from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassCommand is removed in 5.0; use Command.',
    doc: '#dep-s0022',
    compat: 'GlassCommand',
  },
  {
    id: 'DEP-S0023',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassCommandSurface',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CommandPalette from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassCommandSurface is removed in 5.0; use CommandPalette.',
    doc: '#dep-s0023',
    compat: 'LiquidGlassCommandSurface',
  },
  {
    id: 'DEP-S0024',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassTransitionProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassTransitionProvider is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0024',
    compat: 'LiquidGlassTransitionProvider',
  },
  {
    id: 'DEP-S0025',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassSource',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition.Source from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassSource is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0025',
    compat: 'LiquidGlassSource',
  },
  {
    id: 'DEP-S0026',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassDestination',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition.Destination from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassDestination is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0026',
    compat: 'LiquidGlassDestination',
  },
] as const;
// --- lane W1 end ---

// --- lane W2 begin ---
const w2 = [] as const;
// --- lane W2 end ---

// --- lane W3 begin ---
const w3 = [] as const;
// --- lane W3 end ---

// --- lane W4 begin ---
const w4 = [] as const;
// --- lane W4 end ---

// --- lane W5 begin ---
// W5 rows cover the ./workspace and ./workflows 4.x subpaths and the
// commerce/presence/comment 4.x exports (Prompt-4 W5 step 3). All ship in the
// 4.2.0 minor: `status: 'planned'` stays until PLAT's release tooling
// publishes 4.2.0 (verify-deprecations fails 'active' when since > line
// version and 'planned' when since <= it).
const w5 = [
  {
    id: 'DEP-S0800',
    kind: 'subpath',
    status: 'planned',
    entry: './workspace',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "aura-glass/app-shell (the 5.x AppShell composition replaces the 4.x workspace layout subpath)",
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      "aura-glass/workspace is removed in 5.0; migrate to aura-glass/app-shell — the AppShell composition replaces the workspace layout subpath.",
    doc: '#dep-s0800',
  },
  {
    id: 'DEP-S0801',
    kind: 'subpath',
    status: 'planned',
    entry: './workflows',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/app-shell workspace recipes and the 5.x registry blocks',
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      'aura-glass/workflows is removed in 5.0; the app-shell workspace recipes and 5.x registry blocks replace every export this subpath re-exported.',
    doc: '#dep-s0801',
  },
  {
    id: 'DEP-S0802',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'SmartShoppingCart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassSmartShoppingCart until 5.0, then the commerce-cart registry block (5.1)',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B3',
    message:
      'The SmartShoppingCart alias is removed in 5.0; it is the same component as GlassSmartShoppingCart, which itself is replaced by the commerce-cart registry block (5.1).',
    doc: '#dep-s0802',
  },
  {
    id: 'DEP-S0803',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommentThread',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the comment-thread registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassCommentThread is removed in 5.0; use the comment-thread registry item (5.1), the single comment surface consolidated from the 4.x duplicates.',
    doc: '#dep-s0803',
  },
  {
    id: 'DEP-S0804',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSmartShoppingCart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the commerce-cart registry block (5.1): controlled cart UI with no baked-in business logic',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassSmartShoppingCart is removed in 5.0; use the commerce-cart registry block (5.1) — controlled cart UI that holds no discounts, tax or currency logic.',
    doc: '#dep-s0804',
  },
  {
    id: 'DEP-S0805',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassProductRecommendations',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the commerce registry blocks (5.1) composed on Card and CarouselRail',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassProductRecommendations is removed in 5.0; compose the commerce registry blocks (5.1) on Card and CarouselRail instead.',
    doc: '#dep-s0805',
  },
  {
    id: 'DEP-S0806',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassEcommerceProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'consumer-owned commerce state; the 5.x commerce registry blocks take data by props',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassEcommerceProvider is removed in 5.0; keep commerce state in your app — the 5.x commerce registry blocks take data by props only.',
    doc: '#dep-s0806',
  },
  {
    id: 'DEP-S0807',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTeamCursors',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassTeamCursors is removed in 5.0; use the presence-stack registry item (5.1) — it only drew three fake cursors with no data input.',
    doc: '#dep-s0807',
  },
  {
    id: 'DEP-S0808',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTeamCursorsWithEffects',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassTeamCursorsWithEffects is removed in 5.0; use the presence-stack registry item (5.1) — the effect variant layered static circles on fake cursors.',
    doc: '#dep-s0808',
  },
  {
    id: 'DEP-S0809',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCollaborativeComments',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the comment-thread registry item (5.1) plus an anchored-popover pin primitive',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassCollaborativeComments is removed in 5.0; use the comment-thread registry item (5.1) — spatial pins become an anchored-popover primitive.',
    doc: '#dep-s0809',
  },
  {
    id: 'DEP-S0810',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassUserPresence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassUserPresence is removed in 5.0; use the presence-stack registry item (5.1) — deterministic ids replace its random presence colours.',
    doc: '#dep-s0810',
  },
  {
    id: 'DEP-S0811',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPresenceIndicator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassPresenceIndicator is removed in 5.0; use the presence-stack registry item (5.1).',
    doc: '#dep-s0811',
  },
  {
    id: 'DEP-S0812',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLiveCursorPresence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1) fed by consumer presence data',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassLiveCursorPresence is removed in 5.0; render live cursors from your own presence channel through the presence-stack registry item (5.1).',
    doc: '#dep-s0812',
  },
  {
    id: 'DEP-S0813',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCollaborativeCursor',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1) fed by consumer presence data',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassCollaborativeCursor is removed in 5.0; render live cursors from your own presence channel through the presence-stack registry item (5.1).',
    doc: '#dep-s0813',
  },
] as const;
// --- lane W5 end ---

export default [...w1, ...w2, ...w3, ...w4, ...w5] satisfies DeprecationFragment;
