/* fragments/deprecations/surf.ts — SURF owns this file on both branches (§3.4).
   W4 rows are mirrored from release/4.x now; the sync job overwrites this file
   with the generated fragment (which will contain every lane's rows). */
import type { DeprecationFragment } from '../../src/contracts/fragments';

// --- lane W4 begin ---
// W4 rows (SURF-632, lane W4 block): the 4.x media/backdrop family. The 14
// adapters keep working through aura-glass/compat until 6.0.0; removed names
// map to registry items, native elements, the labs ParticleField, or the
// 5.1 Waveform.
const w4 = [
  {
    id: 'DEP-S0600',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassMediaControls',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'MediaControls.Root from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassMediaControls is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to MediaControls.Root from aura-glass/media.',
    doc: '#dep-s0600',
    compat: 'LiquidGlassMediaControls',
  },
  {
    id: 'DEP-S0601',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMediaControls',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'MediaControls.Root from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassMediaControls is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to MediaControls.Root from aura-glass/media.',
    doc: '#dep-s0601',
    compat: 'GlassMediaControls',
  },
  {
    id: 'DEP-S0602',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassNowPlayingBar',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'NowPlayingBar from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassNowPlayingBar is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to NowPlayingBar from aura-glass/media.',
    doc: '#dep-s0602',
    compat: 'LiquidGlassNowPlayingBar',
  },
  {
    id: 'DEP-S0603',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassPhotoInspector',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'ImageViewer + Inspector from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassPhotoInspector is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to ImageViewer + Inspector from aura-glass/media.',
    doc: '#dep-s0603',
    compat: 'LiquidGlassPhotoInspector',
  },
  {
    id: 'DEP-S0604',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassImageViewer',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'ImageViewer from aura-glass/media (items need id + required alt)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassImageViewer is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to ImageViewer from aura-glass/media (items need id + required alt).',
    doc: '#dep-s0604',
    compat: 'GlassImageViewer',
  },
  {
    id: 'DEP-S0605',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassGallery',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'ImageViewer from aura-glass/media (or the media-gallery registry item)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassGallery is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to ImageViewer from aura-glass/media (or the media-gallery registry item).',
    doc: '#dep-s0605',
    compat: 'GlassGallery',
  },
  {
    id: 'DEP-S0606',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCarousel',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'CarouselRail from aura-glass/media (infinite to loop, autoPlay gated)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassCarousel is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to CarouselRail from aura-glass/media (infinite to loop, autoPlay gated).',
    doc: '#dep-s0606',
    compat: 'GlassCarousel',
  },
  {
    id: 'DEP-S0607',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassCarouselRail',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'CarouselRail from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassCarouselRail is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to CarouselRail from aura-glass/media.',
    doc: '#dep-s0607',
    compat: 'LiquidGlassCarouselRail',
  },
  {
    id: 'DEP-S0608',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AuroraBackground',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="aurora" from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AuroraBackground is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop preset="aurora" from aura-glass/backdrops.',
    doc: '#dep-s0608',
    compat: 'AuroraBackground',
  },
  {
    id: 'DEP-S0609',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AuroraOrb',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="aurora" from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AuroraOrb is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop preset="aurora" from aura-glass/backdrops.',
    doc: '#dep-s0609',
    compat: 'AuroraOrb',
  },
  {
    id: 'DEP-S0610',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AtmosphericBackground',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AtmosphericBackground is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0610',
    compat: 'AtmosphericBackground',
  },
  {
    id: 'DEP-S0611',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDynamicAtmosphere',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassDynamicAtmosphere is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0611',
    compat: 'GlassDynamicAtmosphere',
  },
  {
    id: 'DEP-S0612',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'DynamicAtmosphere',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'DynamicAtmosphere is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0612',
    compat: 'GlassDynamicAtmosphere',
  },
  {
    id: 'DEP-S0613',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMeshGradient',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="mesh" from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassMeshGradient is removed from aura-glass in 5.0; the aura-glass/compat adapter works until 6.0.0. Migrate to Backdrop preset="mesh" from aura-glass/backdrops.',
    doc: '#dep-s0613',
    compat: 'GlassMeshGradient',
  },
  {
    id: 'DEP-S0614',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageList',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native img',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageList is removed in 5.0; CMP Grid + native img.',
    doc: '#dep-s0614',
  },
  {
    id: 'DEP-S0615',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageListItem',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native img',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageListItem is removed in 5.0; CMP Grid + native img.',
    doc: '#dep-s0615',
  },
  {
    id: 'DEP-S0616',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageListItemBar',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native img',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageListItemBar is removed in 5.0; CMP Grid + native img.',
    doc: '#dep-s0616',
  },
  {
    id: 'DEP-S0617',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLazyImage',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'native img loading="lazy"',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassLazyImage is removed in 5.0; native img loading="lazy".',
    doc: '#dep-s0617',
  },
  {
    id: 'DEP-S0618',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVideoPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-video-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassVideoPlayer is removed in 5.0; the media-video-player registry item.',
    doc: '#dep-s0618',
  },
  {
    id: 'DEP-S0619',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvancedVideoPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-video-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassAdvancedVideoPlayer is removed in 5.0; the media-video-player registry item.',
    doc: '#dep-s0619',
  },
  {
    id: 'DEP-S0620',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvancedAudioPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-audio-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassAdvancedAudioPlayer is removed in 5.0; the media-audio-player registry item.',
    doc: '#dep-s0620',
  },
  {
    id: 'DEP-S0621',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMediaProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useMediaElement from aura-glass/media',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMediaProvider is removed in 5.0; useMediaElement from aura-glass/media.',
    doc: '#dep-s0621',
  },
  {
    id: 'DEP-S0622',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVoiceWaveform',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'no successor until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassVoiceWaveform is removed in 5.0; no successor until 5.1 (Waveform).',
    doc: '#dep-s0622',
  },
  {
    id: 'DEP-S0623',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMusicVisualizer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'no successor until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMusicVisualizer is removed in 5.0; no successor until 5.1 (Waveform).',
    doc: '#dep-s0623',
  },
  {
    id: 'DEP-S0624',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ParticleBackground',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ParticleBackground is removed in 5.0; the labs ParticleField (seeded PRNG).',
    doc: '#dep-s0624',
  },
  {
    id: 'DEP-S0625',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassParticles',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassParticles is removed in 5.0; the labs ParticleField (seeded PRNG).',
    doc: '#dep-s0625',
  },
  {
    id: 'DEP-S0626',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassParticleField',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassParticleField is removed in 5.0; the labs ParticleField (seeded PRNG).',
    doc: '#dep-s0626',
  },
  {
    id: 'DEP-S0627',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AuroraPro',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop preset="aurora"',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'AuroraPro is removed in 5.0; Backdrop preset="aurora".',
    doc: '#dep-s0627',
  },
  {
    id: 'DEP-S0628',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'SeasonalParticles',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop presets; particles live in labs',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'SeasonalParticles is removed in 5.0; Backdrop presets; particles live in labs.',
    doc: '#dep-s0628',
  },
  {
    id: 'DEP-S0629',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAuroraDisplay',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop preset="aurora"',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassAuroraDisplay is removed in 5.0; Backdrop preset="aurora".',
    doc: '#dep-s0629',
  },
  {
    id: 'DEP-S0630',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassNebulaClouds',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop presets aurora/mesh',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassNebulaClouds is removed in 5.0; Backdrop presets aurora/mesh.',
    doc: '#dep-s0630',
  },
  {
    id: 'DEP-S0631',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassBackdropSampler',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop + useMediaElement({ sampleTone: true })',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'LiquidGlassBackdropSampler is removed in 5.0; Backdrop + useMediaElement({ sampleTone: true }).',
    doc: '#dep-s0631',
  },
  {
    id: 'DEP-S0632',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useLiquidGlassBackdrop',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop + useMediaElement({ sampleTone: true })',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'useLiquidGlassBackdrop is removed in 5.0; Backdrop + useMediaElement({ sampleTone: true }).',
    doc: '#dep-s0632',
  },
] as const;
// --- lane W4 end ---

export default [...w4] satisfies DeprecationFragment;
