// deprecations fragment for SURF (contract S-38). Lane blocks are owned by SURF
// lanes W1..W5; edit only your own block. Id ranges: W1 DEP-S0001..S0199,
// W2 DEP-S0200..S0399, W3 DEP-S0400..S0599, W4 DEP-S0600..S0799,
// W5 DEP-S0800..S0999 (SURF-632). This file lives on release/4.x; the daily
// PLAT sync mirrors it to next where it is read-only (REQ-SURF-12).
import type { DeprecationFragment } from '../../src/contracts/fragments';

// --- lane W1 begin ---
// W1 rows: every absorbed 4.x shell/navigation export (PROMPT-4a SURF-112).
// Each keeps working in 5.x through its aura-glass/compat adapter; removal
// lands at 6.0.0 per the migration window. `status: 'planned'` holds until
// PLAT's release tooling publishes 4.2.0.
const w1 = [
  {
    id: 'DEP-S0001',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAppShell',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassAppShell is removed in 5.0; use the AppShell entry and migrate slot props to slot children.',
    doc: '#dep-s0001',
    compat: 'GlassAppShell',
  },
  {
    id: 'DEP-S0002',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassHeader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TopBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassHeader is removed in 5.0; use TopBar — AppShell.SidebarToggle replaces the built-in burger.',
    doc: '#dep-s0002',
    compat: 'GlassHeader',
  },
  {
    id: 'DEP-S0003',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTopBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TopBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTopBar is removed in 5.0; use TopBar inside AppShell.Root.',
    doc: '#dep-s0003',
    compat: 'GlassTopBar',
  },
  {
    id: 'DEP-S0004',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSidebar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Sidebar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassSidebar is removed in 5.0; use Sidebar with Sidebar.Nav/Sidebar.Item children.',
    doc: '#dep-s0004',
    compat: 'GlassSidebar',
  },
  {
    id: 'DEP-S0005',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMain',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell.Main from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMain is removed in 5.0; use AppShell.Main inside AppShell.Root.',
    doc: '#dep-s0005',
    compat: 'GlassMain',
  },
  {
    id: 'DEP-S0006',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPageHeader',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell.PageHeader from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPageHeader is removed in 5.0; use AppShell.PageHeader.',
    doc: '#dep-s0006',
    compat: 'GlassPageHeader',
  },
  {
    id: 'DEP-S0007',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassStatusBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatusBar from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassStatusBar is removed in 5.0; use StatusBar inside AppShell.Root.',
    doc: '#dep-s0007',
    compat: 'GlassStatusBar',
  },
  {
    id: 'DEP-S0008',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassInspector',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Inspector from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassInspector is removed in 5.0; use Inspector inside AppShell.Root.',
    doc: '#dep-s0008',
    compat: 'GlassInspector',
  },
  {
    id: 'DEP-S0009',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMobileShell',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'MobileShell from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMobileShell is removed in 5.0; use MobileShell.',
    doc: '#dep-s0009',
    compat: 'GlassMobileShell',
  },
  {
    id: 'DEP-S0010',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ZSpaceAppLayout',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'AppShell composition',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'ZSpaceAppLayout is removed in 5.0; the AppShell composition replaces z-depth layouts.',
    doc: '#dep-s0010',
    compat: 'ZSpaceAppLayout',
  },
  {
    id: 'DEP-S0011',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTabs is removed in 5.0; use Tabs with Tabs.List/Tabs.Tab/Tabs.Panel.',
    doc: '#dep-s0011',
    compat: 'GlassTabs',
  },
  {
    id: 'DEP-S0012',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPageTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPageTabs is removed in 5.0; use Tabs inside AppShell.PageHeader actions.',
    doc: '#dep-s0012',
    compat: 'GlassPageTabs',
  },
  {
    id: 'DEP-S0013',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTabBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassTabBar is removed in 5.0; use TabBar.',
    doc: '#dep-s0013',
    compat: 'GlassTabBar',
  },
  {
    id: 'DEP-S0014',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassWorkspaceTabs',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Tabs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassWorkspaceTabs is removed in 5.0; use Tabs.',
    doc: '#dep-s0014',
    compat: 'GlassWorkspaceTabs',
  },
  {
    id: 'DEP-S0015',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassTabBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassTabBar is removed in 5.0; use TabBar with material variants.',
    doc: '#dep-s0015',
    compat: 'LiquidGlassTabBar',
  },
  {
    id: 'DEP-S0016',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassBottomNav',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassBottomNav is removed in 5.0; use TabBar in the MobileShell tabBar slot.',
    doc: '#dep-s0016',
    compat: 'GlassBottomNav',
  },
  {
    id: 'DEP-S0017',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassBottomAccessory',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TabBar accessory',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassBottomAccessory is removed in 5.0; use TabBar accessory slot.',
    doc: '#dep-s0017',
    compat: 'LiquidGlassBottomAccessory',
  },
  {
    id: 'DEP-S0018',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMobileNav',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SidebarDrawer from aura-glass/app-shell',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassMobileNav is removed in 5.0; Sidebar.Drawer provides the overlay navigation.',
    doc: '#dep-s0018',
    compat: 'GlassMobileNav',
  },
  {
    id: 'DEP-S0019',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassBreadcrumb',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Breadcrumbs from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassBreadcrumb is removed in 5.0; use Breadcrumbs.',
    doc: '#dep-s0019',
    compat: 'GlassBreadcrumb',
  },
  {
    id: 'DEP-S0020',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPagination',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Pagination from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassPagination is removed in 5.0; use Pagination (currentPage->page, totalPages->pageCount).',
    doc: '#dep-s0020',
    compat: 'GlassPagination',
  },
  {
    id: 'DEP-S0021',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommandPalette',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CommandPalette from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassCommandPalette is removed in 5.0; use CommandPalette.',
    doc: '#dep-s0021',
    compat: 'GlassCommandPalette',
  },
  {
    id: 'DEP-S0022',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommand',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Command from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'GlassCommand is removed in 5.0; use Command.',
    doc: '#dep-s0022',
    compat: 'GlassCommand',
  },
  {
    id: 'DEP-S0023',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassCommandSurface',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'CommandPalette from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassCommandSurface is removed in 5.0; use CommandPalette.',
    doc: '#dep-s0023',
    compat: 'LiquidGlassCommandSurface',
  },
  {
    id: 'DEP-S0024',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassTransitionProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassTransitionProvider is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0024',
    compat: 'LiquidGlassTransitionProvider',
  },
  {
    id: 'DEP-S0025',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassSource',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition.Source from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassSource is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0025',
    compat: 'LiquidGlassSource',
  },
  {
    id: 'DEP-S0026',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassDestination',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'SourceTransition.Destination from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B4',
    message: 'LiquidGlassDestination is removed in 5.0; use SourceTransition.',
    doc: '#dep-s0026',
    compat: 'LiquidGlassDestination',
  },
] as const;
// --- lane W1 end ---

// --- lane W2 begin ---
// W2 rows: every absorbed 4.x data/date/charts export (PROMPT-4b SURF-256..264).
// Renames keep working in 5.x through their aura-glass/compat adapter (`compat`);
// the removed chart widgets have no 5.0 equivalent — the ./charts entry (Chart)
// ships at ga 5.1. `status: 'planned'` holds until PLAT's release tooling
// publishes 4.2.0.
const w2 = [
  {
    id: 'DEP-S0200',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDataTable',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Table from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassDataTable is removed in 5.0; use Table from aura-glass/data.',
    doc: '#dep-s0200',
    compat: 'GlassDataTable',
  },
  {
    id: 'DEP-S0201',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDataGrid',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Table from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassDataGrid is removed in 5.0; use Table from aura-glass/data.',
    doc: '#dep-s0201',
    compat: 'GlassDataGrid',
  },
  {
    id: 'DEP-S0202',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVirtualTable',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Table with virtualize from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassVirtualTable is removed in 5.0; use Table with virtualize from aura-glass/data.',
    doc: '#dep-s0202',
    compat: 'GlassVirtualTable',
  },
  {
    id: 'DEP-S0203',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVirtualList',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Table virtualization primitives',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassVirtualList is removed in 5.0; use Table virtualization primitives.',
    doc: '#dep-s0203',
    compat: 'GlassVirtualList',
  },
  {
    id: 'DEP-S0204',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTreeView',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TreeView from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassTreeView is removed in 5.0; use TreeView from aura-glass/data.',
    doc: '#dep-s0204',
    compat: 'GlassTreeView',
  },
  {
    id: 'DEP-S0205',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'TreeView',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TreeView from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'TreeView is removed in 5.0; use TreeView from aura-glass/data.',
    doc: '#dep-s0205',
    compat: 'TreeView4x',
  },
  {
    id: 'DEP-S0206',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFileTree',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TreeView from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassFileTree is removed in 5.0; use TreeView from aura-glass/data.',
    doc: '#dep-s0206',
    compat: 'GlassFileTree',
  },
  {
    id: 'DEP-S0207',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFileExplorer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TreeView from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassFileExplorer is removed in 5.0; use TreeView from aura-glass/data.',
    doc: '#dep-s0207',
    compat: 'GlassFileExplorer',
  },
  {
    id: 'DEP-S0208',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFilterBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'FilterBar from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassFilterBar is removed in 5.0; use FilterBar from aura-glass/data.',
    doc: '#dep-s0208',
    compat: 'GlassFilterBar',
  },
  {
    id: 'DEP-S0209',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSearchBar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'FilterBar search slot from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassSearchBar is removed in 5.0; use FilterBar search slot from aura-glass/data.',
    doc: '#dep-s0209',
  },
  {
    id: 'DEP-S0210',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassStatCard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatCard from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassStatCard is removed in 5.0; use StatCard from aura-glass/data.',
    doc: '#dep-s0210',
    compat: 'GlassStatCard',
  },
  {
    id: 'DEP-S0211',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassKPICard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatCard from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassKPICard is removed in 5.0; use StatCard from aura-glass/data.',
    doc: '#dep-s0211',
    compat: 'GlassKPICard',
  },
  {
    id: 'DEP-S0212',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMetricCard',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatCard from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassMetricCard is removed in 5.0; use StatCard from aura-glass/data.',
    doc: '#dep-s0212',
    compat: 'GlassMetricCard',
  },
  {
    id: 'DEP-S0213',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMetricChip',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Chip from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassMetricChip is removed in 5.0; use Chip from aura-glass/data.',
    doc: '#dep-s0213',
  },
  {
    id: 'DEP-S0214',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAnimatedNumber',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'StatCard value from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassAnimatedNumber is removed in 5.0; use StatCard value from aura-glass/data.',
    doc: '#dep-s0214',
    compat: 'GlassAnimatedNumber',
  },
  {
    id: 'DEP-S0215',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSparkline',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Sparkline from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassSparkline is removed in 5.0; use Sparkline from aura-glass/data.',
    doc: '#dep-s0215',
    compat: 'GlassSparkline',
  },
  {
    id: 'DEP-S0216',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTimeline',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Timeline from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassTimeline is removed in 5.0; use Timeline from aura-glass.',
    doc: '#dep-s0216',
    compat: 'GlassTimeline',
  },
  {
    id: 'DEP-S0217',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassActivityFeed',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'ActivityFeed from aura-glass',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassActivityFeed is removed in 5.0; use ActivityFeed from aura-glass.',
    doc: '#dep-s0217',
    compat: 'GlassActivityFeed',
  },
  {
    id: 'DEP-S0218',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChip',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Chip from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassChip is removed in 5.0; use Chip from aura-glass/data.',
    doc: '#dep-s0218',
    compat: 'GlassChip',
  },
  {
    id: 'DEP-S0219',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassKeyValueEditor',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'KeyValueEditor from aura-glass/data',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassKeyValueEditor is removed in 5.0; use KeyValueEditor from aura-glass/data.',
    doc: '#dep-s0219',
    compat: 'GlassKeyValueEditor',
  },
  {
    id: 'DEP-S0220',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDateField',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'DateField from aura-glass/date',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassDateField is removed in 5.0; use DateField from aura-glass/date.',
    doc: '#dep-s0220',
    compat: 'GlassDateField',
  },
  {
    id: 'DEP-S0221',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTimeField',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'TimeField from aura-glass/date',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassTimeField is removed in 5.0; use TimeField from aura-glass/date.',
    doc: '#dep-s0221',
    compat: 'GlassTimeField',
  },
  {
    id: 'DEP-S0222',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDatePicker',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'DatePicker from aura-glass/date',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassDatePicker is removed in 5.0; use DatePicker from aura-glass/date.',
    doc: '#dep-s0222',
    compat: 'GlassDatePicker',
  },
  {
    id: 'DEP-S0223',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDateRangePicker',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'DateRangePicker from aura-glass/date',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassDateRangePicker is removed in 5.0; use DateRangePicker from aura-glass/date.',
    doc: '#dep-s0223',
    compat: 'GlassDateRangePicker',
  },
  {
    id: 'DEP-S0224',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCalendar',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Calendar from aura-glass/date',
    codemod: 'canonical-names',
    automation: 'mostly',
    breaking: 'B3',
    message: 'GlassCalendar is removed in 5.0; use Calendar from aura-glass/date.',
    doc: '#dep-s0224',
    compat: 'GlassCalendar',
  },
  {
    id: 'DEP-S0225',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDataChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassDataChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0225',
  },
  {
    id: 'DEP-S0226',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'DataChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'DataChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0226',
  },
  {
    id: 'DEP-S0227',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ModularGlassDataChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'ModularGlassDataChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0227',
  },
  {
    id: 'DEP-S0228',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0228',
  },
  {
    id: 'DEP-S0229',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLineChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassLineChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0229',
  },
  {
    id: 'DEP-S0230',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassBarChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassBarChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0230',
  },
  {
    id: 'DEP-S0231',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAreaChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassAreaChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0231',
  },
  {
    id: 'DEP-S0232',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPieChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassPieChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0232',
  },
  {
    id: 'DEP-S0233',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDonutChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassDonutChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0233',
  },
  {
    id: 'DEP-S0234',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChartContainer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassChartContainer is removed in 5.0 with no 4.x-shape replacement; ChartFrame from aura-glass/data.',
    doc: '#dep-s0234',
  },
  {
    id: 'DEP-S0235',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChartWidget',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassChartWidget is removed in 5.0 with no 4.x-shape replacement; ChartFrame from aura-glass/data.',
    doc: '#dep-s0235',
  },
  {
    id: 'DEP-S0236',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvancedDataViz',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassAdvancedDataViz is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0236',
  },
  {
    id: 'DEP-S0237',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChartsDemo',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassChartsDemo is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0237',
  },
  {
    id: 'DEP-S0238',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassHeatmap',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassHeatmap is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0238',
  },
  {
    id: 'DEP-S0239',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassGanttChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassGanttChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0239',
  },
  {
    id: 'DEP-S0240',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'KpiChart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'KpiChart is removed in 5.0 with no 4.x-shape replacement; the Chart entry ships on aura-glass/charts in 5.1.',
    doc: '#dep-s0240',
  },
  {
    id: 'DEP-S0241',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMetricsGrid',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassMetricsGrid is removed in 5.0 with no 4.x-shape replacement; StatCard composition from aura-glass/data.',
    doc: '#dep-s0241',
  },
  {
    id: 'DEP-S0242',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVirtualGrid',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassVirtualGrid is removed in 5.0 with no 4.x-shape replacement; Table with virtualize from aura-glass/data.',
    doc: '#dep-s0242',
  },
  {
    id: 'DEP-S0243',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassInfiniteScroll',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassInfiniteScroll is removed in 5.0 with no 4.x-shape replacement; Table with virtualize from aura-glass/data.',
    doc: '#dep-s0243',
  },
  {
    id: 'DEP-S0244',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassListView',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassListView is removed in 5.0 with no 4.x-shape replacement; Table from aura-glass/data.',
    doc: '#dep-s0244',
  },
  {
    id: 'DEP-S0245',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassFormTable',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassFormTable is removed in 5.0 with no 4.x-shape replacement; Table + forms composition.',
    doc: '#dep-s0245',
  },
  {
    id: 'DEP-S0246',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'TableWidget',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'TableWidget is removed in 5.0 with no 4.x-shape replacement; Table from aura-glass/data.',
    doc: '#dep-s0246',
  },
  {
    id: 'DEP-S0247',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDataGridPro',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'GlassDataGridPro is removed in 5.0 with no 4.x-shape replacement; Table from aura-glass/data.',
    doc: '#dep-s0247',
  },
  {
    id: 'DEP-S0248',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'QueryBuilder',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: null,
    codemod: null,
    automation: 'manual',
    breaking: 'B4',
    message: 'QueryBuilder is removed in 5.0 with no 4.x-shape replacement; the query-builder registry item.',
    doc: '#dep-s0248',
  },
] as const;
// --- lane W2 end ---

// --- lane W3 begin ---
// W3 rows (SURF-632, lane W3 block): the 4.x chat/AI family. The four chat
// components keep working through aura-glass/compat adapters (successor
// ./ai at 6.0.0); the simulated-AI/generative family is removed at 5.0 with
// no compat (no-simulation contract); GlassVoiceInput moves to the
// ai-voice-input registry item with no compat adapter.
const w3 = [
  {
    id: 'DEP-S0400',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChat',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Thread + Message + Composer from aura-glass/ai',
    codemod: 'ai-chat',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassChat is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to ./ai (Thread/Message/Composer).',
    doc: '#dep-s0400',
    compat: 'GlassChat',
  },
  {
    id: 'DEP-S0401',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassChatInput',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Composer from aura-glass/ai',
    codemod: 'ai-chat',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassChatInput is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to ./ai Composer.',
    doc: '#dep-s0401',
    compat: 'GlassChatInput',
  },
  {
    id: 'DEP-S0402',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMessageList',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Thread from aura-glass/ai',
    codemod: 'ai-chat',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassMessageList is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to ./ai Thread.',
    doc: '#dep-s0402',
    compat: 'GlassMessageList',
  },
  {
    id: 'DEP-S0403',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTypingIndicator',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'a streaming-status AgMessage or AgentSteps from aura-glass/ai',
    codemod: 'ai-chat',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassTypingIndicator is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Use a streaming-status message or AgentSteps.',
    doc: '#dep-s0403',
    compat: 'GlassTypingIndicator',
  },
  {
    id: 'DEP-S0404',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVoiceInput',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the ai-voice-input registry item',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassVoiceInput is removed in 5.0 with no compat adapter; install the ai-voice-input registry item.',
    doc: '#dep-s0404',
  },
  {
    id: 'DEP-S0405',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPredictiveChat',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassPredictiveChat is removed in 5.0; predictive/simulated AI surfaces are rejected by the contract (no-simulation).',
    doc: '#dep-s0405',
  },
  {
    id: 'DEP-S0406',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPredictiveEngine',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassPredictiveEngine is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0406',
  },
  {
    id: 'DEP-S0407',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'usePredictiveEngine',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'usePredictiveEngine is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0407',
  },
  {
    id: 'DEP-S0408',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAutoComposer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassAutoComposer is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0408',
  },
  {
    id: 'DEP-S0409',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useAutoComposer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'useAutoComposer is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0409',
  },
  {
    id: 'DEP-S0410',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AIGlassThemeProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'AIGlassThemeProvider is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0410',
  },
  {
    id: 'DEP-S0411',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassGANGenerator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 — generative-art surfaces are deferred',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassGANGenerator is removed in 5.0; generative-art surfaces are deferred to 5.1.',
    doc: '#dep-s0411',
  },
  {
    id: 'DEP-S0412',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDeepDreamGlass',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 — generative-art surfaces are deferred',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassDeepDreamGlass is removed in 5.0; generative-art surfaces are deferred to 5.1.',
    doc: '#dep-s0412',
  },
  {
    id: 'DEP-S0413',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassStyleTransfer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 — generative-art surfaces are deferred',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassStyleTransfer is removed in 5.0; generative-art surfaces are deferred to 5.1.',
    doc: '#dep-s0413',
  },
  {
    id: 'DEP-S0414',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassGenerativeArt',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 — generative-art surfaces are deferred',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassGenerativeArt is removed in 5.0; generative-art surfaces are deferred to 5.1.',
    doc: '#dep-s0414',
  },
  {
    id: 'DEP-S0415',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'NeuromorphicLearningNetwork',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'NeuromorphicLearningNetwork is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0415',
  },
  {
    id: 'DEP-S0416',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'NeuralWeightVisualization',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'NeuralWeightVisualization is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0416',
  },
  {
    id: 'DEP-S0417',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMusicVisualizer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassMusicVisualizer is removed in 5.0; a Waveform surface lands at 5.1.',
    doc: '#dep-s0417',
  },
  {
    id: 'DEP-S0418',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVoiceWaveform',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassVoiceWaveform is removed in 5.0; a Waveform surface lands at 5.1.',
    doc: '#dep-s0418',
  },
  {
    id: 'DEP-S0419',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLiveFilter',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassLiveFilter is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0419',
  },
  {
    id: 'DEP-S0420',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPredictionIndicator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'GlassPredictionIndicator is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0420',
  },
  {
    id: 'DEP-S0421',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'useInteractionRecorder',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'useInteractionRecorder is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0421',
  },
  {
    id: 'DEP-S0422',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'predictiveEnginePresets',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'none — predictive/simulated AI is rejected at 5.0',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message: 'predictiveEnginePresets is removed in 5.0 (no-simulation contract).',
    doc: '#dep-s0422',
  },
] as const;
// --- lane W3 end ---

// --- lane W4 begin ---
// W4 rows (SURF-632, lane W4 block): the 4.x media/backdrop family. The 13
// adapters keep working through aura-glass/compat until 6.0.0; removed names
// map to registry items, native elements, the labs ParticleField, or the
// 5.1 Waveform.
const w4 = [
  {
    id: 'DEP-S0600',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassMediaControls',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'MediaControls.Root from aura-glass/media (media-video-player registry item composes it)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassMediaControls is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to MediaControls.Root from aura-glass/media (media-video-player registry item composes it).',
    doc: '#dep-s0600',
    compat: 'LiquidGlassMediaControls',
  },
  {
    id: 'DEP-S0601',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMediaControls',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'MediaControls.Root from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassMediaControls is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to MediaControls.Root from aura-glass/media.',
    doc: '#dep-s0601',
    compat: 'GlassMediaControls',
  },
  {
    id: 'DEP-S0602',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassNowPlayingBar',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'NowPlayingBar from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassNowPlayingBar is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to NowPlayingBar from aura-glass/media.',
    doc: '#dep-s0602',
    compat: 'LiquidGlassNowPlayingBar',
  },
  {
    id: 'DEP-S0603',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassPhotoInspector',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'ImageViewer + Inspector from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassPhotoInspector is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to ImageViewer + Inspector from aura-glass/media.',
    doc: '#dep-s0603',
    compat: 'LiquidGlassPhotoInspector',
  },
  {
    id: 'DEP-S0604',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassImageViewer',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'ImageViewer from aura-glass/media (items need id + required alt)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassImageViewer is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to ImageViewer from aura-glass/media (items need id + required alt).',
    doc: '#dep-s0604',
    compat: 'GlassImageViewer',
  },
  {
    id: 'DEP-S0605',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCarousel',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'CarouselRail from aura-glass/media (infinite→loop, autoPlay gated)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassCarousel is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to CarouselRail from aura-glass/media (infinite→loop, autoPlay gated).',
    doc: '#dep-s0605',
    compat: 'GlassCarousel',
  },
  {
    id: 'DEP-S0606',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassCarouselRail',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'CarouselRail from aura-glass/media',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'LiquidGlassCarouselRail is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to CarouselRail from aura-glass/media.',
    doc: '#dep-s0606',
    compat: 'LiquidGlassCarouselRail',
  },
  {
    id: 'DEP-S0607',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AuroraBackground',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="aurora" from aura-glass/backdrops (motion none|subtle→static, full→drift)',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AuroraBackground is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop preset="aurora" from aura-glass/backdrops (motion none|subtle→static, full→drift).',
    doc: '#dep-s0607',
    compat: 'AuroraBackground',
  },
  {
    id: 'DEP-S0608',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AuroraOrb',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="aurora" from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AuroraOrb is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop preset="aurora" from aura-glass/backdrops.',
    doc: '#dep-s0608',
    compat: 'AuroraOrb',
  },
  {
    id: 'DEP-S0609',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'AtmosphericBackground',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'AtmosphericBackground is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0609',
    compat: 'AtmosphericBackground',
  },
  {
    id: 'DEP-S0610',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassDynamicAtmosphere',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassDynamicAtmosphere is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0610',
    compat: 'GlassDynamicAtmosphere',
  },
  {
    id: 'DEP-S0611',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'DynamicAtmosphere',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop presets from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'DynamicAtmosphere is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop presets from aura-glass/backdrops.',
    doc: '#dep-s0611',
    compat: 'DynamicAtmosphere',
  },
  {
    id: 'DEP-S0612',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMeshGradient',
    since: '4.2.0',
    removeIn: '6.0.0',
    replacement: 'Backdrop preset="mesh" from aura-glass/backdrops',
    codemod: 'media-backdrops',
    automation: 'partial',
    breaking: 'B4',
    message:
      'GlassMeshGradient is removed from aura-glass in 5.0; the aura-glass/compat adapter keeps working until 6.0.0. Migrate to Backdrop preset="mesh" from aura-glass/backdrops.',
    doc: '#dep-s0612',
    compat: 'GlassMeshGradient',
  },
  {
    id: 'DEP-S0613',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassGallery',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-gallery registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassGallery is removed in 5.0; the media-gallery registry item.',
    doc: '#dep-s0613',
  },
  {
    id: 'DEP-S0614',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageList',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native <img>',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageList is removed in 5.0; CMP Grid + native <img>.',
    doc: '#dep-s0614',
  },
  {
    id: 'DEP-S0615',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageListItem',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native <img>',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageListItem is removed in 5.0; CMP Grid + native <img>.',
    doc: '#dep-s0615',
  },
  {
    id: 'DEP-S0616',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ImageListItemBar',
    since: '4.3.0',
    removeIn: '5.0.0',
    replacement: 'CMP Grid + native <img>',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ImageListItemBar is removed in 5.0; CMP Grid + native <img>.',
    doc: '#dep-s0616',
  },
  {
    id: 'DEP-S0617',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLazyImage',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'native img loading="lazy"',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassLazyImage is removed in 5.0; native img loading="lazy".',
    doc: '#dep-s0617',
  },
  {
    id: 'DEP-S0618',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVideoPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-video-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassVideoPlayer is removed in 5.0; the media-video-player registry item.',
    doc: '#dep-s0618',
  },
  {
    id: 'DEP-S0619',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvancedVideoPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-video-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassAdvancedVideoPlayer is removed in 5.0; the media-video-player registry item.',
    doc: '#dep-s0619',
  },
  {
    id: 'DEP-S0620',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassAdvancedAudioPlayer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the media-audio-player registry item',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassAdvancedAudioPlayer is removed in 5.0; the media-audio-player registry item.',
    doc: '#dep-s0620',
  },
  {
    id: 'DEP-S0621',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMediaProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'useMediaElement from aura-glass/media',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMediaProvider is removed in 5.0; useMediaElement from aura-glass/media.',
    doc: '#dep-s0621',
  },
  {
    id: 'DEP-S0622',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassVoiceWaveform',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'no successor until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassVoiceWaveform is removed in 5.0; no successor until 5.1 (Waveform).',
    doc: '#dep-s0622',
  },
  {
    id: 'DEP-S0623',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassMusicVisualizer',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'no successor until 5.1 (Waveform)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassMusicVisualizer is removed in 5.0; no successor until 5.1 (Waveform).',
    doc: '#dep-s0623',
  },
  {
    id: 'DEP-S0624',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'ParticleBackground',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (rebuilt on the seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'ParticleBackground is removed in 5.0; the labs ParticleField (rebuilt on the seeded PRNG).',
    doc: '#dep-s0624',
  },
  {
    id: 'DEP-S0625',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassParticles',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (rebuilt on the seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassParticles is removed in 5.0; the labs ParticleField (rebuilt on the seeded PRNG).',
    doc: '#dep-s0625',
  },
  {
    id: 'DEP-S0626',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassParticleField',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the labs ParticleField (rebuilt on the seeded PRNG)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassParticleField is removed in 5.0; the labs ParticleField (rebuilt on the seeded PRNG).',
    doc: '#dep-s0626',
  },
  {
    id: 'DEP-S0627',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'LiquidGlassBackdropSampler',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'Backdrop + useMediaElement({ sampleTone: true })',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'LiquidGlassBackdropSampler is removed in 5.0; Backdrop + useMediaElement({ sampleTone: true }).',
    doc: '#dep-s0627',
  },
] as const;
// --- lane W4 end ---

// --- lane W5 begin ---
// W5 rows cover the ./workspace and ./workflows 4.x subpaths and the
// commerce/presence/comment 4.x exports (Prompt-4 W5 step 3). All ship in the
// 4.2.0 minor: `status: 'planned'` stays until PLAT's release tooling
// publishes 4.2.0 (verify-deprecations fails 'active' when since > line
// version and 'planned' when since <= it).
const w5 = [
  {
    id: 'DEP-S0800',
    kind: 'subpath',
    status: 'planned',
    entry: './workspace',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: "aura-glass/app-shell (the 5.x AppShell composition replaces the 4.x workspace layout subpath)",
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      "aura-glass/workspace is removed in 5.0; migrate to aura-glass/app-shell — the AppShell composition replaces the workspace layout subpath.",
    doc: '#dep-s0800',
  },
  {
    id: 'DEP-S0801',
    kind: 'subpath',
    status: 'planned',
    entry: './workflows',
    symbol: '*',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'aura-glass/app-shell workspace recipes and the 5.x registry blocks',
    codemod: 'imports-subpaths',
    automation: 'full',
    breaking: 'B4',
    message:
      'aura-glass/workflows is removed in 5.0; the app-shell workspace recipes and 5.x registry blocks replace every export this subpath re-exported.',
    doc: '#dep-s0801',
  },
  {
    id: 'DEP-S0802',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'SmartShoppingCart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'GlassSmartShoppingCart until 5.0, then the commerce-cart registry block (5.1)',
    codemod: 'canonical-names',
    automation: 'full',
    breaking: 'B3',
    message:
      'The SmartShoppingCart alias is removed in 5.0; it is the same component as GlassSmartShoppingCart, which itself is replaced by the commerce-cart registry block (5.1).',
    doc: '#dep-s0802',
  },
  {
    id: 'DEP-S0803',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCommentThread',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the comment-thread registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassCommentThread is removed in 5.0; use the comment-thread registry item (5.1), the single comment surface consolidated from the 4.x duplicates.',
    doc: '#dep-s0803',
  },
  {
    id: 'DEP-S0804',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassSmartShoppingCart',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the commerce-cart registry block (5.1): controlled cart UI with no baked-in business logic',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassSmartShoppingCart is removed in 5.0; use the commerce-cart registry block (5.1) — controlled cart UI that holds no discounts, tax or currency logic.',
    doc: '#dep-s0804',
  },
  {
    id: 'DEP-S0805',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassProductRecommendations',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the commerce registry blocks (5.1) composed on Card and CarouselRail',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassProductRecommendations is removed in 5.0; compose the commerce registry blocks (5.1) on Card and CarouselRail instead.',
    doc: '#dep-s0805',
  },
  {
    id: 'DEP-S0806',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassEcommerceProvider',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'consumer-owned commerce state; the 5.x commerce registry blocks take data by props',
    codemod: 'removed',
    automation: 'manual',
    breaking: 'B3',
    message:
      'GlassEcommerceProvider is removed in 5.0; keep commerce state in your app — the 5.x commerce registry blocks take data by props only.',
    doc: '#dep-s0806',
  },
  {
    id: 'DEP-S0807',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTeamCursors',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassTeamCursors is removed in 5.0; use the presence-stack registry item (5.1) — it only drew three fake cursors with no data input.',
    doc: '#dep-s0807',
  },
  {
    id: 'DEP-S0808',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassTeamCursorsWithEffects',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassTeamCursorsWithEffects is removed in 5.0; use the presence-stack registry item (5.1) — the effect variant layered static circles on fake cursors.',
    doc: '#dep-s0808',
  },
  {
    id: 'DEP-S0809',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCollaborativeComments',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the comment-thread registry item (5.1) plus an anchored-popover pin primitive',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassCollaborativeComments is removed in 5.0; use the comment-thread registry item (5.1) — spatial pins become an anchored-popover primitive.',
    doc: '#dep-s0809',
  },
  {
    id: 'DEP-S0810',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassUserPresence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassUserPresence is removed in 5.0; use the presence-stack registry item (5.1) — deterministic ids replace its random presence colours.',
    doc: '#dep-s0810',
  },
  {
    id: 'DEP-S0811',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassPresenceIndicator',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1)',
    codemod: 'removed',
    automation: 'mostly',
    breaking: 'B3',
    message:
      'GlassPresenceIndicator is removed in 5.0; use the presence-stack registry item (5.1).',
    doc: '#dep-s0811',
  },
  {
    id: 'DEP-S0812',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassLiveCursorPresence',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1) fed by consumer presence data',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassLiveCursorPresence is removed in 5.0; render live cursors from your own presence channel through the presence-stack registry item (5.1).',
    doc: '#dep-s0812',
  },
  {
    id: 'DEP-S0813',
    kind: 'export',
    status: 'planned',
    entry: '.',
    symbol: 'GlassCollaborativeCursor',
    since: '4.2.0',
    removeIn: '5.0.0',
    replacement: 'the presence-stack registry item (5.1) fed by consumer presence data',
    codemod: 'removed',
    automation: 'partial',
    breaking: 'B3',
    message:
      'GlassCollaborativeCursor is removed in 5.0; render live cursors from your own presence channel through the presence-stack registry item (5.1).',
    doc: '#dep-s0813',
  },
] as const;
// --- lane W5 end ---

export default [...w1, ...w2, ...w3, ...w4, ...w5] satisfies DeprecationFragment;
