/* @jest-environment node */
/* tests/deprecations/breaking-register.test.ts — REQ-PLAT-29 (PLAT-194/195),
   AC-FIN-33. The register holds B1..B21 with the PRD B17–B19 scopes; an
   unreferenced B-id, a notice B-id without a notice entry and a missing
   #b-<n> anchor each fail; the guide generated by gen-deprecations --docs
   carries one titled #b-<n> heading per referenced B-id; coverage honours the
   exception allowlist only for entries with `exception` set.
   Replaces tests/deprecations/breaking-register.test.mjs. */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from '@jest/globals';
import { anchorsOf, checkRegister, coverage } from '../../scripts/release/verify-breaking-register.mjs';
import { docsMd, loadBreakingRegister } from '../../scripts/release/gen-deprecations.mjs';

const REGISTER = join(process.cwd(), 'docs/release/breaking-changes.json');
const register = JSON.parse(readFileSync(REGISTER, 'utf8'));
const E = (id: string, b: string, kind = 'export', o: Record<string, unknown> = {}) => ({
  id, kind, breaking: b, symbol: 'x', since: '4.2.0', removeIn: '5.0.0', codemod: 'canonical-names', ...o,
});
const GUIDE = '<h2 id="b-1">B1</h2><h2 id="b-3">B3</h2>';

describe('the committed register', () => {
  it('contains B1..B21 exactly once, in order', () => {
    const ids = register.items.map((i: { id: string }) => i.id);
    expect(ids).toEqual(Array.from({ length: 21 }, (_, i) => `B${i + 1}`));
  });
  it('every item has the §11 fields', () => {
    for (const item of register.items) {
      expect(item.title).toBeTruthy();
      expect(item.affected).toBeTruthy();
      expect(item.cdIn).toMatch(/^4\.\d+\.\d+$/);
      expect(item.path).toBeTruthy();
      expect('codemod' in item && 'escapeHatch' in item).toBe(true);
    }
  });
  it('B17–B21 carry the PRD REQ-PLAT-29 scopes', () => {
    const t = (id: string) => register.items.find((i: { id: string }) => i.id === id).title;
    expect(t('B17')).toContain('./styles → ./styles.css');
    expect(t('B17')).toContain('./tokens/css → ./tokens.css');
    expect(t('B17')).toContain('./tokens/tailwind → ./tailwind.css');
    expect(t('B18')).toContain('./primitives/<name> → ./primitives');
    expect(t('B19')).toContain('./icons/<category> → ./icons/<name>');
    expect(t('B19')).toMatch(/\.\/utils\/env, \.\/tokens\/json, \.\/tokens\/manifest removed/);
    expect(t('B20')).toMatch(/[Dd]ead optical/);
    expect(t('B21')).toMatch(/[Pp]rovider/);
  });
});

describe('checkRegister', () => {
  it('fails when a B-id is unreferenced', () => {
    expect(checkRegister([{ id: 'B9' }], [], GUIDE).join()).toMatch(/B9: not referenced/);
  });
  it('fails when a notice B-id (B1, B2, B13) has no peer|engine|behavior entry with codemod null', () => {
    expect(checkRegister([{ id: 'B1' }], [E('DEP-P0001', 'B1')], GUIDE).join())
      .toMatch(/B1: notice B-id needs a kind peer\|engine\|behavior entry with codemod null/);
    expect(checkRegister([{ id: 'B1' }], [E('DEP-P0001', 'B1', 'engine')], GUIDE).join()).toMatch(/notice B-id/);
  });
  it('accepts a notice entry for B1', () => {
    expect(checkRegister([{ id: 'B1' }], [E('DEP-P0001', 'B1', 'engine', { codemod: null })], GUIDE)).toEqual([]);
  });
  it('fails when the anchor is missing from the guide', () => {
    expect(checkRegister([{ id: 'B4' }], [E('DEP-P0001', 'B4')], GUIDE).join()).toMatch(/B4: no #b-4 anchor/);
  });
  it('passes a covered id with anchor', () => {
    expect(checkRegister([{ id: 'B3' }], [E('DEP-P0001', 'B3')], GUIDE)).toEqual([]);
  });
  it('anchorsOf parses b-<n> and dep-dep-<id> anchors', () => {
    expect([...anchorsOf('x id="b-7" y id="dep-dep-c0001" z id="other"')]).toEqual(['b-7', 'dep-dep-c0001']);
  });
});

describe('generated guide', () => {
  it('has a titled #b-<n> heading for each referenced B-id and passes checkRegister', () => {
    const items = loadBreakingRegister(REGISTER);
    const entries = items.map((it: { id: string }, i: number) =>
      E(`DEP-P${String(i + 1).padStart(4, '0')}`, it.id, ['B1', 'B2', 'B13'].includes(it.id) ? 'behavior' : 'export',
        { codemod: ['B1', 'B2', 'B13'].includes(it.id) ? null : 'canonical-names', message: 'm', doc: '#dep-x', entry: '.' }));
    const md = docsMd(entries, items);
    expect([...md.matchAll(/<h2 id="b-(\d+)">/g)]).toHaveLength(21);
    expect(md).toContain(`<h2 id="b-17">B17 — ${items[16].title}</h2>`);
    expect(checkRegister(items, entries, md)).toEqual([]);
  });
});

describe('coverage output', () => {
  it('shape: version, total, uncoveredCount, per-entry rows', () => {
    const c = coverage([E('DEP-P0001', 'B3')], { published: { '4.2.0': ['DEP-P0001'] } });
    expect(c).toMatchObject({ version: 1, total: 1, uncoveredCount: 0 });
    expect(c.entries[0]).toMatchObject({ id: 'DEP-P0001', coverage: 'covered', verifiedIn: '4.2.0' });
  });
  it('unpublished since → uncovered', () => {
    expect(coverage([E('DEP-P0001', 'B3')], { published: {} }).entries[0].coverage).toBe('uncovered');
  });
  it('allowlist covers only entries that carry an exception', () => {
    const allowlist = new Set(['DEP-P0001', 'DEP-P0002']);
    const c = coverage([E('DEP-P0001', 'B3', 'export', { exception: 'security' }), E('DEP-P0002', 'B3')], { allowlist });
    expect(c.entries.map((r: { coverage: string }) => r.coverage)).toEqual(['covered', 'uncovered']);
    expect(c.entries[0].verifiedIn).toBe('exception');
  });
});
